#
#
# Makefile for some ProjectEuler problems
#
#

######

.PHONY: all
all:: checkall
all:: cleanall

######

checkall:: problem1
problem1: ; make -C PE-problem1 checkall
checkall:: problem2
problem2: ; make -C PE-problem2 checkall
checkall:: problem3
problem3: ; make -C PE-problem3 checkall
checkall:: problem4
problem4: ; make -C PE-problem4 checkall
checkall:: problem5
problem5: ; make -C PE-problem5 checkall
checkall:: problem6
problem6: ; make -C PE-problem6 checkall
checkall:: problem7
problem7: ; make -C PE-problem7 checkall
checkall:: problem8
problem8: ; make -C PE-problem8 checkall
checkall:: problem9
problem9: ; make -C PE-problem9 checkall

checkall:: problem10
problem10: ; make -C PE-problem10 checkall
checkall:: problem11
problem11: ; make -C PE-problem11 checkall
checkall:: problem12
problem12: ; make -C PE-problem12 checkall
checkall:: problem13
problem13: ; make -C PE-problem13 checkall
checkall:: problem14
problem14: ; make -C PE-problem14 checkall
checkall:: problem15
problem15: ; make -C PE-problem15 checkall
checkall:: problem16
problem16: ; make -C PE-problem16 checkall
checkall:: problem17
problem17: ; make -C PE-problem17 checkall
checkall:: problem18
problem18: ; make -C PE-problem18 checkall
checkall:: problem19
problem19: ; make -C PE-problem19 checkall

checkall:: problem20
problem20: ; make -C PE-problem20 checkall
checkall:: problem21
problem21: ; make -C PE-problem21 checkall
checkall:: problem22
problem22: ; make -C PE-problem22 checkall
checkall:: problem23
problem23: ; make -C PE-problem23 checkall
checkall:: problem24
problem24: ; make -C PE-problem24 checkall
checkall:: problem25
problem25: ; make -C PE-problem25 checkall
checkall:: problem26
problem26: ; make -C PE-problem26 checkall
checkall:: problem27
problem27: ; make -C PE-problem27 checkall
checkall:: problem28
problem28: ; make -C PE-problem28 checkall
checkall:: problem29
problem29: ; make -C PE-problem29 checkall

checkall:: problem30
problem30: ; make -C PE-problem30 checkall
checkall:: problem31
problem31: ; make -C PE-problem31 checkall
checkall:: problem32
problem32: ; make -C PE-problem32 checkall
checkall:: problem33
problem33: ; make -C PE-problem33 checkall
checkall:: problem34
problem34: ; make -C PE-problem34 checkall
checkall:: problem35
problem35: ; make -C PE-problem35 checkall
checkall:: problem36
problem36: ; make -C PE-problem36 checkall
checkall:: problem37
problem37: ; make -C PE-problem37 checkall
checkall:: problem38
problem38: ; make -C PE-problem38 checkall
checkall:: problem39
problem39: ; make -C PE-problem39 checkall

checkall:: problem40
problem40: ; make -C PE-problem40 checkall
checkall:: problem41
problem41: ; make -C PE-problem41 checkall
checkall:: problem42
problem42: ; make -C PE-problem42 checkall
checkall:: problem43
problem43: ; make -C PE-problem43 checkall
checkall:: problem44
problem44: ; make -C PE-problem44 checkall
checkall:: problem45
problem45: ; make -C PE-problem45 checkall
checkall:: problem46
problem46: ; make -C PE-problem46 checkall
checkall:: problem47
problem47: ; make -C PE-problem47 checkall
checkall:: problem48
problem48: ; make -C PE-problem48 checkall
checkall:: problem49
problem49: ; make -C PE-problem49 checkall

checkall:: problem50
problem50: ; make -C PE-problem50 checkall
checkall:: problem51
problem51: ; make -C PE-problem51 checkall
checkall:: problem52
problem52: ; make -C PE-problem52 checkall
checkall:: problem53
problem53: ; make -C PE-problem53 checkall
checkall:: problem55
problem55: ; make -C PE-problem55 checkall
checkall:: problem56
problem56: ; make -C PE-problem56 checkall
checkall:: problem57
problem57: ; make -C PE-problem57 checkall
checkall:: problem58
problem58: ; make -C PE-problem58 checkall

checkall:: problem60
problem60: ; make -C PE-problem60 checkall
checkall:: problem63
problem63: ; make -C PE-problem63 checkall
checkall:: problem65
problem65: ; make -C PE-problem65 checkall
checkall:: problem66
problem66: ; make -C PE-problem66 checkall
checkall:: problem69
problem69: ; make -C PE-problem69 checkall

checkall:: problem71
problem71: ; make -C PE-problem71 checkall
checkall:: problem73
problem73: ; make -C PE-problem73 checkall
checkall:: problem75
problem75: ; make -C PE-problem75 checkall
checkall:: problem76
problem76: ; make -C PE-problem76 checkall
checkall:: problem77
problem77: ; make -C PE-problem77 checkall
checkall:: problem78
problem78: ; make -C PE-problem78 checkall

checkall:: problem80
problem80: ; make -C PE-problem80 checkall

checkall:: problem92
problem92: ; make -C PE-problem92 checkall
checkall:: problem94
problem94: ; make -C PE-problem94 checkall
checkall:: problem97
problem97: ; make -C PE-problem97 checkall

checkall:: problem100
problem100: ; make -C PE-problem100 checkall
checkall:: problem104
problem104: ; make -C PE-problem104 checkall
checkall:: problem108
problem108: ; make -C PE-problem108 checkall
checkall:: problem110
problem110: ; make -C PE-problem110 checkall
checkall:: problem120
problem120: ; make -C PE-problem120 checkall
checkall:: problem122
problem122: ; make -C PE-problem122 checkall
checkall:: problem123
problem123: ; make -C PE-problem123 checkall
checkall:: problem125
problem125: ; make -C PE-problem125 checkall
checkall:: problem145
problem145: ; make -C PE-problem145 checkall
checkall:: problem157
problem157: ; make -C PE-problem157 checkall
checkall:: problem162
problem162: ; make -C PE-problem162 checkall
checkall:: problem164
problem164: ; make -C PE-problem164 checkall
checkall:: problem169
problem169: ; make -C PE-problem169 checkall
checkall:: problem301
problem301: ; make -C PE-problem301 checkall

######

Makefiles:: Makefile_problem1
Makefile_problem1: ; ./utils/makefilegen problem1 > PE-problem1/Makefile
Makefiles:: Makefile_problem2
Makefile_problem2: ; ./utils/makefilegen problem2 > PE-problem2/Makefile
Makefiles:: Makefile_problem3
Makefile_problem3: ; ./utils/makefilegen problem3 > PE-problem3/Makefile
Makefiles:: Makefile_problem4
Makefile_problem4: ; ./utils/makefilegen problem4 > PE-problem4/Makefile
Makefiles:: Makefile_problem5
Makefile_problem5: ; ./utils/makefilegen problem5 > PE-problem5/Makefile
Makefiles:: Makefile_problem6
Makefile_problem6: ; ./utils/makefilegen problem6 > PE-problem6/Makefile
Makefiles:: Makefile_problem7
Makefile_problem7: ; ./utils/makefilegen problem7 > PE-problem7/Makefile
Makefiles:: Makefile_problem8
Makefile_problem8: ; ./utils/makefilegen problem8 > PE-problem8/Makefile
Makefiles:: Makefile_problem9
Makefile_problem9: ; ./utils/makefilegen problem9 > PE-problem9/Makefile

Makefiles:: Makefile_problem10
Makefile_problem10: ; ./utils/makefilegen problem10 > PE-problem10/Makefile
Makefiles:: Makefile_problem11
Makefile_problem11: ; ./utils/makefilegen problem11 > PE-problem11/Makefile
Makefiles:: Makefile_problem12
Makefile_problem12: ; ./utils/makefilegen problem12 > PE-problem12/Makefile
Makefiles:: Makefile_problem13
Makefile_problem13: ; ./utils/makefilegen problem13 > PE-problem13/Makefile
Makefiles:: Makefile_problem14
Makefile_problem14: ; ./utils/makefilegen problem14 > PE-problem14/Makefile
Makefiles:: Makefile_problem15
Makefile_problem15: ; ./utils/makefilegen problem15 > PE-problem15/Makefile
Makefiles:: Makefile_problem16
Makefile_problem16: ; ./utils/makefilegen problem16 > PE-problem16/Makefile
Makefiles:: Makefile_problem17
Makefile_problem17: ; ./utils/makefilegen problem17 > PE-problem17/Makefile
Makefiles:: Makefile_problem18
Makefile_problem18: ; ./utils/makefilegen problem18 > PE-problem18/Makefile
Makefiles:: Makefile_problem19
Makefile_problem19: ; ./utils/makefilegen problem19 > PE-problem19/Makefile

Makefiles:: Makefile_problem20
Makefile_problem20: ; ./utils/makefilegen problem20 > PE-problem20/Makefile
Makefiles:: Makefile_problem21
Makefile_problem21: ; ./utils/makefilegen problem21 > PE-problem21/Makefile
Makefiles:: Makefile_problem22
Makefile_problem22: ; ./utils/makefilegen problem22 > PE-problem22/Makefile
Makefiles:: Makefile_problem23
Makefile_problem23: ; ./utils/makefilegen problem23 > PE-problem23/Makefile
Makefiles:: Makefile_problem24
Makefile_problem24: ; ./utils/makefilegen problem24 > PE-problem24/Makefile
Makefiles:: Makefile_problem25
Makefile_problem25: ; ./utils/makefilegen problem25 > PE-problem25/Makefile
Makefiles:: Makefile_problem26
Makefile_problem26: ; ./utils/makefilegen problem26 > PE-problem26/Makefile
Makefiles:: Makefile_problem27
Makefile_problem27: ; ./utils/makefilegen problem27 > PE-problem27/Makefile
Makefiles:: Makefile_problem28
Makefile_problem28: ; ./utils/makefilegen problem28 > PE-problem28/Makefile
Makefiles:: Makefile_problem29
Makefile_problem29: ; ./utils/makefilegen problem29 > PE-problem29/Makefile

Makefiles:: Makefile_problem30
Makefile_problem30: ; ./utils/makefilegen problem30 > PE-problem30/Makefile
Makefiles:: Makefile_problem31
Makefile_problem31: ; ./utils/makefilegen problem31 > PE-problem31/Makefile
Makefiles:: Makefile_problem32
Makefile_problem32: ; ./utils/makefilegen problem32 > PE-problem32/Makefile
Makefiles:: Makefile_problem33
Makefile_problem33: ; ./utils/makefilegen problem33 > PE-problem33/Makefile
Makefiles:: Makefile_problem34
Makefile_problem34: ; ./utils/makefilegen problem34 > PE-problem34/Makefile
Makefiles:: Makefile_problem35
Makefile_problem35: ; ./utils/makefilegen problem35 > PE-problem35/Makefile
Makefiles:: Makefile_problem36
Makefile_problem36: ; ./utils/makefilegen problem36 > PE-problem36/Makefile
Makefiles:: Makefile_problem37
Makefile_problem37: ; ./utils/makefilegen problem37 > PE-problem37/Makefile
Makefiles:: Makefile_problem38
Makefile_problem38: ; ./utils/makefilegen problem38 > PE-problem38/Makefile
Makefiles:: Makefile_problem39
Makefile_problem39: ; ./utils/makefilegen problem39 > PE-problem39/Makefile

Makefiles:: Makefile_problem40
Makefile_problem40: ; ./utils/makefilegen problem40 > PE-problem40/Makefile
Makefiles:: Makefile_problem41
Makefile_problem41: ; ./utils/makefilegen problem41 > PE-problem41/Makefile
Makefiles:: Makefile_problem42
Makefile_problem42: ; ./utils/makefilegen problem42 > PE-problem42/Makefile
Makefiles:: Makefile_problem43
Makefile_problem43: ; ./utils/makefilegen problem43 > PE-problem43/Makefile
Makefiles:: Makefile_problem44
Makefile_problem44: ; ./utils/makefilegen problem44 > PE-problem44/Makefile
Makefiles:: Makefile_problem45
Makefile_problem45: ; ./utils/makefilegen problem45 > PE-problem45/Makefile
Makefiles:: Makefile_problem46
Makefile_problem46: ; ./utils/makefilegen problem46 > PE-problem46/Makefile
Makefiles:: Makefile_problem47
Makefile_problem47: ; ./utils/makefilegen problem47 > PE-problem47/Makefile
Makefiles:: Makefile_problem48
Makefile_problem48: ; ./utils/makefilegen problem48 > PE-problem48/Makefile
Makefiles:: Makefile_problem49
Makefile_problem49: ; ./utils/makefilegen problem49 > PE-problem49/Makefile

Makefiles:: Makefile_problem50
Makefile_problem50: ; ./utils/makefilegen problem50 > PE-problem50/Makefile
Makefiles:: Makefile_problem51
Makefile_problem51: ; ./utils/makefilegen problem51 > PE-problem51/Makefile
Makefiles:: Makefile_problem52
Makefile_problem52: ; ./utils/makefilegen problem52 > PE-problem52/Makefile
Makefiles:: Makefile_problem53
Makefile_problem53: ; ./utils/makefilegen problem53 > PE-problem53/Makefile
Makefiles:: Makefile_problem55
Makefile_problem55: ; ./utils/makefilegen problem55 > PE-problem55/Makefile
Makefiles:: Makefile_problem56
Makefile_problem56: ; ./utils/makefilegen problem56 > PE-problem56/Makefile
Makefiles:: Makefile_problem57
Makefile_problem57: ; ./utils/makefilegen problem57 > PE-problem57/Makefile
Makefiles:: Makefile_problem58
Makefile_problem58: ; ./utils/makefilegen problem58 > PE-problem58/Makefile

Makefiles:: Makefile_problem60
Makefile_problem60: ; ./utils/makefilegen problem60 > PE-problem60/Makefile
Makefiles:: Makefile_problem63
Makefile_problem63: ; ./utils/makefilegen problem63 > PE-problem63/Makefile
Makefiles:: Makefile_problem65
Makefile_problem65: ; ./utils/makefilegen problem65 > PE-problem65/Makefile
Makefiles:: Makefile_problem66
Makefile_problem66: ; ./utils/makefilegen problem66 > PE-problem66/Makefile
Makefiles:: Makefile_problem69
Makefile_problem69: ; ./utils/makefilegen problem69 > PE-problem69/Makefile

Makefiles:: Makefile_problem71
Makefile_problem71: ; ./utils/makefilegen problem71 > PE-problem71/Makefile
Makefiles:: Makefile_problem73
Makefile_problem73: ; ./utils/makefilegen problem73 > PE-problem73/Makefile
Makefiles:: Makefile_problem75
Makefile_problem75: ; ./utils/makefilegen problem75 > PE-problem75/Makefile
Makefiles:: Makefile_problem76
Makefile_problem76: ; ./utils/makefilegen problem76 > PE-problem76/Makefile
Makefiles:: Makefile_problem77
Makefile_problem77: ; ./utils/makefilegen problem77 > PE-problem77/Makefile
Makefiles:: Makefile_problem78
Makefile_problem78: ; ./utils/makefilegen problem78 > PE-problem78/Makefile
Makefiles:: Makefile_problem80
Makefile_problem80: ; ./utils/makefilegen problem80 > PE-problem80/Makefile

Makefiles:: Makefile_problem92
Makefile_problem92: ; ./utils/makefilegen problem92 > PE-problem92/Makefile
Makefiles:: Makefile_problem94
Makefile_problem94: ; ./utils/makefilegen problem94 > PE-problem94/Makefile
Makefiles:: Makefile_problem97
Makefile_problem97: ; ./utils/makefilegen problem97 > PE-problem97/Makefile

Makefiles:: Makefile_problem100
Makefile_problem100: ; ./utils/makefilegen problem100 > PE-problem100/Makefile
Makefiles:: Makefile_problem104
Makefile_problem104: ; ./utils/makefilegen problem104 > PE-problem104/Makefile
Makefiles:: Makefile_problem108
Makefile_problem108: ; ./utils/makefilegen problem108 > PE-problem108/Makefile
Makefiles:: Makefile_problem110
Makefile_problem110: ; ./utils/makefilegen problem110 > PE-problem110/Makefile
Makefiles:: Makefile_problem120
Makefile_problem120: ; ./utils/makefilegen problem120 > PE-problem120/Makefile
Makefiles:: Makefile_problem122
Makefile_problem122: ; ./utils/makefilegen problem122 > PE-problem122/Makefile
Makefiles:: Makefile_problem123
Makefile_problem123: ; ./utils/makefilegen problem123 > PE-problem123/Makefile
Makefiles:: Makefile_problem125
Makefile_problem125: ; ./utils/makefilegen problem125 > PE-problem125/Makefile
Makefiles:: Makefile_problem145
Makefile_problem145: ; ./utils/makefilegen problem145 > PE-problem145/Makefile
Makefiles:: Makefile_problem157
Makefile_problem157: ; ./utils/makefilegen problem157 > PE-problem157/Makefile
Makefiles:: Makefile_problem162
Makefile_problem162: ; ./utils/makefilegen problem162 > PE-problem162/Makefile
Makefiles:: Makefile_problem164
Makefile_problem164: ; ./utils/makefilegen problem164 > PE-problem164/Makefile
Makefiles:: Makefile_problem169
Makefile_problem169: ; ./utils/makefilegen problem169 > PE-problem169/Makefile
Makefiles:: Makefile_problem301
Makefile_problem301: ; ./utils/makefilegen problem301 > PE-problem301/Makefile

######

srclines::
	wc -l PE-problem*/*.?ats

######

cleanall::
	make -C utils cleanall
cleanall::
	make -C PE-problem1 cleanall
	make -C PE-problem2 cleanall
	make -C PE-problem3 cleanall
	make -C PE-problem4 cleanall
	make -C PE-problem5 cleanall
	make -C PE-problem6 cleanall
	make -C PE-problem7 cleanall
	make -C PE-problem8 cleanall
	make -C PE-problem9 cleanall
	make -C PE-problem10 cleanall
cleanall::
	make -C PE-problem11 cleanall
	make -C PE-problem12 cleanall
	make -C PE-problem13 cleanall
	make -C PE-problem14 cleanall
	make -C PE-problem15 cleanall
	make -C PE-problem16 cleanall
	make -C PE-problem17 cleanall
	make -C PE-problem18 cleanall
	make -C PE-problem19 cleanall
	make -C PE-problem20 cleanall
cleanall::
	make -C PE-problem21 cleanall
	make -C PE-problem22 cleanall
	make -C PE-problem23 cleanall
	make -C PE-problem24 cleanall
	make -C PE-problem25 cleanall
	make -C PE-problem26 cleanall
	make -C PE-problem27 cleanall
	make -C PE-problem28 cleanall
	make -C PE-problem29 cleanall
	make -C PE-problem30 cleanall
cleanall::
	make -C PE-problem31 cleanall
	make -C PE-problem32 cleanall
	make -C PE-problem33 cleanall
	make -C PE-problem34 cleanall
	make -C PE-problem35 cleanall
	make -C PE-problem36 cleanall
	make -C PE-problem37 cleanall
	make -C PE-problem38 cleanall
	make -C PE-problem39 cleanall
	make -C PE-problem40 cleanall
cleanall::
	make -C PE-problem41 cleanall
	make -C PE-problem42 cleanall
	make -C PE-problem43 cleanall
	make -C PE-problem44 cleanall
	make -C PE-problem45 cleanall
	make -C PE-problem46 cleanall
	make -C PE-problem47 cleanall
	make -C PE-problem48 cleanall
	make -C PE-problem49 cleanall
	make -C PE-problem50 cleanall
cleanall::
	make -C PE-problem51 cleanall
	make -C PE-problem52 cleanall
	make -C PE-problem53 cleanall
	make -C PE-problem55 cleanall
	make -C PE-problem56 cleanall
	make -C PE-problem57 cleanall
	make -C PE-problem58 cleanall
	make -C PE-problem60 cleanall
cleanall::
	make -C PE-problem63 cleanall
	make -C PE-problem65 cleanall
	make -C PE-problem66 cleanall
	make -C PE-problem69 cleanall
	make -C PE-problem71 cleanall
	make -C PE-problem73 cleanall
	make -C PE-problem75 cleanall
	make -C PE-problem76 cleanall
	make -C PE-problem77 cleanall
	make -C PE-problem78 cleanall
	make -C PE-problem80 cleanall
	make -C PE-problem92 cleanall
	make -C PE-problem94 cleanall
	make -C PE-problem97 cleanall
cleanall::
	make -C PE-problem100 cleanall
	make -C PE-problem104 cleanall
	make -C PE-problem108 cleanall
	make -C PE-problem110 cleanall
	make -C PE-problem120 cleanall
	make -C PE-problem122 cleanall
	make -C PE-problem123 cleanall
	make -C PE-problem125 cleanall
	make -C PE-problem145 cleanall
	make -C PE-problem157 cleanall
	make -C PE-problem162 cleanall
	make -C PE-problem164 cleanall
	make -C PE-problem169 cleanall
	make -C PE-problem301 cleanall

###### end of [Makefile] ######
