/*
**
** The C code is generated by ATS/Anairiats
** The compilation time is: 2013-8-29: 22h:22m
**
*/

/* include some .h files */
#ifndef _ATS_HEADER_NONE
#include "ats_config.h"
#include "ats_basics.h"
#include "ats_types.h"
#include "ats_exception.h"
#include "ats_memory.h"
#endif /* _ATS_HEADER_NONE */

/* include some .cats files */
#ifndef _ATS_PRELUDE_NONE
#include "prelude/CATS/basics.cats"
#include "prelude/CATS/bool.cats"
#include "prelude/CATS/byte.cats"
#include "prelude/CATS/char.cats"
#include "prelude/CATS/float.cats"
#include "prelude/CATS/integer.cats"
#include "prelude/CATS/integer_fixed.cats"
#include "prelude/CATS/integer_ptr.cats"
#include "prelude/CATS/lazy.cats"
#include "prelude/CATS/lazy_vt.cats"
#include "prelude/CATS/pointer.cats"
#include "prelude/CATS/printf.cats"
#include "prelude/CATS/reference.cats"
#include "prelude/CATS/sizetype.cats"
#include "prelude/CATS/string.cats"
#include "prelude/CATS/array.cats"
#include "prelude/CATS/list.cats"
#include "prelude/CATS/matrix.cats"
#include "prelude/CATS/option.cats"
#endif /* _ATS_PRELUDE_NONE */
/* prologues from statically loaded files */

#include "ats_intinf.cats"

#include "ats_counter.cats"

#include "ats_intinf.cats"

#include "ats_counter.cats"

#include "ats_intinf.cats"

#include "ats_counter.cats"

#include "ats_counter.cats"

#include "ats_intinf.cats"

#include "ats_counter.cats"

#include "ats_counter.cats"

#include "ats_intinf.cats"

#include "ats_counter.cats"

#include "ats_intinf.cats"

#include "ats_counter.cats"

#include "ats_counter.cats"

#include "ats_intinf.cats"

#include "ats_counter.cats"
/* external codes at top */
/* type definitions */
typedef struct {
ats_ptr_type atslab_hityp_name ;
ats_ptr_type atslab_hityp_node ;
} anairiats_rec_0 ;

typedef struct {
int tag ;
ats_ptr_type atslab_0 ;
ats_ptr_type atslab_1 ;
} anairiats_sum_1 ;

typedef struct {
int tag ;
ats_ptr_type atslab_0 ;
ats_ptr_type atslab_1 ;
ats_ptr_type atslab_2 ;
} anairiats_sum_2 ;

typedef struct {
int tag ;
ats_int_type atslab_0 ;
ats_ptr_type atslab_1 ;
} anairiats_sum_3 ;

typedef struct {
int tag ;
ats_ptr_type atslab_0 ;
} anairiats_sum_4 ;

typedef struct {
ats_int_type atslab_0 ;
ats_ptr_type atslab_1 ;
} anairiats_sum_5 ;

typedef struct {
ats_ptr_type atslab_hipat_loc ;
ats_ptr_type atslab_hipat_node ;
ats_ptr_type atslab_hipat_typ ;
ats_ptr_type atslab_hipat_asvar ;
} anairiats_rec_6 ;

typedef struct {
int tag ;
ats_int_type atslab_0 ;
ats_ptr_type atslab_1 ;
ats_ptr_type atslab_2 ;
} anairiats_sum_7 ;

typedef struct {
int tag ;
ats_bool_type atslab_0 ;
} anairiats_sum_8 ;

typedef struct {
int tag ;
ats_char_type atslab_0 ;
} anairiats_sum_9 ;

typedef struct {
int tag ;
ats_int_type atslab_0 ;
ats_ptr_type atslab_1 ;
ats_ptr_type atslab_2 ;
ats_ptr_type atslab_3 ;
} anairiats_sum_10 ;

typedef struct {
ats_ptr_type atslab_hiexp_loc ;
ats_ptr_type atslab_hiexp_node ;
ats_ptr_type atslab_hiexp_typ ;
} anairiats_rec_11 ;

typedef struct {
ats_ptr_type atslab_0 ;
} anairiats_sum_12 ;

typedef struct {
int tag ;
ats_ptr_type atslab_0 ;
ats_ptr_type atslab_1 ;
ats_ptr_type atslab_2 ;
ats_ptr_type atslab_3 ;
} anairiats_sum_13 ;

typedef struct {
int tag ;
ats_int_type atslab_0 ;
} anairiats_sum_14 ;

typedef struct {
int tag ;
ats_int_type atslab_0 ;
ats_int_type atslab_1 ;
ats_ptr_type atslab_2 ;
} anairiats_sum_15 ;

typedef struct {
int tag ;
ats_ptr_type atslab_0 ;
ats_int_type atslab_1 ;
} anairiats_sum_16 ;

typedef struct {
ats_ptr_type atslab_0 ;
ats_ptr_type atslab_1 ;
ats_ptr_type atslab_2 ;
} anairiats_sum_17 ;

typedef struct {
ats_ptr_type atslab_hilab_loc ;
ats_ptr_type atslab_hilab_node ;
} anairiats_rec_18 ;

/* external typedefs */
/* external dynamic constructor declarations */
ATSextern_val(ats_sum_type, ATS_2d0_2e2_2e10_2prelude_2basics_sta_2esats__None) ;
ATSextern_val(ats_sum_type, ATS_2d0_2e2_2e10_2prelude_2basics_sta_2esats__Some) ;
ATSextern_val(ats_sum_type, ATS_2d0_2e2_2e10_2src_2ats_hiexp_2esats__HITNAM) ;
ATSextern_val(ats_sum_type, ATS_2d0_2e2_2e10_2src_2ats_hiexp_2esats__HITextype) ;
ATSextern_val(ats_sum_type, ATS_2d0_2e2_2e10_2src_2ats_hiexp_2esats__HITfun) ;
ATSextern_val(ats_sum_type, ATS_2d0_2e2_2e10_2src_2ats_hiexp_2esats__HITrefarg) ;
ATSextern_val(ats_sum_type, ATS_2d0_2e2_2e10_2src_2ats_hiexp_2esats__HITs2var) ;
ATSextern_val(ats_sum_type, ATS_2d0_2e2_2e10_2src_2ats_hiexp_2esats__HITtyrectemp) ;
ATSextern_val(ats_sum_type, ATS_2d0_2e2_2e10_2src_2ats_hiexp_2esats__HITtyrecsin) ;
ATSextern_val(ats_sum_type, ATS_2d0_2e2_2e10_2src_2ats_hiexp_2esats__HITtysumtemp) ;
ATSextern_val(ats_sum_type, ATS_2d0_2e2_2e10_2src_2ats_hiexp_2esats__LABHIPATLSTcons) ;
ATSextern_val(ats_sum_type, ATS_2d0_2e2_2e10_2src_2ats_hiexp_2esats__LABHIPATLSTdot) ;
ATSextern_val(ats_sum_type, ATS_2d0_2e2_2e10_2src_2ats_hiexp_2esats__LABHIPATLSTnil) ;
ATSextern_val(ats_sum_type, ATS_2d0_2e2_2e10_2src_2ats_hiexp_2esats__HIPann) ;
ATSextern_val(ats_sum_type, ATS_2d0_2e2_2e10_2src_2ats_hiexp_2esats__HIPany) ;
ATSextern_val(ats_sum_type, ATS_2d0_2e2_2e10_2src_2ats_hiexp_2esats__HIPas) ;
ATSextern_val(ats_sum_type, ATS_2d0_2e2_2e10_2src_2ats_hiexp_2esats__HIPbool) ;
ATSextern_val(ats_sum_type, ATS_2d0_2e2_2e10_2src_2ats_hiexp_2esats__HIPchar) ;
ATSextern_val(ats_sum_type, ATS_2d0_2e2_2e10_2src_2ats_hiexp_2esats__HIPcon) ;
ATSextern_val(ats_sum_type, ATS_2d0_2e2_2e10_2src_2ats_hiexp_2esats__HIPcon_any) ;
ATSextern_val(ats_sum_type, ATS_2d0_2e2_2e10_2src_2ats_hiexp_2esats__HIPempty) ;
ATSextern_val(ats_sum_type, ATS_2d0_2e2_2e10_2src_2ats_hiexp_2esats__HIPfloat) ;
ATSextern_val(ats_sum_type, ATS_2d0_2e2_2e10_2src_2ats_hiexp_2esats__HIPint) ;
ATSextern_val(ats_sum_type, ATS_2d0_2e2_2e10_2src_2ats_hiexp_2esats__HIPlst) ;
ATSextern_val(ats_sum_type, ATS_2d0_2e2_2e10_2src_2ats_hiexp_2esats__HIPrec) ;
ATSextern_val(ats_sum_type, ATS_2d0_2e2_2e10_2src_2ats_hiexp_2esats__HIPstring) ;
ATSextern_val(ats_sum_type, ATS_2d0_2e2_2e10_2src_2ats_hiexp_2esats__HIPvar) ;
ATSextern_val(ats_sum_type, ATS_2d0_2e2_2e10_2src_2ats_hiexp_2esats__HILlab) ;
ATSextern_val(ats_sum_type, ATS_2d0_2e2_2e10_2src_2ats_hiexp_2esats__HILind) ;
ATSextern_val(ats_sum_type, ATS_2d0_2e2_2e10_2src_2ats_hiexp_2esats__LABHIEXPLSTcons) ;
ATSextern_val(ats_sum_type, ATS_2d0_2e2_2e10_2src_2ats_hiexp_2esats__LABHIEXPLSTnil) ;
ATSextern_val(ats_sum_type, ATS_2d0_2e2_2e10_2src_2ats_hiexp_2esats__HIEapp) ;
ATSextern_val(ats_sum_type, ATS_2d0_2e2_2e10_2src_2ats_hiexp_2esats__HIEarrinit) ;
ATSextern_val(ats_sum_type, ATS_2d0_2e2_2e10_2src_2ats_hiexp_2esats__HIEarrpsz) ;
ATSextern_val(ats_sum_type, ATS_2d0_2e2_2e10_2src_2ats_hiexp_2esats__HIEassgn_ptr) ;
ATSextern_val(ats_sum_type, ATS_2d0_2e2_2e10_2src_2ats_hiexp_2esats__HIEassgn_var) ;
ATSextern_val(ats_sum_type, ATS_2d0_2e2_2e10_2src_2ats_hiexp_2esats__HIEbool) ;
ATSextern_val(ats_sum_type, ATS_2d0_2e2_2e10_2src_2ats_hiexp_2esats__HIEcaseof) ;
ATSextern_val(ats_sum_type, ATS_2d0_2e2_2e10_2src_2ats_hiexp_2esats__HIEcastfn) ;
ATSextern_val(ats_sum_type, ATS_2d0_2e2_2e10_2src_2ats_hiexp_2esats__HIEchar) ;
ATSextern_val(ats_sum_type, ATS_2d0_2e2_2e10_2src_2ats_hiexp_2esats__HIEcon) ;
ATSextern_val(ats_sum_type, ATS_2d0_2e2_2e10_2src_2ats_hiexp_2esats__HIEcst) ;
ATSextern_val(ats_sum_type, ATS_2d0_2e2_2e10_2src_2ats_hiexp_2esats__HIEcstsp) ;
ATSextern_val(ats_sum_type, ATS_2d0_2e2_2e10_2src_2ats_hiexp_2esats__HIEdynload) ;
ATSextern_val(ats_sum_type, ATS_2d0_2e2_2e10_2src_2ats_hiexp_2esats__HIEempty) ;
ATSextern_val(ats_sum_type, ATS_2d0_2e2_2e10_2src_2ats_hiexp_2esats__HIEextval) ;
ATSextern_val(ats_sum_type, ATS_2d0_2e2_2e10_2src_2ats_hiexp_2esats__HIEfix) ;
ATSextern_val(ats_sum_type, ATS_2d0_2e2_2e10_2src_2ats_hiexp_2esats__HIEfloat) ;
ATSextern_val(ats_sum_type, ATS_2d0_2e2_2e10_2src_2ats_hiexp_2esats__HIEfloatsp) ;
ATSextern_val(ats_sum_type, ATS_2d0_2e2_2e10_2src_2ats_hiexp_2esats__HIEfreeat) ;
ATSextern_val(ats_sum_type, ATS_2d0_2e2_2e10_2src_2ats_hiexp_2esats__HIEif) ;
ATSextern_val(ats_sum_type, ATS_2d0_2e2_2e10_2src_2ats_hiexp_2esats__HIEint) ;
ATSextern_val(ats_sum_type, ATS_2d0_2e2_2e10_2src_2ats_hiexp_2esats__HIEintsp) ;
ATSextern_val(ats_sum_type, ATS_2d0_2e2_2e10_2src_2ats_hiexp_2esats__HIElam) ;
ATSextern_val(ats_sum_type, ATS_2d0_2e2_2e10_2src_2ats_hiexp_2esats__HIElaminit) ;
ATSextern_val(ats_sum_type, ATS_2d0_2e2_2e10_2src_2ats_hiexp_2esats__HIElazy_delay) ;
ATSextern_val(ats_sum_type, ATS_2d0_2e2_2e10_2src_2ats_hiexp_2esats__HIElazy_ldelay) ;
ATSextern_val(ats_sum_type, ATS_2d0_2e2_2e10_2src_2ats_hiexp_2esats__HIElazy_force) ;
ATSextern_val(ats_sum_type, ATS_2d0_2e2_2e10_2src_2ats_hiexp_2esats__HIElet) ;
ATSextern_val(ats_sum_type, ATS_2d0_2e2_2e10_2src_2ats_hiexp_2esats__HIEloop) ;
ATSextern_val(ats_sum_type, ATS_2d0_2e2_2e10_2src_2ats_hiexp_2esats__HIEloopexn) ;
ATSextern_val(ats_sum_type, ATS_2d0_2e2_2e10_2src_2ats_hiexp_2esats__HIElst) ;
ATSextern_val(ats_sum_type, ATS_2d0_2e2_2e10_2src_2ats_hiexp_2esats__HIEptrof_ptr) ;
ATSextern_val(ats_sum_type, ATS_2d0_2e2_2e10_2src_2ats_hiexp_2esats__HIEptrof_var) ;
ATSextern_val(ats_sum_type, ATS_2d0_2e2_2e10_2src_2ats_hiexp_2esats__HIEraise) ;
ATSextern_val(ats_sum_type, ATS_2d0_2e2_2e10_2src_2ats_hiexp_2esats__HIErec) ;
ATSextern_val(ats_sum_type, ATS_2d0_2e2_2e10_2src_2ats_hiexp_2esats__HIErefarg) ;
ATSextern_val(ats_sum_type, ATS_2d0_2e2_2e10_2src_2ats_hiexp_2esats__HIEsel) ;
ATSextern_val(ats_sum_type, ATS_2d0_2e2_2e10_2src_2ats_hiexp_2esats__HIEsel_ptr) ;
ATSextern_val(ats_sum_type, ATS_2d0_2e2_2e10_2src_2ats_hiexp_2esats__HIEsel_var) ;
ATSextern_val(ats_sum_type, ATS_2d0_2e2_2e10_2src_2ats_hiexp_2esats__HIEseq) ;
ATSextern_val(ats_sum_type, ATS_2d0_2e2_2e10_2src_2ats_hiexp_2esats__HIEsif) ;
ATSextern_val(ats_sum_type, ATS_2d0_2e2_2e10_2src_2ats_hiexp_2esats__HIEsizeof) ;
ATSextern_val(ats_sum_type, ATS_2d0_2e2_2e10_2src_2ats_hiexp_2esats__HIEstring) ;
ATSextern_val(ats_sum_type, ATS_2d0_2e2_2e10_2src_2ats_hiexp_2esats__HIEtmpcst) ;
ATSextern_val(ats_sum_type, ATS_2d0_2e2_2e10_2src_2ats_hiexp_2esats__HIEtmpvar) ;
ATSextern_val(ats_sum_type, ATS_2d0_2e2_2e10_2src_2ats_hiexp_2esats__HIEtop) ;
ATSextern_val(ats_sum_type, ATS_2d0_2e2_2e10_2src_2ats_hiexp_2esats__HIEtrywith) ;
ATSextern_val(ats_sum_type, ATS_2d0_2e2_2e10_2src_2ats_hiexp_2esats__HIEvar) ;

/* external dynamic constant declarations */
ATSextern_fun(ats_ptr_type, atspre_stdout_get) () ;
ATSextern_fun(ats_void_type, atspre_stdout_view_set) () ;
ATSextern_fun(ats_ptr_type, atspre_stderr_get) () ;
ATSextern_fun(ats_void_type, atspre_stderr_view_set) () ;
ATSextern_fun(ats_void_type, atspre_fprint_bool) (ats_ref_type, ats_bool_type) ;
ATSextern_fun(ats_void_type, atspre_fprint_char) (ats_ref_type, ats_char_type) ;
ATSextern_fun(ats_int_type, atspre_add_int_int) (ats_int_type, ats_int_type) ;
ATSextern_fun(ats_bool_type, atspre_gt_int_int) (ats_int_type, ats_int_type) ;
ATSextern_fun(ats_void_type, atspre_fprint_int) (ats_ref_type, ats_int_type) ;
ATSextern_fun(ats_void_type, atspre_fprintf_exn) (ats_ref_type, ats_ptr_type, ...) ;
ATSextern_fun(ats_void_type, atspre_fprint_string) (ats_ref_type, ats_ptr_type) ;
ATSextern_fun(ats_void_type, ATS_2d0_2e2_2e10_2src_2ats_filename_2esats__fprint_filename) (ats_ref_type, ats_ptr_type) ;
ATSextern_fun(ats_void_type, ATS_2d0_2e2_2e10_2src_2ats_intinf_2esats__fprint_intinf) (ats_ref_type, ats_ptr_type) ;
ATSextern_fun(ats_void_type, ATS_2d0_2e2_2e10_2src_2ats_label_2esats__fprint_label) (ats_ref_type, ats_ptr_type) ;
ATSextern_fun(ats_void_type, ATS_2d0_2e2_2e10_2src_2ats_list_2esats__fprintlst) (ats_ref_type, ats_ptr_type, ats_ptr_type, ats_ptr_type) ;
ATSextern_fun(ats_void_type, ATS_2d0_2e2_2e10_2src_2ats_syntax_2esats__fprint_cstsp) (ats_ref_type, ats_ptr_type) ;
ATSextern_fun(ats_void_type, ATS_2d0_2e2_2e10_2src_2ats_syntax_2esats__fprint_funclo) (ats_ref_type, ats_ptr_type) ;
ATSextern_fun(ats_void_type, ATS_2d0_2e2_2e10_2src_2ats_staexp2_2esats__fprint_s2var) (ats_ref_type, ats_ptr_type) ;
ATSextern_fun(ats_void_type, ATS_2d0_2e2_2e10_2src_2ats_staexp2_2esats__fprint_d2con) (ats_ref_type, ats_ptr_type) ;
ATSextern_fun(ats_void_type, ATS_2d0_2e2_2e10_2src_2ats_dynexp2_2esats__fprint_d2cst) (ats_ref_type, ats_ptr_type) ;
ATSextern_fun(ats_void_type, ATS_2d0_2e2_2e10_2src_2ats_dynexp2_2esats__fprint_d2var) (ats_ref_type, ats_ptr_type) ;
ATSextern_fun(ats_void_type, ATS_2d0_2e2_2e10_2src_2ats_hiexp_2esats__fprint_hityp) (ats_ref_type, ats_ptr_type) ;
ATSextern_fun(ats_void_type, ATS_2d0_2e2_2e10_2src_2ats_hiexp_2esats__fprint_hityplst) (ats_ref_type, ats_ptr_type) ;
ATSextern_fun(ats_void_type, ATS_2d0_2e2_2e10_2src_2ats_hiexp_2esats__fprint_hityplstlst) (ats_ref_type, ats_ptr_type) ;
ATSextern_fun(ats_void_type, ATS_2d0_2e2_2e10_2src_2ats_hiexp_2esats__fprint_hipat) (ats_ref_type, ats_ptr_type) ;
ATSextern_fun(ats_void_type, ATS_2d0_2e2_2e10_2src_2ats_hiexp_2esats__fprint_hipatlst) (ats_ref_type, ats_ptr_type) ;
ATSextern_fun(ats_void_type, ATS_2d0_2e2_2e10_2src_2ats_hiexp_2esats__fprint_labhipatlst) (ats_ref_type, ats_ptr_type) ;
ATSextern_fun(ats_void_type, ATS_2d0_2e2_2e10_2src_2ats_hiexp_2esats__fprint_hilab) (ats_ref_type, ats_ptr_type) ;
ATSextern_fun(ats_void_type, ATS_2d0_2e2_2e10_2src_2ats_hiexp_2esats__fprint_hilablst) (ats_ref_type, ats_ptr_type) ;
ATSextern_fun(ats_void_type, ATS_2d0_2e2_2e10_2src_2ats_hiexp_2esats__fprint_hiexp) (ats_ref_type, ats_ptr_type) ;
ATSextern_fun(ats_void_type, ATS_2d0_2e2_2e10_2src_2ats_hiexp_2esats__fprint_hiexplst) (ats_ref_type, ats_ptr_type) ;
ATSextern_fun(ats_void_type, ATS_2d0_2e2_2e10_2src_2ats_hiexp_2esats__fprint_hiexplstlst) (ats_ref_type, ats_ptr_type) ;
ATSextern_fun(ats_void_type, ATS_2d0_2e2_2e10_2src_2ats_hiexp_2esats__fprint_labhiexplst) (ats_ref_type, ats_ptr_type) ;
ATSextern_fun(ats_ptr_type, ATS_2d0_2e2_2e10_2src_2ats_hiexp_2esats__hityp_decode) (ats_ptr_type) ;
ATSextern_fun(ats_ptr_type, ATS_2d0_2e2_2e10_2src_2ats_hiexp_2esats__vartyp_get_typ) (ats_ptr_type) ;
ATSextern_fun(ats_ptr_type, ATS_2d0_2e2_2e10_2src_2ats_hiexp_2esats__vartyp_get_var) (ats_ptr_type) ;
ATSextern_fun(ats_void_type, ATS_2d0_2e2_2e10_2src_2ats_hiexp_2esats__fprint_vartyp) (ats_ref_type, ats_ptr_type) ;

/* external dynamic terminating constant declarations */
#ifdef _ATS_PROOFCHECK
extern
ats_void_type ATS_2d0_2e2_2e10_2prelude_2basics_dyn_2esats__file_mode_lte_w_w_prfck () ;
#endif /* _ATS_PROOFCHECK */

/* sum constructor declarations */
/* exn constructor declarations */
/* global dynamic (non-functional) constant declarations */
/* internal function declarations */
static
ats_void_type aux_14 (ats_ref_type arg0, ats_int_type arg1, ats_ptr_type arg2) ;
static
ats_void_type aux_23 (ats_ref_type arg0, ats_int_type arg1, ats_ptr_type arg2) ;

/* partial value template declarations */
/* static temporary variable declarations */
/* external value variable declarations */

/* function implementations */

/*
// /home/hwxi/research/Anairiats/src/ats_hiexp_print.dats: 1947(line=62, offs=14) -- 3492(line=113, offs=4)
*/
ATSglobaldec()
ats_void_type
ATS_2d0_2e2_2e10_2src_2ats_hiexp_2esats__fprint_hityp (ats_ref_type arg0, ats_ptr_type arg1) {
/* local vardec */
// ATSlocal_void (tmp0) ;
ATSlocal (ats_ptr_type, tmp1) ;
ATSlocal (ats_ptr_type, tmp2) ;
ATSlocal (ats_ptr_type, tmp3) ;
// ATSlocal_void (tmp4) ;
// ATSlocal_void (tmp5) ;
// ATSlocal_void (tmp6) ;
// ATSlocal_void (tmp7) ;
ATSlocal (ats_ptr_type, tmp8) ;
ATSlocal (ats_ptr_type, tmp9) ;
ATSlocal (ats_ptr_type, tmp10) ;
// ATSlocal_void (tmp11) ;
// ATSlocal_void (tmp12) ;
// ATSlocal_void (tmp13) ;
// ATSlocal_void (tmp14) ;
// ATSlocal_void (tmp15) ;
// ATSlocal_void (tmp16) ;
ATSlocal (ats_int_type, tmp17) ;
ATSlocal (ats_ptr_type, tmp18) ;
// ATSlocal_void (tmp19) ;
// ATSlocal_void (tmp20) ;
// ATSlocal_void (tmp21) ;
// ATSlocal_void (tmp22) ;
ATSlocal (ats_ptr_type, tmp23) ;
// ATSlocal_void (tmp24) ;
// ATSlocal_void (tmp25) ;
ATSlocal (ats_ptr_type, tmp26) ;
ATSlocal (ats_ptr_type, tmp27) ;
// ATSlocal_void (tmp28) ;
// ATSlocal_void (tmp29) ;
// ATSlocal_void (tmp30) ;
// ATSlocal_void (tmp31) ;
ATSlocal (ats_ptr_type, tmp32) ;
// ATSlocal_void (tmp33) ;
// ATSlocal_void (tmp34) ;
ATSlocal (ats_ptr_type, tmp35) ;
ATSlocal (ats_int_type, tmp36) ;
ATSlocal (ats_ptr_type, tmp37) ;
// ATSlocal_void (tmp38) ;
ATSlocal (ats_bool_type, tmp39) ;

__ats_lab_ATS_2d0_2e2_2e10_2src_2ats_hiexp_2esats__fprint_hityp:
tmp1 = ats_selbox_mac(ats_castptr_mac(anairiats_rec_0, arg1), atslab_hityp_node) ;
do {
/* branch: __ats_lab_0 */
__ats_lab_0_0:
if (((ats_sum_ptr_type)tmp1)->tag != 1) { goto __ats_lab_1_0 ; }
__ats_lab_0_1:
tmp2 = ats_caselptrlab_mac(anairiats_sum_1, tmp1, atslab_0) ;
tmp3 = ats_caselptrlab_mac(anairiats_sum_1, tmp1, atslab_1) ;
/* tmp4 = */ atspre_fprint_string (arg0, ATSstrcst("HITextype(")) ;
/* tmp5 = */ atspre_fprint_string (arg0, tmp2) ;
/* tmp6 = */ atspre_fprint_string (arg0, ATSstrcst("; ")) ;
/* tmp7 = */ ATS_2d0_2e2_2e10_2src_2ats_hiexp_2esats__fprint_hityplstlst (arg0, tmp3) ;
/* tmp0 = */ atspre_fprint_string (arg0, ATSstrcst(")")) ;
break ;

/* branch: __ats_lab_1 */
__ats_lab_1_0:
if (((ats_sum_ptr_type)tmp1)->tag != 2) { goto __ats_lab_2_0 ; }
__ats_lab_1_1:
tmp8 = ats_caselptrlab_mac(anairiats_sum_2, tmp1, atslab_0) ;
tmp9 = ats_caselptrlab_mac(anairiats_sum_2, tmp1, atslab_1) ;
tmp10 = ats_caselptrlab_mac(anairiats_sum_2, tmp1, atslab_2) ;
/* tmp11 = */ atspre_fprint_string (arg0, ATSstrcst("HITfun(")) ;
/* tmp12 = */ ATS_2d0_2e2_2e10_2src_2ats_syntax_2esats__fprint_funclo (arg0, tmp8) ;
/* tmp13 = */ atspre_fprint_string (arg0, ATSstrcst("; ")) ;
/* tmp14 = */ ATS_2d0_2e2_2e10_2src_2ats_hiexp_2esats__fprint_hityplst (arg0, tmp9) ;
/* tmp15 = */ atspre_fprint_string (arg0, ATSstrcst("; ")) ;
/* tmp16 = */ ATS_2d0_2e2_2e10_2src_2ats_hiexp_2esats__fprint_hityp (arg0, tmp10) ;
/* tmp0 = */ atspre_fprint_string (arg0, ATSstrcst(")")) ;
break ;

/* branch: __ats_lab_2 */
__ats_lab_2_0:
if (((ats_sum_ptr_type)tmp1)->tag != 3) { goto __ats_lab_3_0 ; }
__ats_lab_2_1:
tmp17 = ats_caselptrlab_mac(anairiats_sum_3, tmp1, atslab_0) ;
tmp18 = ats_caselptrlab_mac(anairiats_sum_3, tmp1, atslab_1) ;
/* tmp19 = */ atspre_fprint_string (arg0, ATSstrcst("HITrefarg(")) ;
/* tmp20 = */ atspre_fprint_int (arg0, tmp17) ;
/* tmp21 = */ atspre_fprint_string (arg0, ATSstrcst("; ")) ;
/* tmp22 = */ ATS_2d0_2e2_2e10_2src_2ats_hiexp_2esats__fprint_hityp (arg0, tmp18) ;
/* tmp0 = */ atspre_fprint_string (arg0, ATSstrcst(")")) ;
break ;

/* branch: __ats_lab_3 */
__ats_lab_3_0:
if (((ats_sum_ptr_type)tmp1)->tag != 8) { goto __ats_lab_4_0 ; }
__ats_lab_3_1:
tmp23 = ats_caselptrlab_mac(anairiats_sum_4, tmp1, atslab_0) ;
/* tmp24 = */ atspre_fprint_string (arg0, ATSstrcst("HITtyrecsin(")) ;
/* tmp25 = */ ATS_2d0_2e2_2e10_2src_2ats_hiexp_2esats__fprint_hityp (arg0, tmp23) ;
/* tmp0 = */ atspre_fprint_string (arg0, ATSstrcst(")")) ;
break ;

/* branch: __ats_lab_4 */
__ats_lab_4_0:
if (((ats_sum_ptr_type)tmp1)->tag != 7) { goto __ats_lab_5_0 ; }
__ats_lab_4_1:
/* tmp0 = */ atspre_fprint_string (arg0, ATSstrcst("HITtyrectemp(...)")) ;
break ;

/* branch: __ats_lab_5 */
__ats_lab_5_0:
if (((ats_sum_ptr_type)tmp1)->tag != 10) { goto __ats_lab_6_0 ; }
__ats_lab_5_1:
tmp26 = ats_caselptrlab_mac(anairiats_sum_1, tmp1, atslab_0) ;
tmp27 = ats_caselptrlab_mac(anairiats_sum_1, tmp1, atslab_1) ;
/* tmp28 = */ atspre_fprint_string (arg0, ATSstrcst("HITsumtemp(")) ;
/* tmp29 = */ ATS_2d0_2e2_2e10_2src_2ats_staexp2_2esats__fprint_d2con (arg0, tmp26) ;
/* tmp30 = */ atspre_fprint_string (arg0, ATSstrcst("; ")) ;
/* tmp31 = */ ATS_2d0_2e2_2e10_2src_2ats_hiexp_2esats__fprint_hityplst (arg0, tmp27) ;
/* tmp0 = */ atspre_fprint_string (arg0, ATSstrcst(")")) ;
break ;

/* branch: __ats_lab_6 */
__ats_lab_6_0:
if (((ats_sum_ptr_type)tmp1)->tag != 4) { goto __ats_lab_7_0 ; }
__ats_lab_6_1:
tmp32 = ats_caselptrlab_mac(anairiats_sum_4, tmp1, atslab_0) ;
/* tmp33 = */ atspre_fprint_string (arg0, ATSstrcst("HITs2var(")) ;
/* tmp34 = */ ATS_2d0_2e2_2e10_2src_2ats_staexp2_2esats__fprint_s2var (arg0, tmp32) ;
/* tmp0 = */ atspre_fprint_string (arg0, ATSstrcst(")")) ;
break ;

/* branch: __ats_lab_7 */
__ats_lab_7_0:
__ats_lab_7_1:
tmp35 = ats_selbox_mac(ats_castptr_mac(anairiats_rec_0, arg1), atslab_hityp_name) ;

tmp36 = ats_caselptrlab_mac(anairiats_sum_5, tmp35, atslab_0) ;
tmp37 = ats_caselptrlab_mac(anairiats_sum_5, tmp35, atslab_1) ;
tmp39 = atspre_gt_int_int (tmp36, 0) ;
if (tmp39) {
/* tmp38 = */ atspre_fprint_string (arg0, ATSstrcst("*")) ;
} else {
/* empty */
} /* end of [if] */
/* tmp0 = */ atspre_fprint_string (arg0, tmp37) ;
break ;
} while (0) ;
return /* (tmp0) */ ;
} /* end of [ATS_2d0_2e2_2e10_2src_2ats_hiexp_2esats__fprint_hityp] */

/*
// /home/hwxi/research/Anairiats/src/ats_hiexp_print.dats: 3541(line=116, offs=13) -- 3578(line=116, offs=50)
*/
ATSglobaldec()
ats_void_type
ATS_2d0_2e2_2e10_2src_2ats_hiexp_2esats__print_hityp (ats_ptr_type arg0) {
/* local vardec */
// ATSlocal_void (tmp40) ;
ATSlocal (ats_ptr_type, tmp41) ;
ATSlocal (ats_ptr_type, tmp42) ;
// ATSlocal_void (tmp43) ;

__ats_lab_ATS_2d0_2e2_2e10_2src_2ats_hiexp_2esats__print_hityp:
tmp41 = atspre_stdout_get () ;
tmp42 = ats_selsin_mac(tmp41, atslab_1) ;
/* tmp43 = */ ATS_2d0_2e2_2e10_2src_2ats_hiexp_2esats__fprint_hityp (tmp42, arg0) ;
/* tmp40 = */ atspre_stdout_view_set () ;
return /* (tmp40) */ ;
} /* end of [ATS_2d0_2e2_2e10_2src_2ats_hiexp_2esats__print_hityp] */

/*
// /home/hwxi/research/Anairiats/src/ats_hiexp_print.dats: 3601(line=118, offs=13) -- 3638(line=118, offs=50)
*/
ATSglobaldec()
ats_void_type
ATS_2d0_2e2_2e10_2src_2ats_hiexp_2esats__prerr_hityp (ats_ptr_type arg0) {
/* local vardec */
// ATSlocal_void (tmp44) ;
ATSlocal (ats_ptr_type, tmp45) ;
ATSlocal (ats_ptr_type, tmp46) ;
// ATSlocal_void (tmp47) ;

__ats_lab_ATS_2d0_2e2_2e10_2src_2ats_hiexp_2esats__prerr_hityp:
tmp45 = atspre_stderr_get () ;
tmp46 = ats_selsin_mac(tmp45, atslab_1) ;
/* tmp47 = */ ATS_2d0_2e2_2e10_2src_2ats_hiexp_2esats__fprint_hityp (tmp46, arg0) ;
/* tmp44 = */ atspre_stderr_view_set () ;
return /* (tmp44) */ ;
} /* end of [ATS_2d0_2e2_2e10_2src_2ats_hiexp_2esats__prerr_hityp] */

/*
// /home/hwxi/research/Anairiats/src/ats_hiexp_print.dats: 3687(line=123, offs=17) -- 3763(line=124, offs=60)
*/
ATSglobaldec()
ats_void_type
ATS_2d0_2e2_2e10_2src_2ats_hiexp_2esats__fprint_hityplst (ats_ref_type arg0, ats_ptr_type arg1) {
/* local vardec */
// ATSlocal_void (tmp48) ;

__ats_lab_ATS_2d0_2e2_2e10_2src_2ats_hiexp_2esats__fprint_hityplst:
/* tmp48 = */ ATS_2d0_2e2_2e10_2src_2ats_list_2esats__fprintlst (arg0, arg1, ATSstrcst(", "), &ATS_2d0_2e2_2e10_2src_2ats_hiexp_2esats__fprint_hityp) ;
return /* (tmp48) */ ;
} /* end of [ATS_2d0_2e2_2e10_2src_2ats_hiexp_2esats__fprint_hityplst] */

/*
// /home/hwxi/research/Anairiats/src/ats_hiexp_print.dats: 3818(line=128, offs=16) -- 3860(line=128, offs=58)
*/
ATSglobaldec()
ats_void_type
ATS_2d0_2e2_2e10_2src_2ats_hiexp_2esats__print_hityplst (ats_ptr_type arg0) {
/* local vardec */
// ATSlocal_void (tmp49) ;
ATSlocal (ats_ptr_type, tmp50) ;
ATSlocal (ats_ptr_type, tmp51) ;
// ATSlocal_void (tmp52) ;

__ats_lab_ATS_2d0_2e2_2e10_2src_2ats_hiexp_2esats__print_hityplst:
tmp50 = atspre_stdout_get () ;
tmp51 = ats_selsin_mac(tmp50, atslab_1) ;
/* tmp52 = */ ATS_2d0_2e2_2e10_2src_2ats_hiexp_2esats__fprint_hityplst (tmp51, arg0) ;
/* tmp49 = */ atspre_stdout_view_set () ;
return /* (tmp49) */ ;
} /* end of [ATS_2d0_2e2_2e10_2src_2ats_hiexp_2esats__print_hityplst] */

/*
// /home/hwxi/research/Anairiats/src/ats_hiexp_print.dats: 3886(line=130, offs=16) -- 3928(line=130, offs=58)
*/
ATSglobaldec()
ats_void_type
ATS_2d0_2e2_2e10_2src_2ats_hiexp_2esats__prerr_hityplst (ats_ptr_type arg0) {
/* local vardec */
// ATSlocal_void (tmp53) ;
ATSlocal (ats_ptr_type, tmp54) ;
ATSlocal (ats_ptr_type, tmp55) ;
// ATSlocal_void (tmp56) ;

__ats_lab_ATS_2d0_2e2_2e10_2src_2ats_hiexp_2esats__prerr_hityplst:
tmp54 = atspre_stderr_get () ;
tmp55 = ats_selsin_mac(tmp54, atslab_1) ;
/* tmp56 = */ ATS_2d0_2e2_2e10_2src_2ats_hiexp_2esats__fprint_hityplst (tmp55, arg0) ;
/* tmp53 = */ atspre_stderr_view_set () ;
return /* (tmp53) */ ;
} /* end of [ATS_2d0_2e2_2e10_2src_2ats_hiexp_2esats__prerr_hityplst] */

/*
// /home/hwxi/research/Anairiats/src/ats_hiexp_print.dats: 3980(line=135, offs=20) -- 4064(line=136, offs=67)
*/
ATSglobaldec()
ats_void_type
ATS_2d0_2e2_2e10_2src_2ats_hiexp_2esats__fprint_hityplstlst (ats_ref_type arg0, ats_ptr_type arg1) {
/* local vardec */
// ATSlocal_void (tmp57) ;

__ats_lab_ATS_2d0_2e2_2e10_2src_2ats_hiexp_2esats__fprint_hityplstlst:
/* tmp57 = */ ATS_2d0_2e2_2e10_2src_2ats_list_2esats__fprintlst (arg0, arg1, ATSstrcst("; "), &ATS_2d0_2e2_2e10_2src_2ats_hiexp_2esats__fprint_hityplst) ;
return /* (tmp57) */ ;
} /* end of [ATS_2d0_2e2_2e10_2src_2ats_hiexp_2esats__fprint_hityplstlst] */

/*
// /home/hwxi/research/Anairiats/src/ats_hiexp_print.dats: 4141(line=142, offs=14) -- 6620(line=222, offs=4)
*/
ATSglobaldec()
ats_void_type
ATS_2d0_2e2_2e10_2src_2ats_hiexp_2esats__fprint_hipat (ats_ref_type arg0, ats_ptr_type arg1) {
/* local vardec */
// ATSlocal_void (tmp58) ;
ATSlocal (ats_ptr_type, tmp59) ;
ATSlocal (ats_ptr_type, tmp60) ;
ATSlocal (ats_ptr_type, tmp61) ;
// ATSlocal_void (tmp62) ;
// ATSlocal_void (tmp63) ;
// ATSlocal_void (tmp64) ;
// ATSlocal_void (tmp65) ;
ATSlocal (ats_int_type, tmp66) ;
ATSlocal (ats_ptr_type, tmp67) ;
ATSlocal (ats_ptr_type, tmp68) ;
// ATSlocal_void (tmp69) ;
// ATSlocal_void (tmp70) ;
// ATSlocal_void (tmp71) ;
// ATSlocal_void (tmp72) ;
// ATSlocal_void (tmp73) ;
// ATSlocal_void (tmp74) ;
ATSlocal (ats_bool_type, tmp75) ;
// ATSlocal_void (tmp76) ;
// ATSlocal_void (tmp77) ;
ATSlocal (ats_char_type, tmp78) ;
// ATSlocal_void (tmp79) ;
// ATSlocal_void (tmp80) ;
ATSlocal (ats_int_type, tmp81) ;
ATSlocal (ats_ptr_type, tmp82) ;
ATSlocal (ats_ptr_type, tmp83) ;
ATSlocal (ats_ptr_type, tmp84) ;
// ATSlocal_void (tmp85) ;
// ATSlocal_void (tmp86) ;
// ATSlocal_void (tmp87) ;
// ATSlocal_void (tmp88) ;
// ATSlocal_void (tmp89) ;
// ATSlocal_void (tmp90) ;
// ATSlocal_void (tmp91) ;
// ATSlocal_void (tmp92) ;
ATSlocal (ats_int_type, tmp93) ;
ATSlocal (ats_ptr_type, tmp94) ;
// ATSlocal_void (tmp95) ;
// ATSlocal_void (tmp96) ;
// ATSlocal_void (tmp97) ;
// ATSlocal_void (tmp98) ;
ATSlocal (ats_ptr_type, tmp99) ;
ATSlocal (ats_ptr_type, tmp100) ;
// ATSlocal_void (tmp101) ;
// ATSlocal_void (tmp102) ;
ATSlocal (ats_ptr_type, tmp103) ;
ATSlocal (ats_ptr_type, tmp104) ;
// ATSlocal_void (tmp105) ;
// ATSlocal_void (tmp106) ;
// ATSlocal_void (tmp107) ;
// ATSlocal_void (tmp108) ;
ATSlocal (ats_int_type, tmp109) ;
ATSlocal (ats_ptr_type, tmp110) ;
ATSlocal (ats_ptr_type, tmp111) ;
// ATSlocal_void (tmp112) ;
// ATSlocal_void (tmp113) ;
// ATSlocal_void (tmp114) ;
// ATSlocal_void (tmp115) ;
// ATSlocal_void (tmp116) ;
// ATSlocal_void (tmp117) ;
ATSlocal (ats_ptr_type, tmp118) ;
// ATSlocal_void (tmp119) ;
// ATSlocal_void (tmp120) ;
ATSlocal (ats_ptr_type, tmp121) ;
// ATSlocal_void (tmp122) ;
// ATSlocal_void (tmp123) ;

__ats_lab_ATS_2d0_2e2_2e10_2src_2ats_hiexp_2esats__fprint_hipat:
tmp59 = ats_selbox_mac(ats_castptr_mac(anairiats_rec_6, arg1), atslab_hipat_node) ;
do {
/* branch: __ats_lab_8 */
__ats_lab_8_0:
if (((ats_sum_ptr_type)tmp59)->tag != 0) { goto __ats_lab_9_0 ; }
__ats_lab_8_1:
tmp60 = ats_caselptrlab_mac(anairiats_sum_1, tmp59, atslab_0) ;
tmp61 = ats_caselptrlab_mac(anairiats_sum_1, tmp59, atslab_1) ;
/* tmp62 = */ atspre_fprint_string (arg0, ATSstrcst("HIPann(")) ;
/* tmp63 = */ ATS_2d0_2e2_2e10_2src_2ats_hiexp_2esats__fprint_hipat (arg0, tmp60) ;
/* tmp64 = */ atspre_fprint_string (arg0, ATSstrcst("; ")) ;
/* tmp65 = */ ATS_2d0_2e2_2e10_2src_2ats_hiexp_2esats__fprint_hityp (arg0, tmp61) ;
/* tmp58 = */ atspre_fprint_string (arg0, ATSstrcst(")")) ;
break ;

/* branch: __ats_lab_9 */
__ats_lab_9_0:
if (((ats_sum_ptr_type)tmp59)->tag != 1) { goto __ats_lab_10_0 ; }
__ats_lab_9_1:
/* tmp58 = */ atspre_fprint_string (arg0, ATSstrcst("HIPany()")) ;
break ;

/* branch: __ats_lab_10 */
__ats_lab_10_0:
if (((ats_sum_ptr_type)tmp59)->tag != 2) { goto __ats_lab_11_0 ; }
__ats_lab_10_1:
tmp66 = ats_caselptrlab_mac(anairiats_sum_7, tmp59, atslab_0) ;
tmp67 = ats_caselptrlab_mac(anairiats_sum_7, tmp59, atslab_1) ;
tmp68 = ats_caselptrlab_mac(anairiats_sum_7, tmp59, atslab_2) ;
/* tmp69 = */ atspre_fprint_string (arg0, ATSstrcst("HIPas(")) ;
/* tmp70 = */ atspre_fprint_int (arg0, tmp66) ;
/* tmp71 = */ atspre_fprint_string (arg0, ATSstrcst("; ")) ;
/* tmp72 = */ ATS_2d0_2e2_2e10_2src_2ats_dynexp2_2esats__fprint_d2var (arg0, tmp67) ;
/* tmp73 = */ atspre_fprint_string (arg0, ATSstrcst("; ")) ;
/* tmp74 = */ ATS_2d0_2e2_2e10_2src_2ats_hiexp_2esats__fprint_hipat (arg0, tmp68) ;
/* tmp58 = */ atspre_fprint_string (arg0, ATSstrcst(")")) ;
break ;

/* branch: __ats_lab_11 */
__ats_lab_11_0:
if (((ats_sum_ptr_type)tmp59)->tag != 3) { goto __ats_lab_12_0 ; }
__ats_lab_11_1:
tmp75 = ats_caselptrlab_mac(anairiats_sum_8, tmp59, atslab_0) ;
/* tmp76 = */ atspre_fprint_string (arg0, ATSstrcst("HIPbool(")) ;
/* tmp77 = */ atspre_fprint_bool (arg0, tmp75) ;
/* tmp58 = */ atspre_fprint_string (arg0, ATSstrcst(")")) ;
break ;

/* branch: __ats_lab_12 */
__ats_lab_12_0:
if (((ats_sum_ptr_type)tmp59)->tag != 4) { goto __ats_lab_13_0 ; }
__ats_lab_12_1:
tmp78 = ats_caselptrlab_mac(anairiats_sum_9, tmp59, atslab_0) ;
/* tmp79 = */ atspre_fprint_string (arg0, ATSstrcst("HIPchar(")) ;
/* tmp80 = */ atspre_fprint_char (arg0, tmp78) ;
/* tmp58 = */ atspre_fprint_string (arg0, ATSstrcst(")")) ;
break ;

/* branch: __ats_lab_13 */
__ats_lab_13_0:
if (((ats_sum_ptr_type)tmp59)->tag != 5) { goto __ats_lab_14_0 ; }
__ats_lab_13_1:
tmp81 = ats_caselptrlab_mac(anairiats_sum_10, tmp59, atslab_0) ;
tmp82 = ats_caselptrlab_mac(anairiats_sum_10, tmp59, atslab_1) ;
tmp83 = ats_caselptrlab_mac(anairiats_sum_10, tmp59, atslab_2) ;
tmp84 = ats_caselptrlab_mac(anairiats_sum_10, tmp59, atslab_3) ;
/* tmp85 = */ atspre_fprint_string (arg0, ATSstrcst("HIPcon(")) ;
/* tmp86 = */ atspre_fprint_int (arg0, tmp81) ;
/* tmp87 = */ atspre_fprint_string (arg0, ATSstrcst("; ")) ;
/* tmp88 = */ ATS_2d0_2e2_2e10_2src_2ats_staexp2_2esats__fprint_d2con (arg0, tmp82) ;
/* tmp89 = */ atspre_fprint_string (arg0, ATSstrcst("; ")) ;
/* tmp90 = */ ATS_2d0_2e2_2e10_2src_2ats_hiexp_2esats__fprint_hipatlst (arg0, tmp83) ;
/* tmp91 = */ atspre_fprint_string (arg0, ATSstrcst("; ")) ;
/* tmp92 = */ ATS_2d0_2e2_2e10_2src_2ats_hiexp_2esats__fprint_hityp (arg0, tmp84) ;
/* tmp58 = */ atspre_fprint_string (arg0, ATSstrcst(")")) ;
break ;

/* branch: __ats_lab_14 */
__ats_lab_14_0:
if (((ats_sum_ptr_type)tmp59)->tag != 6) { goto __ats_lab_15_0 ; }
__ats_lab_14_1:
tmp93 = ats_caselptrlab_mac(anairiats_sum_3, tmp59, atslab_0) ;
tmp94 = ats_caselptrlab_mac(anairiats_sum_3, tmp59, atslab_1) ;
/* tmp95 = */ atspre_fprint_string (arg0, ATSstrcst("HIPcon_any(")) ;
/* tmp96 = */ atspre_fprint_int (arg0, tmp93) ;
/* tmp97 = */ atspre_fprint_string (arg0, ATSstrcst("; ")) ;
/* tmp98 = */ ATS_2d0_2e2_2e10_2src_2ats_staexp2_2esats__fprint_d2con (arg0, tmp94) ;
/* tmp58 = */ atspre_fprint_string (arg0, ATSstrcst(")")) ;
break ;

/* branch: __ats_lab_15 */
__ats_lab_15_0:
if (((ats_sum_ptr_type)tmp59)->tag != 7) { goto __ats_lab_16_0 ; }
__ats_lab_15_1:
/* tmp58 = */ atspre_fprint_string (arg0, ATSstrcst("HIPempty()")) ;
break ;

/* branch: __ats_lab_16 */
__ats_lab_16_0:
if (((ats_sum_ptr_type)tmp59)->tag != 8) { goto __ats_lab_17_0 ; }
__ats_lab_16_1:
tmp99 = ats_caselptrlab_mac(anairiats_sum_4, tmp59, atslab_0) ;
/* tmp58 = */ atspre_fprintf_exn (arg0, ATSstrcst("HIPfloat(%s)"), tmp99) ;
break ;

/* branch: __ats_lab_17 */
__ats_lab_17_0:
if (((ats_sum_ptr_type)tmp59)->tag != 9) { goto __ats_lab_18_0 ; }
__ats_lab_17_1:
tmp100 = ats_caselptrlab_mac(anairiats_sum_1, tmp59, atslab_1) ;
/* tmp101 = */ atspre_fprint_string (arg0, ATSstrcst("HIPint(")) ;
/* tmp102 = */ ATS_2d0_2e2_2e10_2src_2ats_intinf_2esats__fprint_intinf (arg0, tmp100) ;
/* tmp58 = */ atspre_fprint_string (arg0, ATSstrcst(")")) ;
break ;

/* branch: __ats_lab_18 */
__ats_lab_18_0:
if (((ats_sum_ptr_type)tmp59)->tag != 10) { goto __ats_lab_19_0 ; }
__ats_lab_18_1:
tmp103 = ats_caselptrlab_mac(anairiats_sum_1, tmp59, atslab_0) ;
tmp104 = ats_caselptrlab_mac(anairiats_sum_1, tmp59, atslab_1) ;
/* tmp105 = */ atspre_fprint_string (arg0, ATSstrcst("HIPlst(")) ;
/* tmp106 = */ ATS_2d0_2e2_2e10_2src_2ats_hiexp_2esats__fprint_hityp (arg0, tmp103) ;
/* tmp107 = */ atspre_fprint_string (arg0, ATSstrcst("; ")) ;
/* tmp108 = */ ATS_2d0_2e2_2e10_2src_2ats_hiexp_2esats__fprint_hipatlst (arg0, tmp104) ;
/* tmp58 = */ atspre_fprint_string (arg0, ATSstrcst(")")) ;
break ;

/* branch: __ats_lab_19 */
__ats_lab_19_0:
if (((ats_sum_ptr_type)tmp59)->tag != 11) { goto __ats_lab_20_0 ; }
__ats_lab_19_1:
tmp109 = ats_caselptrlab_mac(anairiats_sum_7, tmp59, atslab_0) ;
tmp110 = ats_caselptrlab_mac(anairiats_sum_7, tmp59, atslab_1) ;
tmp111 = ats_caselptrlab_mac(anairiats_sum_7, tmp59, atslab_2) ;
/* tmp112 = */ atspre_fprint_string (arg0, ATSstrcst("HIPrec(")) ;
/* tmp113 = */ atspre_fprint_int (arg0, tmp109) ;
/* tmp114 = */ atspre_fprint_string (arg0, ATSstrcst("; ")) ;
/* tmp115 = */ ATS_2d0_2e2_2e10_2src_2ats_hiexp_2esats__fprint_labhipatlst (arg0, tmp110) ;
/* tmp116 = */ atspre_fprint_string (arg0, ATSstrcst("; ")) ;
/* tmp117 = */ ATS_2d0_2e2_2e10_2src_2ats_hiexp_2esats__fprint_hityp (arg0, tmp111) ;
/* tmp58 = */ atspre_fprint_string (arg0, ATSstrcst(")")) ;
break ;

/* branch: __ats_lab_20 */
__ats_lab_20_0:
if (((ats_sum_ptr_type)tmp59)->tag != 12) { goto __ats_lab_21_0 ; }
__ats_lab_20_1:
tmp118 = ats_caselptrlab_mac(anairiats_sum_4, tmp59, atslab_0) ;
/* tmp119 = */ atspre_fprint_string (arg0, ATSstrcst("HIPstring(")) ;
/* tmp120 = */ atspre_fprint_string (arg0, tmp118) ;
/* tmp58 = */ atspre_fprint_string (arg0, ATSstrcst(")")) ;
break ;

/* branch: __ats_lab_21 */
__ats_lab_21_0:
// if (((ats_sum_ptr_type)tmp59)->tag != 13) { ats_deadcode_failure_handle () ; }
__ats_lab_21_1:
tmp121 = ats_caselptrlab_mac(anairiats_sum_3, tmp59, atslab_1) ;
/* tmp122 = */ atspre_fprint_string (arg0, ATSstrcst("HIPvar(")) ;
/* tmp123 = */ ATS_2d0_2e2_2e10_2src_2ats_dynexp2_2esats__fprint_d2var (arg0, tmp121) ;
/* tmp58 = */ atspre_fprint_string (arg0, ATSstrcst(")")) ;
break ;
} while (0) ;
return /* (tmp58) */ ;
} /* end of [ATS_2d0_2e2_2e10_2src_2ats_hiexp_2esats__fprint_hipat] */

/*
// /home/hwxi/research/Anairiats/src/ats_hiexp_print.dats: 6669(line=225, offs=13) -- 6706(line=225, offs=50)
*/
ATSglobaldec()
ats_void_type
ATS_2d0_2e2_2e10_2src_2ats_hiexp_2esats__print_hipat (ats_ptr_type arg0) {
/* local vardec */
// ATSlocal_void (tmp124) ;
ATSlocal (ats_ptr_type, tmp125) ;
ATSlocal (ats_ptr_type, tmp126) ;
// ATSlocal_void (tmp127) ;

__ats_lab_ATS_2d0_2e2_2e10_2src_2ats_hiexp_2esats__print_hipat:
tmp125 = atspre_stdout_get () ;
tmp126 = ats_selsin_mac(tmp125, atslab_1) ;
/* tmp127 = */ ATS_2d0_2e2_2e10_2src_2ats_hiexp_2esats__fprint_hipat (tmp126, arg0) ;
/* tmp124 = */ atspre_stdout_view_set () ;
return /* (tmp124) */ ;
} /* end of [ATS_2d0_2e2_2e10_2src_2ats_hiexp_2esats__print_hipat] */

/*
// /home/hwxi/research/Anairiats/src/ats_hiexp_print.dats: 6729(line=227, offs=13) -- 6766(line=227, offs=50)
*/
ATSglobaldec()
ats_void_type
ATS_2d0_2e2_2e10_2src_2ats_hiexp_2esats__prerr_hipat (ats_ptr_type arg0) {
/* local vardec */
// ATSlocal_void (tmp128) ;
ATSlocal (ats_ptr_type, tmp129) ;
ATSlocal (ats_ptr_type, tmp130) ;
// ATSlocal_void (tmp131) ;

__ats_lab_ATS_2d0_2e2_2e10_2src_2ats_hiexp_2esats__prerr_hipat:
tmp129 = atspre_stderr_get () ;
tmp130 = ats_selsin_mac(tmp129, atslab_1) ;
/* tmp131 = */ ATS_2d0_2e2_2e10_2src_2ats_hiexp_2esats__fprint_hipat (tmp130, arg0) ;
/* tmp128 = */ atspre_stderr_view_set () ;
return /* (tmp128) */ ;
} /* end of [ATS_2d0_2e2_2e10_2src_2ats_hiexp_2esats__prerr_hipat] */

/*
// /home/hwxi/research/Anairiats/src/ats_hiexp_print.dats: 6815(line=232, offs=17) -- 6891(line=233, offs=60)
*/
ATSglobaldec()
ats_void_type
ATS_2d0_2e2_2e10_2src_2ats_hiexp_2esats__fprint_hipatlst (ats_ref_type arg0, ats_ptr_type arg1) {
/* local vardec */
// ATSlocal_void (tmp132) ;

__ats_lab_ATS_2d0_2e2_2e10_2src_2ats_hiexp_2esats__fprint_hipatlst:
/* tmp132 = */ ATS_2d0_2e2_2e10_2src_2ats_list_2esats__fprintlst (arg0, arg1, ATSstrcst(", "), &ATS_2d0_2e2_2e10_2src_2ats_hiexp_2esats__fprint_hipat) ;
return /* (tmp132) */ ;
} /* end of [ATS_2d0_2e2_2e10_2src_2ats_hiexp_2esats__fprint_hipatlst] */

/*
// /home/hwxi/research/Anairiats/src/ats_hiexp_print.dats: 6946(line=237, offs=16) -- 6988(line=237, offs=58)
*/
ATSglobaldec()
ats_void_type
ATS_2d0_2e2_2e10_2src_2ats_hiexp_2esats__print_hipatlst (ats_ptr_type arg0) {
/* local vardec */
// ATSlocal_void (tmp133) ;
ATSlocal (ats_ptr_type, tmp134) ;
ATSlocal (ats_ptr_type, tmp135) ;
// ATSlocal_void (tmp136) ;

__ats_lab_ATS_2d0_2e2_2e10_2src_2ats_hiexp_2esats__print_hipatlst:
tmp134 = atspre_stdout_get () ;
tmp135 = ats_selsin_mac(tmp134, atslab_1) ;
/* tmp136 = */ ATS_2d0_2e2_2e10_2src_2ats_hiexp_2esats__fprint_hipatlst (tmp135, arg0) ;
/* tmp133 = */ atspre_stdout_view_set () ;
return /* (tmp133) */ ;
} /* end of [ATS_2d0_2e2_2e10_2src_2ats_hiexp_2esats__print_hipatlst] */

/*
// /home/hwxi/research/Anairiats/src/ats_hiexp_print.dats: 7014(line=239, offs=16) -- 7056(line=239, offs=58)
*/
ATSglobaldec()
ats_void_type
ATS_2d0_2e2_2e10_2src_2ats_hiexp_2esats__prerr_hipatlst (ats_ptr_type arg0) {
/* local vardec */
// ATSlocal_void (tmp137) ;
ATSlocal (ats_ptr_type, tmp138) ;
ATSlocal (ats_ptr_type, tmp139) ;
// ATSlocal_void (tmp140) ;

__ats_lab_ATS_2d0_2e2_2e10_2src_2ats_hiexp_2esats__prerr_hipatlst:
tmp138 = atspre_stderr_get () ;
tmp139 = ats_selsin_mac(tmp138, atslab_1) ;
/* tmp140 = */ ATS_2d0_2e2_2e10_2src_2ats_hiexp_2esats__fprint_hipatlst (tmp139, arg0) ;
/* tmp137 = */ atspre_stderr_view_set () ;
return /* (tmp137) */ ;
} /* end of [ATS_2d0_2e2_2e10_2src_2ats_hiexp_2esats__prerr_hipatlst] */

/*
// /home/hwxi/research/Anairiats/src/ats_hiexp_print.dats: 7145(line=246, offs=7) -- 7703(line=260, offs=30)
*/
ATSstaticdec()
ats_void_type
aux_14 (ats_ref_type arg0, ats_int_type arg1, ats_ptr_type arg2) {
/* local vardec */
// ATSlocal_void (tmp142) ;
ATSlocal (ats_ptr_type, tmp143) ;
ATSlocal (ats_ptr_type, tmp144) ;
ATSlocal (ats_ptr_type, tmp145) ;
// ATSlocal_void (tmp146) ;
ATSlocal (ats_bool_type, tmp147) ;
// ATSlocal_void (tmp148) ;
// ATSlocal_void (tmp149) ;
// ATSlocal_void (tmp150) ;
ATSlocal (ats_int_type, tmp151) ;
// ATSlocal_void (tmp152) ;
ATSlocal (ats_bool_type, tmp153) ;

__ats_lab_aux_14:
do {
/* branch: __ats_lab_22 */
__ats_lab_22_0:
if (((ats_sum_ptr_type)arg2)->tag != 0) { goto __ats_lab_23_0 ; }
__ats_lab_22_1:
tmp143 = ats_caselptrlab_mac(anairiats_sum_2, arg2, atslab_0) ;
tmp144 = ats_caselptrlab_mac(anairiats_sum_2, arg2, atslab_1) ;
tmp145 = ats_caselptrlab_mac(anairiats_sum_2, arg2, atslab_2) ;
tmp147 = atspre_gt_int_int (arg1, 0) ;
if (tmp147) {
/* tmp146 = */ atspre_fprint_string (arg0, ATSstrcst(", ")) ;
} else {
/* empty */
} /* end of [if] */
/* tmp148 = */ ATS_2d0_2e2_2e10_2src_2ats_label_2esats__fprint_label (arg0, tmp143) ;
/* tmp149 = */ atspre_fprint_string (arg0, ATSstrcst("= ")) ;
/* tmp150 = */ ATS_2d0_2e2_2e10_2src_2ats_hiexp_2esats__fprint_hipat (arg0, tmp144) ;
tmp151 = atspre_add_int_int (arg1, 1) ;
arg0 = arg0 ;
arg1 = tmp151 ;
arg2 = tmp145 ;
goto __ats_lab_aux_14 ; // tail call
break ;

/* branch: __ats_lab_23 */
__ats_lab_23_0:
if (((ats_sum_ptr_type)arg2)->tag != 1) { goto __ats_lab_24_0 ; }
__ats_lab_23_1:
tmp153 = atspre_gt_int_int (arg1, 0) ;
if (tmp153) {
/* tmp152 = */ atspre_fprint_string (arg0, ATSstrcst(", ")) ;
} else {
/* empty */
} /* end of [if] */
/* tmp142 = */ atspre_fprint_string (arg0, ATSstrcst("...")) ;
break ;

/* branch: __ats_lab_24 */
__ats_lab_24_0:
// if (((ats_sum_ptr_type)arg2)->tag != 2) { ats_deadcode_failure_handle () ; }
__ats_lab_24_1:
break ;
} while (0) ;
return /* (tmp142) */ ;
} /* end of [aux_14] */

/*
// /home/hwxi/research/Anairiats/src/ats_hiexp_print.dats: 7114(line=245, offs=3) -- 7778(line=264, offs=4)
*/
ATSglobaldec()
ats_void_type
ATS_2d0_2e2_2e10_2src_2ats_hiexp_2esats__fprint_labhipatlst (ats_ref_type arg0, ats_ptr_type arg1) {
/* local vardec */
// ATSlocal_void (tmp141) ;

__ats_lab_ATS_2d0_2e2_2e10_2src_2ats_hiexp_2esats__fprint_labhipatlst:
/* tmp141 = */ aux_14 (arg0, 0, arg1) ;
return /* (tmp141) */ ;
} /* end of [ATS_2d0_2e2_2e10_2src_2ats_hiexp_2esats__fprint_labhipatlst] */

/*
// /home/hwxi/research/Anairiats/src/ats_hiexp_print.dats: 7855(line=269, offs=14) -- 16955(line=555, offs=4)
*/
ATSglobaldec()
ats_void_type
ATS_2d0_2e2_2e10_2src_2ats_hiexp_2esats__fprint_hiexp (ats_ref_type arg0, ats_ptr_type arg1) {
/* local vardec */
// ATSlocal_void (tmp154) ;
ATSlocal (ats_ptr_type, tmp155) ;
ATSlocal (ats_ptr_type, tmp156) ;
ATSlocal (ats_ptr_type, tmp157) ;
ATSlocal (ats_ptr_type, tmp158) ;
// ATSlocal_void (tmp159) ;
// ATSlocal_void (tmp160) ;
// ATSlocal_void (tmp161) ;
// ATSlocal_void (tmp162) ;
// ATSlocal_void (tmp163) ;
// ATSlocal_void (tmp164) ;
ATSlocal (ats_ptr_type, tmp165) ;
ATSlocal (ats_ptr_type, tmp166) ;
ATSlocal (ats_ptr_type, tmp167) ;
// ATSlocal_void (tmp168) ;
// ATSlocal_void (tmp169) ;
// ATSlocal_void (tmp170) ;
// ATSlocal_void (tmp171) ;
ATSlocal (ats_ptr_type, tmp172) ;
// ATSlocal_void (tmp173) ;
// ATSlocal_void (tmp174) ;
ATSlocal (ats_ptr_type, tmp175) ;
ATSlocal (ats_ptr_type, tmp176) ;
// ATSlocal_void (tmp177) ;
// ATSlocal_void (tmp178) ;
// ATSlocal_void (tmp179) ;
// ATSlocal_void (tmp180) ;
ATSlocal (ats_ptr_type, tmp181) ;
ATSlocal (ats_ptr_type, tmp182) ;
ATSlocal (ats_ptr_type, tmp183) ;
// ATSlocal_void (tmp184) ;
// ATSlocal_void (tmp185) ;
// ATSlocal_void (tmp186) ;
// ATSlocal_void (tmp187) ;
// ATSlocal_void (tmp188) ;
// ATSlocal_void (tmp189) ;
ATSlocal (ats_ptr_type, tmp190) ;
ATSlocal (ats_ptr_type, tmp191) ;
ATSlocal (ats_ptr_type, tmp192) ;
// ATSlocal_void (tmp193) ;
// ATSlocal_void (tmp194) ;
// ATSlocal_void (tmp195) ;
// ATSlocal_void (tmp196) ;
// ATSlocal_void (tmp197) ;
// ATSlocal_void (tmp198) ;
ATSlocal (ats_bool_type, tmp199) ;
// ATSlocal_void (tmp200) ;
// ATSlocal_void (tmp201) ;
// ATSlocal_void (tmp202) ;
// ATSlocal_void (tmp203) ;
ATSlocal (ats_ptr_type, tmp204) ;
ATSlocal (ats_ptr_type, tmp205) ;
// ATSlocal_void (tmp206) ;
// ATSlocal_void (tmp207) ;
// ATSlocal_void (tmp208) ;
// ATSlocal_void (tmp209) ;
ATSlocal (ats_char_type, tmp210) ;
// ATSlocal_void (tmp211) ;
// ATSlocal_void (tmp212) ;
ATSlocal (ats_ptr_type, tmp213) ;
ATSlocal (ats_ptr_type, tmp214) ;
ATSlocal (ats_ptr_type, tmp215) ;
// ATSlocal_void (tmp216) ;
// ATSlocal_void (tmp217) ;
// ATSlocal_void (tmp218) ;
// ATSlocal_void (tmp219) ;
// ATSlocal_void (tmp220) ;
// ATSlocal_void (tmp221) ;
ATSlocal (ats_ptr_type, tmp222) ;
// ATSlocal_void (tmp223) ;
// ATSlocal_void (tmp224) ;
ATSlocal (ats_ptr_type, tmp225) ;
// ATSlocal_void (tmp226) ;
// ATSlocal_void (tmp227) ;
ATSlocal (ats_ptr_type, tmp228) ;
// ATSlocal_void (tmp229) ;
// ATSlocal_void (tmp230) ;
ATSlocal (ats_ptr_type, tmp231) ;
// ATSlocal_void (tmp232) ;
// ATSlocal_void (tmp233) ;
ATSlocal (ats_int_type, tmp234) ;
ATSlocal (ats_ptr_type, tmp235) ;
ATSlocal (ats_ptr_type, tmp236) ;
// ATSlocal_void (tmp237) ;
// ATSlocal_void (tmp238) ;
// ATSlocal_void (tmp239) ;
// ATSlocal_void (tmp240) ;
// ATSlocal_void (tmp241) ;
// ATSlocal_void (tmp242) ;
ATSlocal (ats_ptr_type, tmp243) ;
// ATSlocal_void (tmp244) ;
// ATSlocal_void (tmp245) ;
ATSlocal (ats_ptr_type, tmp246) ;
// ATSlocal_void (tmp247) ;
// ATSlocal_void (tmp248) ;
ATSlocal (ats_ptr_type, tmp249) ;
// ATSlocal_void (tmp250) ;
// ATSlocal_void (tmp251) ;
ATSlocal (ats_ptr_type, tmp252) ;
ATSlocal (ats_ptr_type, tmp253) ;
ATSlocal (ats_ptr_type, tmp254) ;
// ATSlocal_void (tmp255) ;
// ATSlocal_void (tmp256) ;
// ATSlocal_void (tmp257) ;
// ATSlocal_void (tmp258) ;
// ATSlocal_void (tmp259) ;
// ATSlocal_void (tmp260) ;
ATSlocal (ats_ptr_type, tmp261) ;
// ATSlocal_void (tmp262) ;
// ATSlocal_void (tmp263) ;
ATSlocal (ats_ptr_type, tmp264) ;
// ATSlocal_void (tmp265) ;
// ATSlocal_void (tmp266) ;
ATSlocal (ats_ptr_type, tmp267) ;
ATSlocal (ats_ptr_type, tmp268) ;
// ATSlocal_void (tmp269) ;
// ATSlocal_void (tmp270) ;
// ATSlocal_void (tmp271) ;
// ATSlocal_void (tmp272) ;
ATSlocal (ats_ptr_type, tmp273) ;
ATSlocal (ats_ptr_type, tmp274) ;
// ATSlocal_void (tmp275) ;
// ATSlocal_void (tmp276) ;
// ATSlocal_void (tmp277) ;
// ATSlocal_void (tmp278) ;
ATSlocal (ats_ptr_type, tmp279) ;
// ATSlocal_void (tmp280) ;
// ATSlocal_void (tmp281) ;
ATSlocal (ats_ptr_type, tmp282) ;
ATSlocal (ats_ptr_type, tmp283) ;
// ATSlocal_void (tmp284) ;
// ATSlocal_void (tmp285) ;
// ATSlocal_void (tmp286) ;
// ATSlocal_void (tmp287) ;
ATSlocal (ats_int_type, tmp288) ;
ATSlocal (ats_ptr_type, tmp289) ;
// ATSlocal_void (tmp290) ;
// ATSlocal_void (tmp291) ;
// ATSlocal_void (tmp292) ;
// ATSlocal_void (tmp293) ;
ATSlocal (ats_ptr_type, tmp294) ;
// ATSlocal_void (tmp295) ;
// ATSlocal_void (tmp296) ;
// ATSlocal_void (tmp297) ;
// ATSlocal_void (tmp298) ;
ATSlocal (ats_ptr_type, tmp299) ;
ATSlocal (ats_ptr_type, tmp300) ;
ATSlocal (ats_ptr_type, tmp301) ;
// ATSlocal_void (tmp302) ;
// ATSlocal_void (tmp303) ;
ATSlocal (ats_ptr_type, tmp304) ;
// ATSlocal_void (tmp305) ;
// ATSlocal_void (tmp306) ;
// ATSlocal_void (tmp307) ;
// ATSlocal_void (tmp308) ;
ATSlocal (ats_ptr_type, tmp309) ;
// ATSlocal_void (tmp310) ;
// ATSlocal_void (tmp311) ;
ATSlocal (ats_int_type, tmp312) ;
// ATSlocal_void (tmp313) ;
// ATSlocal_void (tmp314) ;
ATSlocal (ats_int_type, tmp315) ;
ATSlocal (ats_ptr_type, tmp316) ;
ATSlocal (ats_ptr_type, tmp317) ;
// ATSlocal_void (tmp318) ;
// ATSlocal_void (tmp319) ;
// ATSlocal_void (tmp320) ;
// ATSlocal_void (tmp321) ;
// ATSlocal_void (tmp322) ;
// ATSlocal_void (tmp323) ;
ATSlocal (ats_ptr_type, tmp324) ;
ATSlocal (ats_ptr_type, tmp325) ;
// ATSlocal_void (tmp326) ;
// ATSlocal_void (tmp327) ;
// ATSlocal_void (tmp328) ;
// ATSlocal_void (tmp329) ;
ATSlocal (ats_ptr_type, tmp330) ;
ATSlocal (ats_ptr_type, tmp331) ;
// ATSlocal_void (tmp332) ;
// ATSlocal_void (tmp333) ;
// ATSlocal_void (tmp334) ;
// ATSlocal_void (tmp335) ;
ATSlocal (ats_ptr_type, tmp336) ;
// ATSlocal_void (tmp337) ;
// ATSlocal_void (tmp338) ;
ATSlocal (ats_int_type, tmp339) ;
ATSlocal (ats_ptr_type, tmp340) ;
ATSlocal (ats_ptr_type, tmp341) ;
// ATSlocal_void (tmp342) ;
// ATSlocal_void (tmp343) ;
// ATSlocal_void (tmp344) ;
// ATSlocal_void (tmp345) ;
// ATSlocal_void (tmp346) ;
// ATSlocal_void (tmp347) ;
ATSlocal (ats_int_type, tmp348) ;
ATSlocal (ats_int_type, tmp349) ;
ATSlocal (ats_ptr_type, tmp350) ;
// ATSlocal_void (tmp351) ;
// ATSlocal_void (tmp352) ;
// ATSlocal_void (tmp353) ;
// ATSlocal_void (tmp354) ;
// ATSlocal_void (tmp355) ;
// ATSlocal_void (tmp356) ;
ATSlocal (ats_ptr_type, tmp357) ;
ATSlocal (ats_ptr_type, tmp358) ;
// ATSlocal_void (tmp359) ;
// ATSlocal_void (tmp360) ;
// ATSlocal_void (tmp361) ;
// ATSlocal_void (tmp362) ;
ATSlocal (ats_ptr_type, tmp363) ;
ATSlocal (ats_ptr_type, tmp364) ;
// ATSlocal_void (tmp365) ;
// ATSlocal_void (tmp366) ;
// ATSlocal_void (tmp367) ;
// ATSlocal_void (tmp368) ;
ATSlocal (ats_ptr_type, tmp369) ;
ATSlocal (ats_ptr_type, tmp370) ;
// ATSlocal_void (tmp371) ;
// ATSlocal_void (tmp372) ;
// ATSlocal_void (tmp373) ;
// ATSlocal_void (tmp374) ;
ATSlocal (ats_ptr_type, tmp375) ;
// ATSlocal_void (tmp376) ;
// ATSlocal_void (tmp377) ;
ATSlocal (ats_ptr_type, tmp378) ;
ATSlocal (ats_ptr_type, tmp379) ;
// ATSlocal_void (tmp380) ;
// ATSlocal_void (tmp381) ;
// ATSlocal_void (tmp382) ;
// ATSlocal_void (tmp383) ;
ATSlocal (ats_ptr_type, tmp384) ;
// ATSlocal_void (tmp385) ;
// ATSlocal_void (tmp386) ;
ATSlocal (ats_ptr_type, tmp387) ;
ATSlocal (ats_ptr_type, tmp388) ;
// ATSlocal_void (tmp389) ;
// ATSlocal_void (tmp390) ;
// ATSlocal_void (tmp391) ;
// ATSlocal_void (tmp392) ;
ATSlocal (ats_ptr_type, tmp393) ;
ATSlocal (ats_ptr_type, tmp394) ;
// ATSlocal_void (tmp395) ;
// ATSlocal_void (tmp396) ;
// ATSlocal_void (tmp397) ;
// ATSlocal_void (tmp398) ;
ATSlocal (ats_ptr_type, tmp399) ;
// ATSlocal_void (tmp400) ;
// ATSlocal_void (tmp401) ;

__ats_lab_ATS_2d0_2e2_2e10_2src_2ats_hiexp_2esats__fprint_hiexp:
tmp155 = ats_selbox_mac(ats_castptr_mac(anairiats_rec_11, arg1), atslab_hiexp_node) ;
do {
/* branch: __ats_lab_25 */
__ats_lab_25_0:
if (((ats_sum_ptr_type)tmp155)->tag != 0) { goto __ats_lab_26_0 ; }
__ats_lab_25_1:
tmp156 = ats_caselptrlab_mac(anairiats_sum_2, tmp155, atslab_0) ;
tmp157 = ats_caselptrlab_mac(anairiats_sum_2, tmp155, atslab_1) ;
tmp158 = ats_caselptrlab_mac(anairiats_sum_2, tmp155, atslab_2) ;
/* tmp159 = */ atspre_fprint_string (arg0, ATSstrcst("HIEapp(")) ;
/* tmp160 = */ ATS_2d0_2e2_2e10_2src_2ats_hiexp_2esats__fprint_hityp (arg0, tmp156) ;
/* tmp161 = */ atspre_fprint_string (arg0, ATSstrcst("; ")) ;
/* tmp162 = */ ATS_2d0_2e2_2e10_2src_2ats_hiexp_2esats__fprint_hiexp (arg0, tmp157) ;
/* tmp163 = */ atspre_fprint_string (arg0, ATSstrcst("; ")) ;
/* tmp164 = */ ATS_2d0_2e2_2e10_2src_2ats_hiexp_2esats__fprint_hiexplst (arg0, tmp158) ;
/* tmp154 = */ atspre_fprint_string (arg0, ATSstrcst(")")) ;
break ;

/* branch: __ats_lab_26 */
__ats_lab_26_0:
if (((ats_sum_ptr_type)tmp155)->tag != 1) { goto __ats_lab_29_0 ; }
__ats_lab_26_1:
tmp165 = ats_caselptrlab_mac(anairiats_sum_2, tmp155, atslab_0) ;
tmp166 = ats_caselptrlab_mac(anairiats_sum_2, tmp155, atslab_1) ;
tmp167 = ats_caselptrlab_mac(anairiats_sum_2, tmp155, atslab_2) ;
/* tmp168 = */ atspre_fprint_string (arg0, ATSstrcst("HIEarrinit(")) ;
/* tmp169 = */ ATS_2d0_2e2_2e10_2src_2ats_hiexp_2esats__fprint_hityp (arg0, tmp165) ;
/* tmp170 = */ atspre_fprint_string (arg0, ATSstrcst("; ")) ;
do {
/* branch: __ats_lab_27 */
__ats_lab_27_0:
if (tmp166 == (ats_sum_ptr_type)0) { goto __ats_lab_28_0 ; }
__ats_lab_27_1:
tmp172 = ats_caselptrlab_mac(anairiats_sum_12, tmp166, atslab_0) ;
/* tmp171 = */ ATS_2d0_2e2_2e10_2src_2ats_hiexp_2esats__fprint_hiexp (arg0, tmp172) ;
break ;

/* branch: __ats_lab_28 */
__ats_lab_28_0:
// if (tmp166 != (ats_sum_ptr_type)0) { ats_deadcode_failure_handle () ; }
__ats_lab_28_1:
break ;
} while (0) ;
/* tmp173 = */ atspre_fprint_string (arg0, ATSstrcst("; ")) ;
/* tmp174 = */ ATS_2d0_2e2_2e10_2src_2ats_hiexp_2esats__fprint_hiexplst (arg0, tmp167) ;
/* tmp154 = */ atspre_fprint_string (arg0, ATSstrcst(")")) ;
break ;

/* branch: __ats_lab_29 */
__ats_lab_29_0:
if (((ats_sum_ptr_type)tmp155)->tag != 2) { goto __ats_lab_30_0 ; }
__ats_lab_29_1:
tmp175 = ats_caselptrlab_mac(anairiats_sum_1, tmp155, atslab_0) ;
tmp176 = ats_caselptrlab_mac(anairiats_sum_1, tmp155, atslab_1) ;
/* tmp177 = */ atspre_fprint_string (arg0, ATSstrcst("HIEarrpsz(")) ;
/* tmp178 = */ ATS_2d0_2e2_2e10_2src_2ats_hiexp_2esats__fprint_hityp (arg0, tmp175) ;
/* tmp179 = */ atspre_fprint_string (arg0, ATSstrcst("; ")) ;
/* tmp180 = */ ATS_2d0_2e2_2e10_2src_2ats_hiexp_2esats__fprint_hiexplst (arg0, tmp176) ;
/* tmp154 = */ atspre_fprint_string (arg0, ATSstrcst(")")) ;
break ;

/* branch: __ats_lab_30 */
__ats_lab_30_0:
if (((ats_sum_ptr_type)tmp155)->tag != 3) { goto __ats_lab_31_0 ; }
__ats_lab_30_1:
tmp181 = ats_caselptrlab_mac(anairiats_sum_2, tmp155, atslab_0) ;
tmp182 = ats_caselptrlab_mac(anairiats_sum_2, tmp155, atslab_1) ;
tmp183 = ats_caselptrlab_mac(anairiats_sum_2, tmp155, atslab_2) ;
/* tmp184 = */ atspre_fprint_string (arg0, ATSstrcst("HIEassgn_ptr(")) ;
/* tmp185 = */ ATS_2d0_2e2_2e10_2src_2ats_hiexp_2esats__fprint_hiexp (arg0, tmp181) ;
/* tmp186 = */ atspre_fprint_string (arg0, ATSstrcst("; ")) ;
/* tmp187 = */ ATS_2d0_2e2_2e10_2src_2ats_hiexp_2esats__fprint_hilablst (arg0, tmp182) ;
/* tmp188 = */ atspre_fprint_string (arg0, ATSstrcst("; ")) ;
/* tmp189 = */ ATS_2d0_2e2_2e10_2src_2ats_hiexp_2esats__fprint_hiexp (arg0, tmp183) ;
/* tmp154 = */ atspre_fprint_string (arg0, ATSstrcst(")")) ;
break ;

/* branch: __ats_lab_31 */
__ats_lab_31_0:
if (((ats_sum_ptr_type)tmp155)->tag != 4) { goto __ats_lab_32_0 ; }
__ats_lab_31_1:
tmp190 = ats_caselptrlab_mac(anairiats_sum_2, tmp155, atslab_0) ;
tmp191 = ats_caselptrlab_mac(anairiats_sum_2, tmp155, atslab_1) ;
tmp192 = ats_caselptrlab_mac(anairiats_sum_2, tmp155, atslab_2) ;
/* tmp193 = */ atspre_fprint_string (arg0, ATSstrcst("HIEassgn_var(")) ;
/* tmp194 = */ ATS_2d0_2e2_2e10_2src_2ats_dynexp2_2esats__fprint_d2var (arg0, tmp190) ;
/* tmp195 = */ atspre_fprint_string (arg0, ATSstrcst("; ")) ;
/* tmp196 = */ ATS_2d0_2e2_2e10_2src_2ats_hiexp_2esats__fprint_hilablst (arg0, tmp191) ;
/* tmp197 = */ atspre_fprint_string (arg0, ATSstrcst("; ")) ;
/* tmp198 = */ ATS_2d0_2e2_2e10_2src_2ats_hiexp_2esats__fprint_hiexp (arg0, tmp192) ;
/* tmp154 = */ atspre_fprint_string (arg0, ATSstrcst(")")) ;
break ;

/* branch: __ats_lab_32 */
__ats_lab_32_0:
if (((ats_sum_ptr_type)tmp155)->tag != 5) { goto __ats_lab_33_0 ; }
__ats_lab_32_1:
tmp199 = ats_caselptrlab_mac(anairiats_sum_8, tmp155, atslab_0) ;
/* tmp200 = */ atspre_fprint_string (arg0, ATSstrcst("HIEbool(")) ;
/* tmp201 = */ atspre_fprint_bool (arg0, tmp199) ;
/* tmp154 = */ atspre_fprint_string (arg0, ATSstrcst(")")) ;
break ;

/* branch: __ats_lab_33 */
__ats_lab_33_0:
if (((ats_sum_ptr_type)tmp155)->tag != 6) { goto __ats_lab_34_0 ; }
__ats_lab_33_1:
/* tmp202 = */ atspre_fprint_string (arg0, ATSstrcst("HIEcaseof(")) ;
/* tmp203 = */ atspre_fprint_string (arg0, ATSstrcst("...")) ;
/* tmp154 = */ atspre_fprint_string (arg0, ATSstrcst(")")) ;
break ;

/* branch: __ats_lab_34 */
__ats_lab_34_0:
if (((ats_sum_ptr_type)tmp155)->tag != 7) { goto __ats_lab_35_0 ; }
__ats_lab_34_1:
tmp204 = ats_caselptrlab_mac(anairiats_sum_1, tmp155, atslab_0) ;
tmp205 = ats_caselptrlab_mac(anairiats_sum_1, tmp155, atslab_1) ;
/* tmp206 = */ atspre_fprint_string (arg0, ATSstrcst("HIEcastfn(")) ;
/* tmp207 = */ ATS_2d0_2e2_2e10_2src_2ats_dynexp2_2esats__fprint_d2cst (arg0, tmp204) ;
/* tmp208 = */ atspre_fprint_string (arg0, ATSstrcst("; ")) ;
/* tmp209 = */ ATS_2d0_2e2_2e10_2src_2ats_hiexp_2esats__fprint_hiexp (arg0, tmp205) ;
/* tmp154 = */ atspre_fprint_string (arg0, ATSstrcst(")")) ;
break ;

/* branch: __ats_lab_35 */
__ats_lab_35_0:
if (((ats_sum_ptr_type)tmp155)->tag != 8) { goto __ats_lab_36_0 ; }
__ats_lab_35_1:
tmp210 = ats_caselptrlab_mac(anairiats_sum_9, tmp155, atslab_0) ;
/* tmp211 = */ atspre_fprint_string (arg0, ATSstrcst("HIEchar(")) ;
/* tmp212 = */ atspre_fprint_char (arg0, tmp210) ;
/* tmp154 = */ atspre_fprint_string (arg0, ATSstrcst(")")) ;
break ;

/* branch: __ats_lab_36 */
__ats_lab_36_0:
if (((ats_sum_ptr_type)tmp155)->tag != 9) { goto __ats_lab_37_0 ; }
__ats_lab_36_1:
tmp213 = ats_caselptrlab_mac(anairiats_sum_2, tmp155, atslab_0) ;
tmp214 = ats_caselptrlab_mac(anairiats_sum_2, tmp155, atslab_1) ;
tmp215 = ats_caselptrlab_mac(anairiats_sum_2, tmp155, atslab_2) ;
/* tmp216 = */ atspre_fprint_string (arg0, ATSstrcst("HIEcon(")) ;
/* tmp217 = */ ATS_2d0_2e2_2e10_2src_2ats_hiexp_2esats__fprint_hityp (arg0, tmp213) ;
/* tmp218 = */ atspre_fprint_string (arg0, ATSstrcst("; ")) ;
/* tmp219 = */ ATS_2d0_2e2_2e10_2src_2ats_staexp2_2esats__fprint_d2con (arg0, tmp214) ;
/* tmp220 = */ atspre_fprint_string (arg0, ATSstrcst("; ")) ;
/* tmp221 = */ ATS_2d0_2e2_2e10_2src_2ats_hiexp_2esats__fprint_hiexplst (arg0, tmp215) ;
/* tmp154 = */ atspre_fprint_string (arg0, ATSstrcst(")")) ;
break ;

/* branch: __ats_lab_37 */
__ats_lab_37_0:
if (((ats_sum_ptr_type)tmp155)->tag != 10) { goto __ats_lab_38_0 ; }
__ats_lab_37_1:
tmp222 = ats_caselptrlab_mac(anairiats_sum_4, tmp155, atslab_0) ;
/* tmp223 = */ atspre_fprint_string (arg0, ATSstrcst("HIEcst(")) ;
/* tmp224 = */ ATS_2d0_2e2_2e10_2src_2ats_dynexp2_2esats__fprint_d2cst (arg0, tmp222) ;
/* tmp154 = */ atspre_fprint_string (arg0, ATSstrcst(")")) ;
break ;

/* branch: __ats_lab_38 */
__ats_lab_38_0:
if (((ats_sum_ptr_type)tmp155)->tag != 11) { goto __ats_lab_39_0 ; }
__ats_lab_38_1:
tmp225 = ats_caselptrlab_mac(anairiats_sum_4, tmp155, atslab_0) ;
/* tmp226 = */ atspre_fprint_string (arg0, ATSstrcst("HIEcstsp(")) ;
/* tmp227 = */ ATS_2d0_2e2_2e10_2src_2ats_syntax_2esats__fprint_cstsp (arg0, tmp225) ;
/* tmp154 = */ atspre_fprint_string (arg0, ATSstrcst(")")) ;
break ;

/* branch: __ats_lab_39 */
__ats_lab_39_0:
if (((ats_sum_ptr_type)tmp155)->tag != 12) { goto __ats_lab_40_0 ; }
__ats_lab_39_1:
tmp228 = ats_caselptrlab_mac(anairiats_sum_4, tmp155, atslab_0) ;
/* tmp229 = */ atspre_fprint_string (arg0, ATSstrcst("HIEdynload(")) ;
/* tmp230 = */ ATS_2d0_2e2_2e10_2src_2ats_filename_2esats__fprint_filename (arg0, tmp228) ;
/* tmp154 = */ atspre_fprint_string (arg0, ATSstrcst(")")) ;
break ;

/* branch: __ats_lab_40 */
__ats_lab_40_0:
if (((ats_sum_ptr_type)tmp155)->tag != 13) { goto __ats_lab_41_0 ; }
__ats_lab_40_1:
/* tmp154 = */ atspre_fprint_string (arg0, ATSstrcst("HIEempty()")) ;
break ;

/* branch: __ats_lab_41 */
__ats_lab_41_0:
if (((ats_sum_ptr_type)tmp155)->tag != 14) { goto __ats_lab_42_0 ; }
__ats_lab_41_1:
tmp231 = ats_caselptrlab_mac(anairiats_sum_4, tmp155, atslab_0) ;
/* tmp232 = */ atspre_fprint_string (arg0, ATSstrcst("HIEextval(")) ;
/* tmp233 = */ atspre_fprint_string (arg0, tmp231) ;
/* tmp154 = */ atspre_fprint_string (arg0, ATSstrcst(")")) ;
break ;

/* branch: __ats_lab_42 */
__ats_lab_42_0:
if (((ats_sum_ptr_type)tmp155)->tag != 15) { goto __ats_lab_43_0 ; }
__ats_lab_42_1:
tmp234 = ats_caselptrlab_mac(anairiats_sum_7, tmp155, atslab_0) ;
tmp235 = ats_caselptrlab_mac(anairiats_sum_7, tmp155, atslab_1) ;
tmp236 = ats_caselptrlab_mac(anairiats_sum_7, tmp155, atslab_2) ;
/* tmp237 = */ atspre_fprint_string (arg0, ATSstrcst("HIEfix(")) ;
/* tmp238 = */ atspre_fprint_int (arg0, tmp234) ;
/* tmp239 = */ atspre_fprint_string (arg0, ATSstrcst("; ")) ;
/* tmp240 = */ ATS_2d0_2e2_2e10_2src_2ats_dynexp2_2esats__fprint_d2var (arg0, tmp235) ;
/* tmp241 = */ atspre_fprint_string (arg0, ATSstrcst("; ")) ;
/* tmp242 = */ ATS_2d0_2e2_2e10_2src_2ats_hiexp_2esats__fprint_hiexp (arg0, tmp236) ;
/* tmp154 = */ atspre_fprint_string (arg0, ATSstrcst(")")) ;
break ;

/* branch: __ats_lab_43 */
__ats_lab_43_0:
if (((ats_sum_ptr_type)tmp155)->tag != 16) { goto __ats_lab_44_0 ; }
__ats_lab_43_1:
tmp243 = ats_caselptrlab_mac(anairiats_sum_4, tmp155, atslab_0) ;
/* tmp244 = */ atspre_fprint_string (arg0, ATSstrcst("HIEfloat(")) ;
/* tmp245 = */ atspre_fprint_string (arg0, tmp243) ;
/* tmp154 = */ atspre_fprint_string (arg0, ATSstrcst(")")) ;
break ;

/* branch: __ats_lab_44 */
__ats_lab_44_0:
if (((ats_sum_ptr_type)tmp155)->tag != 17) { goto __ats_lab_45_0 ; }
__ats_lab_44_1:
tmp246 = ats_caselptrlab_mac(anairiats_sum_4, tmp155, atslab_0) ;
/* tmp247 = */ atspre_fprint_string (arg0, ATSstrcst("HIEfloatsp(")) ;
/* tmp248 = */ atspre_fprint_string (arg0, tmp246) ;
/* tmp154 = */ atspre_fprint_string (arg0, ATSstrcst(")")) ;
break ;

/* branch: __ats_lab_45 */
__ats_lab_45_0:
if (((ats_sum_ptr_type)tmp155)->tag != 18) { goto __ats_lab_46_0 ; }
__ats_lab_45_1:
tmp249 = ats_caselptrlab_mac(anairiats_sum_4, tmp155, atslab_0) ;
/* tmp250 = */ atspre_fprint_string (arg0, ATSstrcst("HIEfreeat(")) ;
/* tmp251 = */ ATS_2d0_2e2_2e10_2src_2ats_hiexp_2esats__fprint_hiexp (arg0, tmp249) ;
/* tmp154 = */ atspre_fprint_string (arg0, ATSstrcst(")")) ;
break ;

/* branch: __ats_lab_46 */
__ats_lab_46_0:
if (((ats_sum_ptr_type)tmp155)->tag != 19) { goto __ats_lab_47_0 ; }
__ats_lab_46_1:
tmp252 = ats_caselptrlab_mac(anairiats_sum_2, tmp155, atslab_0) ;
tmp253 = ats_caselptrlab_mac(anairiats_sum_2, tmp155, atslab_1) ;
tmp254 = ats_caselptrlab_mac(anairiats_sum_2, tmp155, atslab_2) ;
/* tmp255 = */ atspre_fprint_string (arg0, ATSstrcst("HIEif(")) ;
/* tmp256 = */ ATS_2d0_2e2_2e10_2src_2ats_hiexp_2esats__fprint_hiexp (arg0, tmp252) ;
/* tmp257 = */ atspre_fprint_string (arg0, ATSstrcst("; ")) ;
/* tmp258 = */ ATS_2d0_2e2_2e10_2src_2ats_hiexp_2esats__fprint_hiexp (arg0, tmp253) ;
/* tmp259 = */ atspre_fprint_string (arg0, ATSstrcst("; ")) ;
/* tmp260 = */ ATS_2d0_2e2_2e10_2src_2ats_hiexp_2esats__fprint_hiexp (arg0, tmp254) ;
/* tmp154 = */ atspre_fprint_string (arg0, ATSstrcst(")")) ;
break ;

/* branch: __ats_lab_47 */
__ats_lab_47_0:
if (((ats_sum_ptr_type)tmp155)->tag != 20) { goto __ats_lab_48_0 ; }
__ats_lab_47_1:
tmp261 = ats_caselptrlab_mac(anairiats_sum_1, tmp155, atslab_1) ;
/* tmp262 = */ atspre_fprint_string (arg0, ATSstrcst("HIEint(")) ;
/* tmp263 = */ ATS_2d0_2e2_2e10_2src_2ats_intinf_2esats__fprint_intinf (arg0, tmp261) ;
/* tmp154 = */ atspre_fprint_string (arg0, ATSstrcst(")")) ;
break ;

/* branch: __ats_lab_48 */
__ats_lab_48_0:
if (((ats_sum_ptr_type)tmp155)->tag != 21) { goto __ats_lab_49_0 ; }
__ats_lab_48_1:
tmp264 = ats_caselptrlab_mac(anairiats_sum_1, tmp155, atslab_0) ;
/* tmp265 = */ atspre_fprint_string (arg0, ATSstrcst("HIEintsp(")) ;
/* tmp266 = */ atspre_fprint_string (arg0, tmp264) ;
/* tmp154 = */ atspre_fprint_string (arg0, ATSstrcst(")")) ;
break ;

/* branch: __ats_lab_49 */
__ats_lab_49_0:
if (((ats_sum_ptr_type)tmp155)->tag != 22) { goto __ats_lab_50_0 ; }
__ats_lab_49_1:
tmp267 = ats_caselptrlab_mac(anairiats_sum_1, tmp155, atslab_0) ;
tmp268 = ats_caselptrlab_mac(anairiats_sum_1, tmp155, atslab_1) ;
/* tmp269 = */ atspre_fprint_string (arg0, ATSstrcst("HIElam(")) ;
/* tmp270 = */ ATS_2d0_2e2_2e10_2src_2ats_hiexp_2esats__fprint_hipatlst (arg0, tmp267) ;
/* tmp271 = */ atspre_fprint_string (arg0, ATSstrcst("; ")) ;
/* tmp272 = */ ATS_2d0_2e2_2e10_2src_2ats_hiexp_2esats__fprint_hiexp (arg0, tmp268) ;
/* tmp154 = */ atspre_fprint_string (arg0, ATSstrcst(")")) ;
break ;

/* branch: __ats_lab_50 */
__ats_lab_50_0:
if (((ats_sum_ptr_type)tmp155)->tag != 23) { goto __ats_lab_51_0 ; }
__ats_lab_50_1:
tmp273 = ats_caselptrlab_mac(anairiats_sum_1, tmp155, atslab_0) ;
tmp274 = ats_caselptrlab_mac(anairiats_sum_1, tmp155, atslab_1) ;
/* tmp275 = */ atspre_fprint_string (arg0, ATSstrcst("HIElaminit(")) ;
/* tmp276 = */ ATS_2d0_2e2_2e10_2src_2ats_hiexp_2esats__fprint_hipatlst (arg0, tmp273) ;
/* tmp277 = */ atspre_fprint_string (arg0, ATSstrcst("; ")) ;
/* tmp278 = */ ATS_2d0_2e2_2e10_2src_2ats_hiexp_2esats__fprint_hiexp (arg0, tmp274) ;
/* tmp154 = */ atspre_fprint_string (arg0, ATSstrcst(")")) ;
break ;

/* branch: __ats_lab_51 */
__ats_lab_51_0:
if (((ats_sum_ptr_type)tmp155)->tag != 24) { goto __ats_lab_52_0 ; }
__ats_lab_51_1:
tmp279 = ats_caselptrlab_mac(anairiats_sum_4, tmp155, atslab_0) ;
/* tmp280 = */ atspre_fprint_string (arg0, ATSstrcst("HIElazy_delay(")) ;
/* tmp281 = */ ATS_2d0_2e2_2e10_2src_2ats_hiexp_2esats__fprint_hiexp (arg0, tmp279) ;
/* tmp154 = */ atspre_fprint_string (arg0, ATSstrcst(")")) ;
break ;

/* branch: __ats_lab_52 */
__ats_lab_52_0:
if (((ats_sum_ptr_type)tmp155)->tag != 25) { goto __ats_lab_53_0 ; }
__ats_lab_52_1:
tmp282 = ats_caselptrlab_mac(anairiats_sum_1, tmp155, atslab_0) ;
tmp283 = ats_caselptrlab_mac(anairiats_sum_1, tmp155, atslab_1) ;
/* tmp284 = */ atspre_fprint_string (arg0, ATSstrcst("HIElazy_delay(")) ;
/* tmp285 = */ ATS_2d0_2e2_2e10_2src_2ats_hiexp_2esats__fprint_hiexp (arg0, tmp282) ;
/* tmp286 = */ atspre_fprint_string (arg0, ATSstrcst("; ")) ;
/* tmp287 = */ ATS_2d0_2e2_2e10_2src_2ats_hiexp_2esats__fprint_hiexp (arg0, tmp283) ;
/* tmp154 = */ atspre_fprint_string (arg0, ATSstrcst(")")) ;
break ;

/* branch: __ats_lab_53 */
__ats_lab_53_0:
if (((ats_sum_ptr_type)tmp155)->tag != 26) { goto __ats_lab_54_0 ; }
__ats_lab_53_1:
tmp288 = ats_caselptrlab_mac(anairiats_sum_3, tmp155, atslab_0) ;
tmp289 = ats_caselptrlab_mac(anairiats_sum_3, tmp155, atslab_1) ;
/* tmp290 = */ atspre_fprint_string (arg0, ATSstrcst("HIElazy_force(")) ;
/* tmp291 = */ atspre_fprint_int (arg0, tmp288) ;
/* tmp292 = */ atspre_fprint_string (arg0, ATSstrcst("; ")) ;
/* tmp293 = */ ATS_2d0_2e2_2e10_2src_2ats_hiexp_2esats__fprint_hiexp (arg0, tmp289) ;
/* tmp154 = */ atspre_fprint_string (arg0, ATSstrcst(")")) ;
break ;

/* branch: __ats_lab_54 */
__ats_lab_54_0:
if (((ats_sum_ptr_type)tmp155)->tag != 27) { goto __ats_lab_55_0 ; }
__ats_lab_54_1:
tmp294 = ats_caselptrlab_mac(anairiats_sum_1, tmp155, atslab_1) ;
/* tmp295 = */ atspre_fprint_string (arg0, ATSstrcst("HIElet(")) ;
/* tmp296 = */ atspre_fprint_string (arg0, ATSstrcst("...")) ;
/* tmp297 = */ atspre_fprint_string (arg0, ATSstrcst("; ")) ;
/* tmp298 = */ ATS_2d0_2e2_2e10_2src_2ats_hiexp_2esats__fprint_hiexp (arg0, tmp294) ;
/* tmp154 = */ atspre_fprint_string (arg0, ATSstrcst(")")) ;
break ;

/* branch: __ats_lab_55 */
__ats_lab_55_0:
if (((ats_sum_ptr_type)tmp155)->tag != 28) { goto __ats_lab_60_0 ; }
__ats_lab_55_1:
tmp299 = ats_caselptrlab_mac(anairiats_sum_13, tmp155, atslab_1) ;
tmp300 = ats_caselptrlab_mac(anairiats_sum_13, tmp155, atslab_2) ;
tmp301 = ats_caselptrlab_mac(anairiats_sum_13, tmp155, atslab_3) ;
/* tmp302 = */ atspre_fprint_string (arg0, ATSstrcst("HIEloop(")) ;
do {
/* branch: __ats_lab_56 */
__ats_lab_56_0:
if (tmp300 != (ats_sum_ptr_type)0) { goto __ats_lab_57_0 ; }
__ats_lab_56_1:
break ;

/* branch: __ats_lab_57 */
__ats_lab_57_0:
// if (tmp300 == (ats_sum_ptr_type)0) { ats_deadcode_failure_handle () ; }
__ats_lab_57_1:
tmp304 = ats_caselptrlab_mac(anairiats_sum_12, tmp300, atslab_0) ;
/* tmp303 = */ ATS_2d0_2e2_2e10_2src_2ats_hiexp_2esats__fprint_hiexp (arg0, tmp304) ;
break ;
} while (0) ;
/* tmp305 = */ atspre_fprint_string (arg0, ATSstrcst("; ")) ;
/* tmp306 = */ ATS_2d0_2e2_2e10_2src_2ats_hiexp_2esats__fprint_hiexp (arg0, tmp299) ;
/* tmp307 = */ atspre_fprint_string (arg0, ATSstrcst("; ")) ;
do {
/* branch: __ats_lab_58 */
__ats_lab_58_0:
if (tmp300 != (ats_sum_ptr_type)0) { goto __ats_lab_59_0 ; }
__ats_lab_58_1:
break ;

/* branch: __ats_lab_59 */
__ats_lab_59_0:
// if (tmp300 == (ats_sum_ptr_type)0) { ats_deadcode_failure_handle () ; }
__ats_lab_59_1:
tmp309 = ats_caselptrlab_mac(anairiats_sum_12, tmp300, atslab_0) ;
/* tmp308 = */ ATS_2d0_2e2_2e10_2src_2ats_hiexp_2esats__fprint_hiexp (arg0, tmp309) ;
break ;
} while (0) ;
/* tmp310 = */ atspre_fprint_string (arg0, ATSstrcst("; ")) ;
/* tmp311 = */ ATS_2d0_2e2_2e10_2src_2ats_hiexp_2esats__fprint_hiexp (arg0, tmp301) ;
/* tmp154 = */ atspre_fprint_string (arg0, ATSstrcst(")")) ;
break ;

/* branch: __ats_lab_60 */
__ats_lab_60_0:
if (((ats_sum_ptr_type)tmp155)->tag != 29) { goto __ats_lab_61_0 ; }
__ats_lab_60_1:
tmp312 = ats_caselptrlab_mac(anairiats_sum_14, tmp155, atslab_0) ;
/* tmp313 = */ atspre_fprint_string (arg0, ATSstrcst("HIEloopexn(")) ;
/* tmp314 = */ atspre_fprint_int (arg0, tmp312) ;
/* tmp154 = */ atspre_fprint_string (arg0, ATSstrcst(")")) ;
break ;

/* branch: __ats_lab_61 */
__ats_lab_61_0:
if (((ats_sum_ptr_type)tmp155)->tag != 30) { goto __ats_lab_62_0 ; }
__ats_lab_61_1:
tmp315 = ats_caselptrlab_mac(anairiats_sum_7, tmp155, atslab_0) ;
tmp316 = ats_caselptrlab_mac(anairiats_sum_7, tmp155, atslab_1) ;
tmp317 = ats_caselptrlab_mac(anairiats_sum_7, tmp155, atslab_2) ;
/* tmp318 = */ atspre_fprint_string (arg0, ATSstrcst("HIElst(")) ;
/* tmp319 = */ atspre_fprint_int (arg0, tmp315) ;
/* tmp320 = */ atspre_fprint_string (arg0, ATSstrcst("; ")) ;
/* tmp321 = */ ATS_2d0_2e2_2e10_2src_2ats_hiexp_2esats__fprint_hityp (arg0, tmp316) ;
/* tmp322 = */ atspre_fprint_string (arg0, ATSstrcst("; ")) ;
/* tmp323 = */ ATS_2d0_2e2_2e10_2src_2ats_hiexp_2esats__fprint_hiexplst (arg0, tmp317) ;
/* tmp154 = */ atspre_fprint_string (arg0, ATSstrcst(")")) ;
break ;

/* branch: __ats_lab_62 */
__ats_lab_62_0:
if (((ats_sum_ptr_type)tmp155)->tag != 31) { goto __ats_lab_63_0 ; }
__ats_lab_62_1:
tmp324 = ats_caselptrlab_mac(anairiats_sum_1, tmp155, atslab_0) ;
tmp325 = ats_caselptrlab_mac(anairiats_sum_1, tmp155, atslab_1) ;
/* tmp326 = */ atspre_fprint_string (arg0, ATSstrcst("HIEptrof_ptr(")) ;
/* tmp327 = */ ATS_2d0_2e2_2e10_2src_2ats_hiexp_2esats__fprint_hiexp (arg0, tmp324) ;
/* tmp328 = */ atspre_fprint_string (arg0, ATSstrcst("; ")) ;
/* tmp329 = */ ATS_2d0_2e2_2e10_2src_2ats_hiexp_2esats__fprint_hilablst (arg0, tmp325) ;
/* tmp154 = */ atspre_fprint_string (arg0, ATSstrcst(")")) ;
break ;

/* branch: __ats_lab_63 */
__ats_lab_63_0:
if (((ats_sum_ptr_type)tmp155)->tag != 32) { goto __ats_lab_64_0 ; }
__ats_lab_63_1:
tmp330 = ats_caselptrlab_mac(anairiats_sum_1, tmp155, atslab_0) ;
tmp331 = ats_caselptrlab_mac(anairiats_sum_1, tmp155, atslab_1) ;
/* tmp332 = */ atspre_fprint_string (arg0, ATSstrcst("HIEptrof_var(")) ;
/* tmp333 = */ ATS_2d0_2e2_2e10_2src_2ats_dynexp2_2esats__fprint_d2var (arg0, tmp330) ;
/* tmp334 = */ atspre_fprint_string (arg0, ATSstrcst("; ")) ;
/* tmp335 = */ ATS_2d0_2e2_2e10_2src_2ats_hiexp_2esats__fprint_hilablst (arg0, tmp331) ;
/* tmp154 = */ atspre_fprint_string (arg0, ATSstrcst(")")) ;
break ;

/* branch: __ats_lab_64 */
__ats_lab_64_0:
if (((ats_sum_ptr_type)tmp155)->tag != 33) { goto __ats_lab_65_0 ; }
__ats_lab_64_1:
tmp336 = ats_caselptrlab_mac(anairiats_sum_4, tmp155, atslab_0) ;
/* tmp337 = */ atspre_fprint_string (arg0, ATSstrcst("HIEraise(")) ;
/* tmp338 = */ ATS_2d0_2e2_2e10_2src_2ats_hiexp_2esats__fprint_hiexp (arg0, tmp336) ;
/* tmp154 = */ atspre_fprint_string (arg0, ATSstrcst(")")) ;
break ;

/* branch: __ats_lab_65 */
__ats_lab_65_0:
if (((ats_sum_ptr_type)tmp155)->tag != 34) { goto __ats_lab_66_0 ; }
__ats_lab_65_1:
tmp339 = ats_caselptrlab_mac(anairiats_sum_7, tmp155, atslab_0) ;
tmp340 = ats_caselptrlab_mac(anairiats_sum_7, tmp155, atslab_1) ;
tmp341 = ats_caselptrlab_mac(anairiats_sum_7, tmp155, atslab_2) ;
/* tmp342 = */ atspre_fprint_string (arg0, ATSstrcst("HIErec(")) ;
/* tmp343 = */ atspre_fprint_int (arg0, tmp339) ;
/* tmp344 = */ atspre_fprint_string (arg0, ATSstrcst("; ")) ;
/* tmp345 = */ ATS_2d0_2e2_2e10_2src_2ats_hiexp_2esats__fprint_hityp (arg0, tmp340) ;
/* tmp346 = */ atspre_fprint_string (arg0, ATSstrcst("; ")) ;
/* tmp347 = */ ATS_2d0_2e2_2e10_2src_2ats_hiexp_2esats__fprint_labhiexplst (arg0, tmp341) ;
/* tmp154 = */ atspre_fprint_string (arg0, ATSstrcst(")")) ;
break ;

/* branch: __ats_lab_66 */
__ats_lab_66_0:
if (((ats_sum_ptr_type)tmp155)->tag != 35) { goto __ats_lab_67_0 ; }
__ats_lab_66_1:
tmp348 = ats_caselptrlab_mac(anairiats_sum_15, tmp155, atslab_0) ;
tmp349 = ats_caselptrlab_mac(anairiats_sum_15, tmp155, atslab_1) ;
tmp350 = ats_caselptrlab_mac(anairiats_sum_15, tmp155, atslab_2) ;
/* tmp351 = */ atspre_fprint_string (arg0, ATSstrcst("HIErefarg(")) ;
/* tmp352 = */ atspre_fprint_int (arg0, tmp348) ;
/* tmp353 = */ atspre_fprint_string (arg0, ATSstrcst("; ")) ;
/* tmp354 = */ atspre_fprint_int (arg0, tmp349) ;
/* tmp355 = */ atspre_fprint_string (arg0, ATSstrcst("; ")) ;
/* tmp356 = */ ATS_2d0_2e2_2e10_2src_2ats_hiexp_2esats__fprint_hiexp (arg0, tmp350) ;
/* tmp154 = */ atspre_fprint_string (arg0, ATSstrcst(")")) ;
break ;

/* branch: __ats_lab_67 */
__ats_lab_67_0:
if (((ats_sum_ptr_type)tmp155)->tag != 36) { goto __ats_lab_68_0 ; }
__ats_lab_67_1:
tmp357 = ats_caselptrlab_mac(anairiats_sum_1, tmp155, atslab_0) ;
tmp358 = ats_caselptrlab_mac(anairiats_sum_1, tmp155, atslab_1) ;
/* tmp359 = */ atspre_fprint_string (arg0, ATSstrcst("HIEsel(")) ;
/* tmp360 = */ ATS_2d0_2e2_2e10_2src_2ats_hiexp_2esats__fprint_hiexp (arg0, tmp357) ;
/* tmp361 = */ atspre_fprint_string (arg0, ATSstrcst("; ")) ;
/* tmp362 = */ ATS_2d0_2e2_2e10_2src_2ats_hiexp_2esats__fprint_hilablst (arg0, tmp358) ;
/* tmp154 = */ atspre_fprint_string (arg0, ATSstrcst(")")) ;
break ;

/* branch: __ats_lab_68 */
__ats_lab_68_0:
if (((ats_sum_ptr_type)tmp155)->tag != 37) { goto __ats_lab_69_0 ; }
__ats_lab_68_1:
tmp363 = ats_caselptrlab_mac(anairiats_sum_1, tmp155, atslab_0) ;
tmp364 = ats_caselptrlab_mac(anairiats_sum_1, tmp155, atslab_1) ;
/* tmp365 = */ atspre_fprint_string (arg0, ATSstrcst("HIEsel_ptr(")) ;
/* tmp366 = */ ATS_2d0_2e2_2e10_2src_2ats_hiexp_2esats__fprint_hiexp (arg0, tmp363) ;
/* tmp367 = */ atspre_fprint_string (arg0, ATSstrcst("; ")) ;
/* tmp368 = */ ATS_2d0_2e2_2e10_2src_2ats_hiexp_2esats__fprint_hilablst (arg0, tmp364) ;
/* tmp154 = */ atspre_fprint_string (arg0, ATSstrcst(")")) ;
break ;

/* branch: __ats_lab_69 */
__ats_lab_69_0:
if (((ats_sum_ptr_type)tmp155)->tag != 38) { goto __ats_lab_70_0 ; }
__ats_lab_69_1:
tmp369 = ats_caselptrlab_mac(anairiats_sum_1, tmp155, atslab_0) ;
tmp370 = ats_caselptrlab_mac(anairiats_sum_1, tmp155, atslab_1) ;
/* tmp371 = */ atspre_fprint_string (arg0, ATSstrcst("HIEsel_var(")) ;
/* tmp372 = */ ATS_2d0_2e2_2e10_2src_2ats_dynexp2_2esats__fprint_d2var (arg0, tmp369) ;
/* tmp373 = */ atspre_fprint_string (arg0, ATSstrcst("; ")) ;
/* tmp374 = */ ATS_2d0_2e2_2e10_2src_2ats_hiexp_2esats__fprint_hilablst (arg0, tmp370) ;
/* tmp154 = */ atspre_fprint_string (arg0, ATSstrcst(")")) ;
break ;

/* branch: __ats_lab_70 */
__ats_lab_70_0:
if (((ats_sum_ptr_type)tmp155)->tag != 39) { goto __ats_lab_71_0 ; }
__ats_lab_70_1:
tmp375 = ats_caselptrlab_mac(anairiats_sum_4, tmp155, atslab_0) ;
/* tmp376 = */ atspre_fprint_string (arg0, ATSstrcst("HIEseq(")) ;
/* tmp377 = */ ATS_2d0_2e2_2e10_2src_2ats_hiexp_2esats__fprint_hiexplst (arg0, tmp375) ;
/* tmp154 = */ atspre_fprint_string (arg0, ATSstrcst(")")) ;
break ;

/* branch: __ats_lab_71 */
__ats_lab_71_0:
if (((ats_sum_ptr_type)tmp155)->tag != 40) { goto __ats_lab_72_0 ; }
__ats_lab_71_1:
tmp378 = ats_caselptrlab_mac(anairiats_sum_1, tmp155, atslab_0) ;
tmp379 = ats_caselptrlab_mac(anairiats_sum_1, tmp155, atslab_1) ;
/* tmp380 = */ atspre_fprint_string (arg0, ATSstrcst("HIEsif(")) ;
/* tmp381 = */ ATS_2d0_2e2_2e10_2src_2ats_hiexp_2esats__fprint_hiexp (arg0, tmp378) ;
/* tmp382 = */ atspre_fprint_string (arg0, ATSstrcst(", ")) ;
/* tmp383 = */ ATS_2d0_2e2_2e10_2src_2ats_hiexp_2esats__fprint_hiexp (arg0, tmp379) ;
/* tmp154 = */ atspre_fprint_string (arg0, ATSstrcst(")")) ;
break ;

/* branch: __ats_lab_72 */
__ats_lab_72_0:
if (((ats_sum_ptr_type)tmp155)->tag != 41) { goto __ats_lab_73_0 ; }
__ats_lab_72_1:
tmp384 = ats_caselptrlab_mac(anairiats_sum_4, tmp155, atslab_0) ;
/* tmp385 = */ atspre_fprint_string (arg0, ATSstrcst("HIEsizeof(")) ;
/* tmp386 = */ ATS_2d0_2e2_2e10_2src_2ats_hiexp_2esats__fprint_hityp (arg0, tmp384) ;
/* tmp154 = */ atspre_fprint_string (arg0, ATSstrcst(")")) ;
break ;

/* branch: __ats_lab_73 */
__ats_lab_73_0:
if (((ats_sum_ptr_type)tmp155)->tag != 42) { goto __ats_lab_74_0 ; }
__ats_lab_73_1:
/* tmp154 = */ atspre_fprint_string (arg0, ATSstrcst("HIEstring(...)")) ;
break ;

/* branch: __ats_lab_74 */
__ats_lab_74_0:
if (((ats_sum_ptr_type)tmp155)->tag != 43) { goto __ats_lab_75_0 ; }
__ats_lab_74_1:
tmp387 = ats_caselptrlab_mac(anairiats_sum_1, tmp155, atslab_0) ;
tmp388 = ats_caselptrlab_mac(anairiats_sum_1, tmp155, atslab_1) ;
/* tmp389 = */ atspre_fprint_string (arg0, ATSstrcst("HIEtmpcst(")) ;
/* tmp390 = */ ATS_2d0_2e2_2e10_2src_2ats_dynexp2_2esats__fprint_d2cst (arg0, tmp387) ;
/* tmp391 = */ atspre_fprint_string (arg0, ATSstrcst("; ")) ;
/* tmp392 = */ ATS_2d0_2e2_2e10_2src_2ats_hiexp_2esats__fprint_hityplstlst (arg0, tmp388) ;
/* tmp154 = */ atspre_fprint_string (arg0, ATSstrcst(")")) ;
break ;

/* branch: __ats_lab_75 */
__ats_lab_75_0:
if (((ats_sum_ptr_type)tmp155)->tag != 44) { goto __ats_lab_76_0 ; }
__ats_lab_75_1:
tmp393 = ats_caselptrlab_mac(anairiats_sum_1, tmp155, atslab_0) ;
tmp394 = ats_caselptrlab_mac(anairiats_sum_1, tmp155, atslab_1) ;
/* tmp395 = */ atspre_fprint_string (arg0, ATSstrcst("HIEtmpvar(")) ;
/* tmp396 = */ ATS_2d0_2e2_2e10_2src_2ats_dynexp2_2esats__fprint_d2var (arg0, tmp393) ;
/* tmp397 = */ atspre_fprint_string (arg0, ATSstrcst("; ")) ;
/* tmp398 = */ ATS_2d0_2e2_2e10_2src_2ats_hiexp_2esats__fprint_hityplstlst (arg0, tmp394) ;
/* tmp154 = */ atspre_fprint_string (arg0, ATSstrcst(")")) ;
break ;

/* branch: __ats_lab_76 */
__ats_lab_76_0:
if (((ats_sum_ptr_type)tmp155)->tag != 45) { goto __ats_lab_77_0 ; }
__ats_lab_76_1:
/* tmp154 = */ atspre_fprint_string (arg0, ATSstrcst("HIEtop()")) ;
break ;

/* branch: __ats_lab_77 */
__ats_lab_77_0:
if (((ats_sum_ptr_type)tmp155)->tag != 46) { goto __ats_lab_78_0 ; }
__ats_lab_77_1:
/* tmp154 = */ atspre_fprint_string (arg0, ATSstrcst("HIEtrywith(...)")) ;
break ;

/* branch: __ats_lab_78 */
__ats_lab_78_0:
// if (((ats_sum_ptr_type)tmp155)->tag != 47) { ats_deadcode_failure_handle () ; }
__ats_lab_78_1:
tmp399 = ats_caselptrlab_mac(anairiats_sum_4, tmp155, atslab_0) ;
/* tmp400 = */ atspre_fprint_string (arg0, ATSstrcst("HIEvar(")) ;
/* tmp401 = */ ATS_2d0_2e2_2e10_2src_2ats_dynexp2_2esats__fprint_d2var (arg0, tmp399) ;
/* tmp154 = */ atspre_fprint_string (arg0, ATSstrcst(")")) ;
break ;
} while (0) ;
return /* (tmp154) */ ;
} /* end of [ATS_2d0_2e2_2e10_2src_2ats_hiexp_2esats__fprint_hiexp] */

/*
// /home/hwxi/research/Anairiats/src/ats_hiexp_print.dats: 17004(line=557, offs=23) -- 17041(line=557, offs=60)
*/
ATSglobaldec()
ats_void_type
ATS_2d0_2e2_2e10_2src_2ats_hiexp_2esats__print_hiexp (ats_ptr_type arg0) {
/* local vardec */
// ATSlocal_void (tmp402) ;
ATSlocal (ats_ptr_type, tmp403) ;
ATSlocal (ats_ptr_type, tmp404) ;
// ATSlocal_void (tmp405) ;

__ats_lab_ATS_2d0_2e2_2e10_2src_2ats_hiexp_2esats__print_hiexp:
tmp403 = atspre_stdout_get () ;
tmp404 = ats_selsin_mac(tmp403, atslab_1) ;
/* tmp405 = */ ATS_2d0_2e2_2e10_2src_2ats_hiexp_2esats__fprint_hiexp (tmp404, arg0) ;
/* tmp402 = */ atspre_stdout_view_set () ;
return /* (tmp402) */ ;
} /* end of [ATS_2d0_2e2_2e10_2src_2ats_hiexp_2esats__print_hiexp] */

/*
// /home/hwxi/research/Anairiats/src/ats_hiexp_print.dats: 17064(line=558, offs=23) -- 17101(line=558, offs=60)
*/
ATSglobaldec()
ats_void_type
ATS_2d0_2e2_2e10_2src_2ats_hiexp_2esats__prerr_hiexp (ats_ptr_type arg0) {
/* local vardec */
// ATSlocal_void (tmp406) ;
ATSlocal (ats_ptr_type, tmp407) ;
ATSlocal (ats_ptr_type, tmp408) ;
// ATSlocal_void (tmp409) ;

__ats_lab_ATS_2d0_2e2_2e10_2src_2ats_hiexp_2esats__prerr_hiexp:
tmp407 = atspre_stderr_get () ;
tmp408 = ats_selsin_mac(tmp407, atslab_1) ;
/* tmp409 = */ ATS_2d0_2e2_2e10_2src_2ats_hiexp_2esats__fprint_hiexp (tmp408, arg0) ;
/* tmp406 = */ atspre_stderr_view_set () ;
return /* (tmp406) */ ;
} /* end of [ATS_2d0_2e2_2e10_2src_2ats_hiexp_2esats__prerr_hiexp] */

/*
// /home/hwxi/research/Anairiats/src/ats_hiexp_print.dats: 17150(line=563, offs=17) -- 17226(line=564, offs=60)
*/
ATSglobaldec()
ats_void_type
ATS_2d0_2e2_2e10_2src_2ats_hiexp_2esats__fprint_hiexplst (ats_ref_type arg0, ats_ptr_type arg1) {
/* local vardec */
// ATSlocal_void (tmp410) ;

__ats_lab_ATS_2d0_2e2_2e10_2src_2ats_hiexp_2esats__fprint_hiexplst:
/* tmp410 = */ ATS_2d0_2e2_2e10_2src_2ats_list_2esats__fprintlst (arg0, arg1, ATSstrcst(", "), &ATS_2d0_2e2_2e10_2src_2ats_hiexp_2esats__fprint_hiexp) ;
return /* (tmp410) */ ;
} /* end of [ATS_2d0_2e2_2e10_2src_2ats_hiexp_2esats__fprint_hiexplst] */

/*
// /home/hwxi/research/Anairiats/src/ats_hiexp_print.dats: 17281(line=568, offs=16) -- 17323(line=568, offs=58)
*/
ATSglobaldec()
ats_void_type
ATS_2d0_2e2_2e10_2src_2ats_hiexp_2esats__print_hiexplst (ats_ptr_type arg0) {
/* local vardec */
// ATSlocal_void (tmp411) ;
ATSlocal (ats_ptr_type, tmp412) ;
ATSlocal (ats_ptr_type, tmp413) ;
// ATSlocal_void (tmp414) ;

__ats_lab_ATS_2d0_2e2_2e10_2src_2ats_hiexp_2esats__print_hiexplst:
tmp412 = atspre_stdout_get () ;
tmp413 = ats_selsin_mac(tmp412, atslab_1) ;
/* tmp414 = */ ATS_2d0_2e2_2e10_2src_2ats_hiexp_2esats__fprint_hiexplst (tmp413, arg0) ;
/* tmp411 = */ atspre_stdout_view_set () ;
return /* (tmp411) */ ;
} /* end of [ATS_2d0_2e2_2e10_2src_2ats_hiexp_2esats__print_hiexplst] */

/*
// /home/hwxi/research/Anairiats/src/ats_hiexp_print.dats: 17349(line=570, offs=16) -- 17391(line=570, offs=58)
*/
ATSglobaldec()
ats_void_type
ATS_2d0_2e2_2e10_2src_2ats_hiexp_2esats__prerr_hiexplst (ats_ptr_type arg0) {
/* local vardec */
// ATSlocal_void (tmp415) ;
ATSlocal (ats_ptr_type, tmp416) ;
ATSlocal (ats_ptr_type, tmp417) ;
// ATSlocal_void (tmp418) ;

__ats_lab_ATS_2d0_2e2_2e10_2src_2ats_hiexp_2esats__prerr_hiexplst:
tmp416 = atspre_stderr_get () ;
tmp417 = ats_selsin_mac(tmp416, atslab_1) ;
/* tmp418 = */ ATS_2d0_2e2_2e10_2src_2ats_hiexp_2esats__fprint_hiexplst (tmp417, arg0) ;
/* tmp415 = */ atspre_stderr_view_set () ;
return /* (tmp415) */ ;
} /* end of [ATS_2d0_2e2_2e10_2src_2ats_hiexp_2esats__prerr_hiexplst] */

/*
// /home/hwxi/research/Anairiats/src/ats_hiexp_print.dats: 17443(line=575, offs=20) -- 17527(line=576, offs=67)
*/
ATSglobaldec()
ats_void_type
ATS_2d0_2e2_2e10_2src_2ats_hiexp_2esats__fprint_hiexplstlst (ats_ref_type arg0, ats_ptr_type arg1) {
/* local vardec */
// ATSlocal_void (tmp419) ;

__ats_lab_ATS_2d0_2e2_2e10_2src_2ats_hiexp_2esats__fprint_hiexplstlst:
/* tmp419 = */ ATS_2d0_2e2_2e10_2src_2ats_list_2esats__fprintlst (arg0, arg1, ATSstrcst("; "), &ATS_2d0_2e2_2e10_2src_2ats_hiexp_2esats__fprint_hiexplst) ;
return /* (tmp419) */ ;
} /* end of [ATS_2d0_2e2_2e10_2src_2ats_hiexp_2esats__fprint_hiexplstlst] */

/*
// /home/hwxi/research/Anairiats/src/ats_hiexp_print.dats: 17626(line=582, offs=7) -- 18023(line=593, offs=30)
*/
ATSstaticdec()
ats_void_type
aux_23 (ats_ref_type arg0, ats_int_type arg1, ats_ptr_type arg2) {
/* local vardec */
// ATSlocal_void (tmp421) ;
ATSlocal (ats_ptr_type, tmp422) ;
ATSlocal (ats_ptr_type, tmp423) ;
ATSlocal (ats_ptr_type, tmp424) ;
// ATSlocal_void (tmp425) ;
ATSlocal (ats_bool_type, tmp426) ;
// ATSlocal_void (tmp427) ;
// ATSlocal_void (tmp428) ;
// ATSlocal_void (tmp429) ;
ATSlocal (ats_int_type, tmp430) ;

__ats_lab_aux_23:
do {
/* branch: __ats_lab_79 */
__ats_lab_79_0:
if (arg2 == (ats_sum_ptr_type)0) { goto __ats_lab_80_0 ; }
__ats_lab_79_1:
tmp422 = ats_caselptrlab_mac(anairiats_sum_17, arg2, atslab_0) ;
tmp423 = ats_caselptrlab_mac(anairiats_sum_17, arg2, atslab_1) ;
tmp424 = ats_caselptrlab_mac(anairiats_sum_17, arg2, atslab_2) ;
tmp426 = atspre_gt_int_int (arg1, 0) ;
if (tmp426) {
/* tmp425 = */ atspre_fprint_string (arg0, ATSstrcst(", ")) ;
} else {
/* empty */
} /* end of [if] */
/* tmp427 = */ ATS_2d0_2e2_2e10_2src_2ats_label_2esats__fprint_label (arg0, tmp422) ;
/* tmp428 = */ atspre_fprint_string (arg0, ATSstrcst("= ")) ;
/* tmp429 = */ ATS_2d0_2e2_2e10_2src_2ats_hiexp_2esats__fprint_hiexp (arg0, tmp423) ;
tmp430 = atspre_add_int_int (arg1, 1) ;
arg0 = arg0 ;
arg1 = tmp430 ;
arg2 = tmp424 ;
goto __ats_lab_aux_23 ; // tail call
break ;

/* branch: __ats_lab_80 */
__ats_lab_80_0:
// if (arg2 != (ats_sum_ptr_type)0) { ats_deadcode_failure_handle () ; }
__ats_lab_80_1:
break ;
} while (0) ;
return /* (tmp421) */ ;
} /* end of [aux_23] */

/*
// /home/hwxi/research/Anairiats/src/ats_hiexp_print.dats: 17595(line=581, offs=3) -- 18098(line=597, offs=4)
*/
ATSglobaldec()
ats_void_type
ATS_2d0_2e2_2e10_2src_2ats_hiexp_2esats__fprint_labhiexplst (ats_ref_type arg0, ats_ptr_type arg1) {
/* local vardec */
// ATSlocal_void (tmp420) ;

__ats_lab_ATS_2d0_2e2_2e10_2src_2ats_hiexp_2esats__fprint_labhiexplst:
/* tmp420 = */ aux_23 (arg0, 0, arg1) ;
return /* (tmp420) */ ;
} /* end of [ATS_2d0_2e2_2e10_2src_2ats_hiexp_2esats__fprint_labhiexplst] */

/*
// /home/hwxi/research/Anairiats/src/ats_hiexp_print.dats: 18175(line=602, offs=14) -- 18538(line=612, offs=4)
*/
ATSglobaldec()
ats_void_type
ATS_2d0_2e2_2e10_2src_2ats_hiexp_2esats__fprint_hilab (ats_ref_type arg0, ats_ptr_type arg1) {
/* local vardec */
// ATSlocal_void (tmp431) ;
ATSlocal (ats_ptr_type, tmp432) ;
ATSlocal (ats_ptr_type, tmp433) ;
// ATSlocal_void (tmp434) ;
// ATSlocal_void (tmp435) ;
ATSlocal (ats_ptr_type, tmp436) ;
// ATSlocal_void (tmp437) ;
// ATSlocal_void (tmp438) ;

__ats_lab_ATS_2d0_2e2_2e10_2src_2ats_hiexp_2esats__fprint_hilab:
tmp432 = ats_selbox_mac(ats_castptr_mac(anairiats_rec_18, arg1), atslab_hilab_node) ;
do {
/* branch: __ats_lab_81 */
__ats_lab_81_0:
if (((ats_sum_ptr_type)tmp432)->tag != 0) { goto __ats_lab_82_0 ; }
__ats_lab_81_1:
tmp433 = ats_caselptrlab_mac(anairiats_sum_1, tmp432, atslab_0) ;
/* tmp434 = */ atspre_fprint_string (arg0, ATSstrcst("HILlab(")) ;
/* tmp435 = */ ATS_2d0_2e2_2e10_2src_2ats_label_2esats__fprint_label (arg0, tmp433) ;
/* tmp431 = */ atspre_fprint_string (arg0, ATSstrcst(")")) ;
break ;

/* branch: __ats_lab_82 */
__ats_lab_82_0:
// if (((ats_sum_ptr_type)tmp432)->tag != 1) { ats_deadcode_failure_handle () ; }
__ats_lab_82_1:
tmp436 = ats_caselptrlab_mac(anairiats_sum_1, tmp432, atslab_0) ;
/* tmp437 = */ atspre_fprint_string (arg0, ATSstrcst("HILind(")) ;
/* tmp438 = */ ATS_2d0_2e2_2e10_2src_2ats_hiexp_2esats__fprint_hiexplstlst (arg0, tmp436) ;
/* tmp431 = */ atspre_fprint_string (arg0, ATSstrcst(")")) ;
break ;
} while (0) ;
return /* (tmp431) */ ;
} /* end of [ATS_2d0_2e2_2e10_2src_2ats_hiexp_2esats__fprint_hilab] */

/*
// /home/hwxi/research/Anairiats/src/ats_hiexp_print.dats: 18591(line=615, offs=17) -- 18667(line=616, offs=60)
*/
ATSglobaldec()
ats_void_type
ATS_2d0_2e2_2e10_2src_2ats_hiexp_2esats__fprint_hilablst (ats_ref_type arg0, ats_ptr_type arg1) {
/* local vardec */
// ATSlocal_void (tmp439) ;

__ats_lab_ATS_2d0_2e2_2e10_2src_2ats_hiexp_2esats__fprint_hilablst:
/* tmp439 = */ ATS_2d0_2e2_2e10_2src_2ats_list_2esats__fprintlst (arg0, arg1, ATSstrcst(", "), &ATS_2d0_2e2_2e10_2src_2ats_hiexp_2esats__fprint_hilab) ;
return /* (tmp439) */ ;
} /* end of [ATS_2d0_2e2_2e10_2src_2ats_hiexp_2esats__fprint_hilablst] */

/*
// /home/hwxi/research/Anairiats/src/ats_hiexp_print.dats: 18742(line=622, offs=15) -- 18945(line=627, offs=4)
*/
ATSglobaldec()
ats_void_type
ATS_2d0_2e2_2e10_2src_2ats_hiexp_2esats__fprint_vartyp (ats_ref_type arg0, ats_ptr_type arg1) {
/* local vardec */
// ATSlocal_void (tmp440) ;
// ATSlocal_void (tmp441) ;
ATSlocal (ats_ptr_type, tmp442) ;
// ATSlocal_void (tmp443) ;
// ATSlocal_void (tmp444) ;
ATSlocal (ats_ptr_type, tmp445) ;
ATSlocal (ats_ptr_type, tmp446) ;

__ats_lab_ATS_2d0_2e2_2e10_2src_2ats_hiexp_2esats__fprint_vartyp:
tmp442 = ATS_2d0_2e2_2e10_2src_2ats_hiexp_2esats__vartyp_get_var (arg1) ;
/* tmp441 = */ ATS_2d0_2e2_2e10_2src_2ats_dynexp2_2esats__fprint_d2var (arg0, tmp442) ;
/* tmp443 = */ atspre_fprint_string (arg0, ATSstrcst("(")) ;
tmp446 = ATS_2d0_2e2_2e10_2src_2ats_hiexp_2esats__vartyp_get_typ (arg1) ;
tmp445 = ATS_2d0_2e2_2e10_2src_2ats_hiexp_2esats__hityp_decode (tmp446) ;
/* tmp444 = */ ATS_2d0_2e2_2e10_2src_2ats_hiexp_2esats__fprint_hityp (arg0, tmp445) ;
/* tmp440 = */ atspre_fprint_string (arg0, ATSstrcst(")")) ;
return /* (tmp440) */ ;
} /* end of [ATS_2d0_2e2_2e10_2src_2ats_hiexp_2esats__fprint_vartyp] */

/*
// /home/hwxi/research/Anairiats/src/ats_hiexp_print.dats: 18996(line=629, offs=24) -- 19034(line=629, offs=62)
*/
ATSglobaldec()
ats_void_type
ATS_2d0_2e2_2e10_2src_2ats_hiexp_2esats__print_vartyp (ats_ptr_type arg0) {
/* local vardec */
// ATSlocal_void (tmp447) ;
ATSlocal (ats_ptr_type, tmp448) ;
ATSlocal (ats_ptr_type, tmp449) ;
// ATSlocal_void (tmp450) ;

__ats_lab_ATS_2d0_2e2_2e10_2src_2ats_hiexp_2esats__print_vartyp:
tmp448 = atspre_stdout_get () ;
tmp449 = ats_selsin_mac(tmp448, atslab_1) ;
/* tmp450 = */ ATS_2d0_2e2_2e10_2src_2ats_hiexp_2esats__fprint_vartyp (tmp449, arg0) ;
/* tmp447 = */ atspre_stdout_view_set () ;
return /* (tmp447) */ ;
} /* end of [ATS_2d0_2e2_2e10_2src_2ats_hiexp_2esats__print_vartyp] */

/*
// /home/hwxi/research/Anairiats/src/ats_hiexp_print.dats: 19058(line=630, offs=24) -- 19096(line=630, offs=62)
*/
ATSglobaldec()
ats_void_type
ATS_2d0_2e2_2e10_2src_2ats_hiexp_2esats__prerr_vartyp (ats_ptr_type arg0) {
/* local vardec */
// ATSlocal_void (tmp451) ;
ATSlocal (ats_ptr_type, tmp452) ;
ATSlocal (ats_ptr_type, tmp453) ;
// ATSlocal_void (tmp454) ;

__ats_lab_ATS_2d0_2e2_2e10_2src_2ats_hiexp_2esats__prerr_vartyp:
tmp452 = atspre_stderr_get () ;
tmp453 = ats_selsin_mac(tmp452, atslab_1) ;
/* tmp454 = */ ATS_2d0_2e2_2e10_2src_2ats_hiexp_2esats__fprint_vartyp (tmp453, arg0) ;
/* tmp451 = */ atspre_stderr_view_set () ;
return /* (tmp451) */ ;
} /* end of [ATS_2d0_2e2_2e10_2src_2ats_hiexp_2esats__prerr_vartyp] */

/* static load function */

extern ats_void_type ATS_2d0_2e2_2e10_2src_2ats_filename_2esats__staload (void) ;
extern ats_void_type ATS_2d0_2e2_2e10_2src_2ats_intinf_2esats__staload (void) ;
extern ats_void_type ATS_2d0_2e2_2e10_2src_2ats_label_2esats__staload (void) ;
extern ats_void_type ATS_2d0_2e2_2e10_2src_2ats_list_2esats__staload (void) ;
extern ats_void_type ATS_2d0_2e2_2e10_2src_2ats_staexp2_2esats__staload (void) ;
extern ats_void_type ATS_2d0_2e2_2e10_2src_2ats_dynexp2_2esats__staload (void) ;
extern ats_void_type ATS_2d0_2e2_2e10_2src_2ats_hiexp_2esats__staload (void) ;

ats_void_type
ATS_2d0_2e2_2e10_2src_2ats_hiexp_print_2edats__staload () {
static int ATS_2d0_2e2_2e10_2src_2ats_hiexp_print_2edats__staload_flag = 0 ;
if (ATS_2d0_2e2_2e10_2src_2ats_hiexp_print_2edats__staload_flag) return ;
ATS_2d0_2e2_2e10_2src_2ats_hiexp_print_2edats__staload_flag = 1 ;

ATS_2d0_2e2_2e10_2src_2ats_filename_2esats__staload () ;
ATS_2d0_2e2_2e10_2src_2ats_intinf_2esats__staload () ;
ATS_2d0_2e2_2e10_2src_2ats_label_2esats__staload () ;
ATS_2d0_2e2_2e10_2src_2ats_list_2esats__staload () ;
ATS_2d0_2e2_2e10_2src_2ats_staexp2_2esats__staload () ;
ATS_2d0_2e2_2e10_2src_2ats_dynexp2_2esats__staload () ;
ATS_2d0_2e2_2e10_2src_2ats_hiexp_2esats__staload () ;

return ;
} /* staload function */

/* dynamic load function */

// dynload flag declaration
extern ats_int_type ATS_2d0_2e2_2e10_2src_2ats_hiexp_print_2edats__dynload_flag ;

ats_void_type
ATS_2d0_2e2_2e10_2src_2ats_hiexp_print_2edats__dynload () {
ATS_2d0_2e2_2e10_2src_2ats_hiexp_print_2edats__dynload_flag = 1 ;
ATS_2d0_2e2_2e10_2src_2ats_hiexp_print_2edats__staload () ;

#ifdef _ATS_PROOFCHECK
ATS_2d0_2e2_2e10_2prelude_2basics_dyn_2esats__file_mode_lte_w_w_prfck () ;
#endif /* _ATS_PROOFCHECK */

/* marking static variables for GC */

/* marking external values for GC */

/* code for dynamic loading */
return ;
} /* end of [dynload function] */

/* external codes at mid */
/* external codes at bot */

/* ****** ****** */

/* end of [/home/hwxi/research/Anairiats/bootstrap1/ats_hiexp_print_dats.c] */
