/*
**
** The C code is generated by ATS/Anairiats
** The compilation time is: 2013-8-29: 22h:22m
**
*/

/* include some .h files */
#ifndef _ATS_HEADER_NONE
#include "ats_config.h"
#include "ats_basics.h"
#include "ats_types.h"
#include "ats_exception.h"
#include "ats_memory.h"
#endif /* _ATS_HEADER_NONE */

/* include some .cats files */
#ifndef _ATS_PRELUDE_NONE
#include "prelude/CATS/basics.cats"
#include "prelude/CATS/bool.cats"
#include "prelude/CATS/byte.cats"
#include "prelude/CATS/char.cats"
#include "prelude/CATS/float.cats"
#include "prelude/CATS/integer.cats"
#include "prelude/CATS/integer_fixed.cats"
#include "prelude/CATS/integer_ptr.cats"
#include "prelude/CATS/lazy.cats"
#include "prelude/CATS/lazy_vt.cats"
#include "prelude/CATS/pointer.cats"
#include "prelude/CATS/printf.cats"
#include "prelude/CATS/reference.cats"
#include "prelude/CATS/sizetype.cats"
#include "prelude/CATS/string.cats"
#include "prelude/CATS/array.cats"
#include "prelude/CATS/list.cats"
#include "prelude/CATS/matrix.cats"
#include "prelude/CATS/option.cats"
#endif /* _ATS_PRELUDE_NONE */
/* prologues from statically loaded files */
/* external codes at top */
/* type definitions */
typedef struct {
ats_ptr_type atslab_s0rtq_loc ;
ats_ptr_type atslab_s0rtq_node ;
} anairiats_rec_0 ;

typedef struct {
ats_ptr_type atslab_e1xp_loc ;
ats_ptr_type atslab_e1xp_node ;
} anairiats_rec_1 ;

typedef struct {
int tag ;
ats_ptr_type atslab_0 ;
ats_ptr_type atslab_1 ;
ats_ptr_type atslab_2 ;
} anairiats_sum_2 ;

typedef struct {
int tag ;
ats_char_type atslab_0 ;
} anairiats_sum_3 ;

typedef struct {
int tag ;
ats_ptr_type atslab_0 ;
} anairiats_sum_4 ;

typedef struct {
int tag ;
ats_ptr_type atslab_0 ;
ats_int_type atslab_1 ;
} anairiats_sum_5 ;

typedef struct {
int tag ;
ats_int_type atslab_0 ;
} anairiats_sum_6 ;

typedef struct {
ats_ptr_type atslab_s1rt_loc ;
ats_ptr_type atslab_s1rt_node ;
} anairiats_rec_7 ;

typedef struct {
int tag ;
ats_ptr_type atslab_0 ;
ats_ptr_type atslab_1 ;
} anairiats_sum_8 ;

typedef struct {
ats_ptr_type atslab_0 ;
ats_ptr_type atslab_1 ;
} anairiats_sum_9 ;

typedef struct {
ats_ptr_type atslab_s1rtpol_loc ;
ats_ptr_type atslab_s1rtpol_srt ;
ats_int_type atslab_s1rtpol_pol ;
} anairiats_rec_10 ;

typedef struct {
ats_ptr_type atslab_d1atarg_loc ;
ats_ptr_type atslab_d1atarg_node ;
} anairiats_rec_11 ;

typedef struct {
ats_ptr_type atslab_s1arg_loc ;
ats_ptr_type atslab_s1arg_sym ;
ats_ptr_type atslab_s1arg_srt ;
} anairiats_rec_12 ;

typedef struct {
ats_ptr_type atslab_sp1at_loc ;
ats_ptr_type atslab_sp1at_node ;
} anairiats_rec_13 ;

typedef struct {
ats_ptr_type atslab_0 ;
ats_ptr_type atslab_1 ;
ats_ptr_type atslab_2 ;
} anairiats_sum_14 ;

typedef struct {
ats_ptr_type atslab_s1exp_loc ;
ats_ptr_type atslab_s1exp_node ;
} anairiats_rec_15 ;

typedef struct {
int tag ;
ats_int_type atslab_0 ;
ats_ptr_type atslab_1 ;
ats_ptr_type atslab_2 ;
} anairiats_sum_16 ;

typedef struct {
int tag ;
ats_ptr_type atslab_0 ;
ats_int_type atslab_1 ;
ats_int_type atslab_2 ;
ats_ptr_type atslab_3 ;
} anairiats_sum_17 ;

typedef struct {
int tag ;
ats_int_type atslab_0 ;
ats_ptr_type atslab_1 ;
} anairiats_sum_18 ;

typedef struct {
ats_ptr_type atslab_s1exparg_loc ;
ats_ptr_type atslab_s1exparg_node ;
} anairiats_rec_19 ;

typedef struct {
ats_ptr_type atslab_s1rtext_loc ;
ats_ptr_type atslab_s1rtext_node ;
} anairiats_rec_20 ;

typedef struct {
ats_ptr_type atslab_s1qua_loc ;
ats_ptr_type atslab_s1qua_node ;
} anairiats_rec_21 ;

/* external typedefs */
/* external dynamic constructor declarations */
ATSextern_val(ats_sum_type, ATS_2d0_2e2_2e10_2prelude_2basics_sta_2esats__list_cons) ;
ATSextern_val(ats_sum_type, ATS_2d0_2e2_2e10_2prelude_2basics_sta_2esats__list_nil) ;
ATSextern_val(ats_sum_type, ATS_2d0_2e2_2e10_2src_2ats_syntax_2esats__S0RTQnone) ;
ATSextern_val(ats_sum_type, ATS_2d0_2e2_2e10_2src_2ats_staexp1_2esats__E1XPapp) ;
ATSextern_val(ats_sum_type, ATS_2d0_2e2_2e10_2src_2ats_staexp1_2esats__E1XPchar) ;
ATSextern_val(ats_sum_type, ATS_2d0_2e2_2e10_2src_2ats_staexp1_2esats__E1XPfloat) ;
ATSextern_val(ats_sum_type, ATS_2d0_2e2_2e10_2src_2ats_staexp1_2esats__E1XPide) ;
ATSextern_val(ats_sum_type, ATS_2d0_2e2_2e10_2src_2ats_staexp1_2esats__E1XPint) ;
ATSextern_val(ats_sum_type, ATS_2d0_2e2_2e10_2src_2ats_staexp1_2esats__E1XPlist) ;
ATSextern_val(ats_sum_type, ATS_2d0_2e2_2e10_2src_2ats_staexp1_2esats__E1XPstring) ;
ATSextern_val(ats_sum_type, ATS_2d0_2e2_2e10_2src_2ats_staexp1_2esats__E1XPundef) ;
ATSextern_val(ats_sum_type, ATS_2d0_2e2_2e10_2src_2ats_staexp1_2esats__E1XPcstsp) ;
ATSextern_val(ats_sum_type, ATS_2d0_2e2_2e10_2src_2ats_staexp1_2esats__E1XPnone) ;
ATSextern_val(ats_sum_type, ATS_2d0_2e2_2e10_2src_2ats_staexp1_2esats__V1ALint) ;
ATSextern_val(ats_sum_type, ATS_2d0_2e2_2e10_2src_2ats_staexp1_2esats__S1RTapp) ;
ATSextern_val(ats_sum_type, ATS_2d0_2e2_2e10_2src_2ats_staexp1_2esats__S1RTlist) ;
ATSextern_val(ats_sum_type, ATS_2d0_2e2_2e10_2src_2ats_staexp1_2esats__S1RTqid) ;
ATSextern_val(ats_sum_type, ATS_2d0_2e2_2e10_2src_2ats_staexp1_2esats__S1RTtup) ;
ATSextern_val(ats_sum_type, ATS_2d0_2e2_2e10_2src_2ats_staexp1_2esats__D1ATARGsrt) ;
ATSextern_val(ats_sum_type, ATS_2d0_2e2_2e10_2src_2ats_staexp1_2esats__D1ATARGidsrt) ;
ATSextern_val(ats_sum_type, ATS_2d0_2e2_2e10_2src_2ats_staexp1_2esats__SP1Tcon) ;
ATSextern_val(ats_sum_type, ATS_2d0_2e2_2e10_2src_2ats_staexp1_2esats__S1Qprop) ;
ATSextern_val(ats_sum_type, ATS_2d0_2e2_2e10_2src_2ats_staexp1_2esats__S1Qvars) ;
ATSextern_val(ats_sum_type, ATS_2d0_2e2_2e10_2src_2ats_staexp1_2esats__S1TEsrt) ;
ATSextern_val(ats_sum_type, ATS_2d0_2e2_2e10_2src_2ats_staexp1_2esats__S1TEsub) ;
ATSextern_val(ats_sum_type, ATS_2d0_2e2_2e10_2src_2ats_staexp1_2esats__WTHS1EXPLSTnil) ;
ATSextern_val(ats_sum_type, ATS_2d0_2e2_2e10_2src_2ats_staexp1_2esats__WTHS1EXPLSTcons_some) ;
ATSextern_val(ats_sum_type, ATS_2d0_2e2_2e10_2src_2ats_staexp1_2esats__WTHS1EXPLSTcons_none) ;
ATSextern_val(ats_sum_type, ATS_2d0_2e2_2e10_2src_2ats_staexp1_2esats__S1Eann) ;
ATSextern_val(ats_sum_type, ATS_2d0_2e2_2e10_2src_2ats_staexp1_2esats__S1Eany) ;
ATSextern_val(ats_sum_type, ATS_2d0_2e2_2e10_2src_2ats_staexp1_2esats__S1Eapp) ;
ATSextern_val(ats_sum_type, ATS_2d0_2e2_2e10_2src_2ats_staexp1_2esats__S1Echar) ;
ATSextern_val(ats_sum_type, ATS_2d0_2e2_2e10_2src_2ats_staexp1_2esats__S1Eexi) ;
ATSextern_val(ats_sum_type, ATS_2d0_2e2_2e10_2src_2ats_staexp1_2esats__S1Eextype) ;
ATSextern_val(ats_sum_type, ATS_2d0_2e2_2e10_2src_2ats_staexp1_2esats__S1Eimp) ;
ATSextern_val(ats_sum_type, ATS_2d0_2e2_2e10_2src_2ats_staexp1_2esats__S1Eint) ;
ATSextern_val(ats_sum_type, ATS_2d0_2e2_2e10_2src_2ats_staexp1_2esats__S1Einvar) ;
ATSextern_val(ats_sum_type, ATS_2d0_2e2_2e10_2src_2ats_staexp1_2esats__S1Elam) ;
ATSextern_val(ats_sum_type, ATS_2d0_2e2_2e10_2src_2ats_staexp1_2esats__S1Elist) ;
ATSextern_val(ats_sum_type, ATS_2d0_2e2_2e10_2src_2ats_staexp1_2esats__S1Eqid) ;
ATSextern_val(ats_sum_type, ATS_2d0_2e2_2e10_2src_2ats_staexp1_2esats__S1Eread) ;
ATSextern_val(ats_sum_type, ATS_2d0_2e2_2e10_2src_2ats_staexp1_2esats__S1Etop) ;
ATSextern_val(ats_sum_type, ATS_2d0_2e2_2e10_2src_2ats_staexp1_2esats__S1Etrans) ;
ATSextern_val(ats_sum_type, ATS_2d0_2e2_2e10_2src_2ats_staexp1_2esats__S1Etyarr) ;
ATSextern_val(ats_sum_type, ATS_2d0_2e2_2e10_2src_2ats_staexp1_2esats__S1Etyrec) ;
ATSextern_val(ats_sum_type, ATS_2d0_2e2_2e10_2src_2ats_staexp1_2esats__S1Etyrec_ext) ;
ATSextern_val(ats_sum_type, ATS_2d0_2e2_2e10_2src_2ats_staexp1_2esats__S1Etytup) ;
ATSextern_val(ats_sum_type, ATS_2d0_2e2_2e10_2src_2ats_staexp1_2esats__S1Etytup2) ;
ATSextern_val(ats_sum_type, ATS_2d0_2e2_2e10_2src_2ats_staexp1_2esats__S1Euni) ;
ATSextern_val(ats_sum_type, ATS_2d0_2e2_2e10_2src_2ats_staexp1_2esats__S1Eunion) ;
ATSextern_val(ats_sum_type, ATS_2d0_2e2_2e10_2src_2ats_staexp1_2esats__S1EXPARGone) ;
ATSextern_val(ats_sum_type, ATS_2d0_2e2_2e10_2src_2ats_staexp1_2esats__S1EXPARGall) ;
ATSextern_val(ats_sum_type, ATS_2d0_2e2_2e10_2src_2ats_staexp1_2esats__S1EXPARGseq) ;

/* external dynamic constant declarations */
ATSextern_fun(ats_void_type, atspre_prerr_newline) () ;
ATSextern_fun(ats_void_type, atspre_prerr_string) (ats_ptr_type) ;
ATSextern_fun(ats_varet_type, ATS_2d0_2e2_2e10_2src_2ats_error_2esats__abort) () ;
ATSextern_val(ats_ptr_type, ATS_2d0_2e2_2e10_2src_2ats_symbol_2esats__symbol_MINUSGT) ;
ATSextern_fun(ats_bool_type, ATS_2d0_2e2_2e10_2src_2ats_symbol_2esats__eq_symbol_symbol) (ats_ptr_type, ats_ptr_type) ;
ATSextern_val(ats_ptr_type, ATS_2d0_2e2_2e10_2src_2ats_location_2esats__location_dummy) ;
ATSextern_fun(ats_void_type, ATS_2d0_2e2_2e10_2src_2ats_location_2esats__prerr_location) (ats_ptr_type) ;
ATSextern_fun(ats_ptr_type, ATS_2d0_2e2_2e10_2src_2ats_list_2esats__list_append) (ats_ptr_type, ats_ptr_type) ;
ATSextern_fun(ats_int_type, ATS_2d0_2e2_2e10_2src_2ats_list_2esats__list_length) (ats_ptr_type) ;
ATSextern_fun(ats_ptr_type, s0rtq_none) () ;
ATSextern_fun(ats_ptr_type, s0taq_none) () ;
ATSextern_fun(ats_ptr_type, ATS_2d0_2e2_2e10_2src_2ats_staexp1_2esats__e1xp_int) (ats_ptr_type, ats_ptr_type) ;
ATSextern_fun(ats_ptr_type, ATS_2d0_2e2_2e10_2src_2ats_staexp1_2esats__s1rt_arrow) (ats_ptr_type) ;
ATSextern_fun(ats_ptr_type, ATS_2d0_2e2_2e10_2src_2ats_staexp1_2esats__s1exp_app) (ats_ptr_type, ats_ptr_type, ats_ptr_type, ats_ptr_type) ;
ATSextern_fun(ats_ptr_type, ATS_2d0_2e2_2e10_2src_2ats_staexp1_2esats__s1exp_char) (ats_ptr_type, ats_char_type) ;
ATSextern_fun(ats_ptr_type, ATS_2d0_2e2_2e10_2src_2ats_staexp1_2esats__s1exp_ide) (ats_ptr_type, ats_ptr_type) ;
ATSextern_fun(ats_ptr_type, ATS_2d0_2e2_2e10_2src_2ats_staexp1_2esats__s1exp_int) (ats_ptr_type, ats_ptr_type) ;
ATSextern_fun(ats_ptr_type, ATS_2d0_2e2_2e10_2src_2ats_staexp1_2esats__s1exp_list) (ats_ptr_type, ats_ptr_type) ;
ATSextern_fun(ats_bool_type, ATS_2d0_2e2_2e10_2src_2ats_staexp1_2esats__wths1explst_is_none) (ats_ptr_type) ;

/* external dynamic terminating constant declarations */
#ifdef _ATS_PROOFCHECK
#endif /* _ATS_PROOFCHECK */

/* sum constructor declarations */
/* exn constructor declarations */
/* global dynamic (non-functional) constant declarations */
ATSglobal(ats_ptr_type, ATS_2d0_2e2_2e10_2src_2ats_staexp1_2esats__v1al_true) ;
ATSglobal(ats_ptr_type, ATS_2d0_2e2_2e10_2src_2ats_staexp1_2esats__v1al_false) ;

/* internal function declarations */
static
ats_bool_type s0rtq_is_none_0 (ats_ptr_type arg0) ;
static
ats_ptr_type err_41 (ats_ptr_type arg0) ;
static
ats_ptr_type aux_59 (ats_ptr_type env0, ats_ptr_type arg0) ;
static
ats_clo_ptr_type aux_59_closure_make (ats_ptr_type env0) ;
static
ats_ptr_type aux_59_clofun (ats_clo_ptr_type cloptr, ats_ptr_type arg0) ;
static
ats_ptr_type aux_list_60 (ats_ptr_type env0, ats_ptr_type arg0) ;
static
ats_clo_ptr_type aux_list_60_closure_make (ats_ptr_type env0) ;
static
ats_ptr_type aux_list_60_clofun (ats_clo_ptr_type cloptr, ats_ptr_type arg0) ;
static
ats_ptr_type aux_63 (ats_ptr_type arg0, ats_ptr_type arg1) ;

/* partial value template declarations */
/* static temporary variable declarations */
ATSstatic (ats_ptr_type, statmp0) ;
ATSstatic (ats_ptr_type, statmp1) ;
ATSstatic (ats_ptr_type, statmp26) ;
ATSstatic (ats_ptr_type, statmp27) ;

/* external value variable declarations */

/* function implementations */

/*
// /home/hwxi/research/Anairiats/src/ats_staexp1.dats: 2069(line=66, offs=4) -- 2169(line=67, offs=63)
*/
ATSstaticdec()
ats_bool_type
s0rtq_is_none_0 (ats_ptr_type arg0) {
/* local vardec */
ATSlocal (ats_bool_type, tmp2) ;
ATSlocal (ats_ptr_type, tmp3) ;

__ats_lab_s0rtq_is_none_0:
tmp3 = ats_selbox_mac(ats_castptr_mac(anairiats_rec_0, arg0), atslab_s0rtq_node) ;
do {
/* branch: __ats_lab_0 */
__ats_lab_0_0:
if (((ats_sum_ptr_type)tmp3)->tag != 0) { goto __ats_lab_1_0 ; }
__ats_lab_0_1:
tmp2 = ats_true_bool ;
break ;

/* branch: __ats_lab_1 */
__ats_lab_1_0:
__ats_lab_1_1:
tmp2 = ats_false_bool ;
break ;
} while (0) ;
return (tmp2) ;
} /* end of [s0rtq_is_none_0] */

/*
// /home/hwxi/research/Anairiats/src/ats_staexp1.dats: 2211(line=72, offs=10) -- 2313(line=77, offs=2)
*/
ATSglobaldec()
ats_ptr_type
ATS_2d0_2e2_2e10_2src_2ats_staexp1_2esats__e1xp_app (ats_ptr_type arg0, ats_ptr_type arg1, ats_ptr_type arg2, ats_ptr_type arg3) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp4) ;
ATSlocal (ats_ptr_type, tmp5) ;

__ats_lab_ATS_2d0_2e2_2e10_2src_2ats_staexp1_2esats__e1xp_app:
tmp5 = ATS_MALLOC(sizeof(anairiats_sum_2)) ;
((ats_sum_ptr_type)tmp5)->tag = 0 ;
ats_selptrset_mac(anairiats_sum_2, tmp5, atslab_0, arg1) ;
ats_selptrset_mac(anairiats_sum_2, tmp5, atslab_1, arg2) ;
ats_selptrset_mac(anairiats_sum_2, tmp5, atslab_2, arg3) ;
tmp4 = ATS_MALLOC(sizeof(anairiats_rec_1)) ;
ats_selptrset_mac(anairiats_rec_1, tmp4, atslab_e1xp_loc, arg0) ;
ats_selptrset_mac(anairiats_rec_1, tmp4, atslab_e1xp_node, tmp5) ;

return (tmp4) ;
} /* end of [ATS_2d0_2e2_2e10_2src_2ats_staexp1_2esats__e1xp_app] */

/*
// /home/hwxi/research/Anairiats/src/ats_staexp1.dats: 2358(line=81, offs=3) -- 2414(line=83, offs=2)
*/
ATSglobaldec()
ats_ptr_type
ATS_2d0_2e2_2e10_2src_2ats_staexp1_2esats__e1xp_char (ats_ptr_type arg0, ats_char_type arg1) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp6) ;
ATSlocal (ats_ptr_type, tmp7) ;

__ats_lab_ATS_2d0_2e2_2e10_2src_2ats_staexp1_2esats__e1xp_char:
tmp7 = ATS_MALLOC(sizeof(anairiats_sum_3)) ;
((ats_sum_ptr_type)tmp7)->tag = 1 ;
ats_selptrset_mac(anairiats_sum_3, tmp7, atslab_0, arg1) ;
tmp6 = ATS_MALLOC(sizeof(anairiats_rec_1)) ;
ats_selptrset_mac(anairiats_rec_1, tmp6, atslab_e1xp_loc, arg0) ;
ats_selptrset_mac(anairiats_rec_1, tmp6, atslab_e1xp_node, tmp7) ;

return (tmp6) ;
} /* end of [ATS_2d0_2e2_2e10_2src_2ats_staexp1_2esats__e1xp_char] */

/*
// /home/hwxi/research/Anairiats/src/ats_staexp1.dats: 2459(line=86, offs=12) -- 2524(line=88, offs=2)
*/
ATSglobaldec()
ats_ptr_type
ATS_2d0_2e2_2e10_2src_2ats_staexp1_2esats__e1xp_float (ats_ptr_type arg0, ats_ptr_type arg1) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp8) ;
ATSlocal (ats_ptr_type, tmp9) ;

__ats_lab_ATS_2d0_2e2_2e10_2src_2ats_staexp1_2esats__e1xp_float:
tmp9 = ATS_MALLOC(sizeof(anairiats_sum_4)) ;
((ats_sum_ptr_type)tmp9)->tag = 2 ;
ats_selptrset_mac(anairiats_sum_4, tmp9, atslab_0, arg1) ;
tmp8 = ATS_MALLOC(sizeof(anairiats_rec_1)) ;
ats_selptrset_mac(anairiats_rec_1, tmp8, atslab_e1xp_loc, arg0) ;
ats_selptrset_mac(anairiats_rec_1, tmp8, atslab_e1xp_node, tmp9) ;

return (tmp8) ;
} /* end of [ATS_2d0_2e2_2e10_2src_2ats_staexp1_2esats__e1xp_float] */

/*
// /home/hwxi/research/Anairiats/src/ats_staexp1.dats: 2568(line=91, offs=10) -- 2632(line=93, offs=2)
*/
ATSglobaldec()
ats_ptr_type
ATS_2d0_2e2_2e10_2src_2ats_staexp1_2esats__e1xp_ide (ats_ptr_type arg0, ats_ptr_type arg1) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp10) ;
ATSlocal (ats_ptr_type, tmp11) ;

__ats_lab_ATS_2d0_2e2_2e10_2src_2ats_staexp1_2esats__e1xp_ide:
tmp11 = ATS_MALLOC(sizeof(anairiats_sum_4)) ;
((ats_sum_ptr_type)tmp11)->tag = 3 ;
ats_selptrset_mac(anairiats_sum_4, tmp11, atslab_0, arg1) ;
tmp10 = ATS_MALLOC(sizeof(anairiats_rec_1)) ;
ats_selptrset_mac(anairiats_rec_1, tmp10, atslab_e1xp_loc, arg0) ;
ats_selptrset_mac(anairiats_rec_1, tmp10, atslab_e1xp_node, tmp11) ;

return (tmp10) ;
} /* end of [ATS_2d0_2e2_2e10_2src_2ats_staexp1_2esats__e1xp_ide] */

/*
// /home/hwxi/research/Anairiats/src/ats_staexp1.dats: 2653(line=96, offs=10) -- 2720(line=98, offs=2)
*/
ATSglobaldec()
ats_ptr_type
ATS_2d0_2e2_2e10_2src_2ats_staexp1_2esats__e1xp_int (ats_ptr_type arg0, ats_ptr_type arg1) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp12) ;
ATSlocal (ats_ptr_type, tmp13) ;

__ats_lab_ATS_2d0_2e2_2e10_2src_2ats_staexp1_2esats__e1xp_int:
tmp13 = ATS_MALLOC(sizeof(anairiats_sum_4)) ;
((ats_sum_ptr_type)tmp13)->tag = 4 ;
ats_selptrset_mac(anairiats_sum_4, tmp13, atslab_0, arg1) ;
tmp12 = ATS_MALLOC(sizeof(anairiats_rec_1)) ;
ats_selptrset_mac(anairiats_rec_1, tmp12, atslab_e1xp_loc, arg0) ;
ats_selptrset_mac(anairiats_rec_1, tmp12, atslab_e1xp_node, tmp13) ;

return (tmp12) ;
} /* end of [ATS_2d0_2e2_2e10_2src_2ats_staexp1_2esats__e1xp_int] */

/*
// /home/hwxi/research/Anairiats/src/ats_staexp1.dats: 2742(line=101, offs=11) -- 2809(line=103, offs=2)
*/
ATSglobaldec()
ats_ptr_type
ATS_2d0_2e2_2e10_2src_2ats_staexp1_2esats__e1xp_list (ats_ptr_type arg0, ats_ptr_type arg1) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp14) ;
ATSlocal (ats_ptr_type, tmp15) ;

__ats_lab_ATS_2d0_2e2_2e10_2src_2ats_staexp1_2esats__e1xp_list:
tmp15 = ATS_MALLOC(sizeof(anairiats_sum_4)) ;
((ats_sum_ptr_type)tmp15)->tag = 5 ;
ats_selptrset_mac(anairiats_sum_4, tmp15, atslab_0, arg1) ;
tmp14 = ATS_MALLOC(sizeof(anairiats_rec_1)) ;
ats_selptrset_mac(anairiats_rec_1, tmp14, atslab_e1xp_loc, arg0) ;
ats_selptrset_mac(anairiats_rec_1, tmp14, atslab_e1xp_node, tmp15) ;

return (tmp14) ;
} /* end of [ATS_2d0_2e2_2e10_2src_2ats_staexp1_2esats__e1xp_list] */

/*
// /home/hwxi/research/Anairiats/src/ats_staexp1.dats: 2833(line=106, offs=13) -- 2905(line=108, offs=2)
*/
ATSglobaldec()
ats_ptr_type
ATS_2d0_2e2_2e10_2src_2ats_staexp1_2esats__e1xp_string (ats_ptr_type arg0, ats_ptr_type arg1, ats_int_type arg2) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp16) ;
ATSlocal (ats_ptr_type, tmp17) ;

__ats_lab_ATS_2d0_2e2_2e10_2src_2ats_staexp1_2esats__e1xp_string:
tmp17 = ATS_MALLOC(sizeof(anairiats_sum_5)) ;
((ats_sum_ptr_type)tmp17)->tag = 6 ;
ats_selptrset_mac(anairiats_sum_5, tmp17, atslab_0, arg1) ;
ats_selptrset_mac(anairiats_sum_5, tmp17, atslab_1, arg2) ;
tmp16 = ATS_MALLOC(sizeof(anairiats_rec_1)) ;
ats_selptrset_mac(anairiats_rec_1, tmp16, atslab_e1xp_loc, arg0) ;
ats_selptrset_mac(anairiats_rec_1, tmp16, atslab_e1xp_node, tmp17) ;

return (tmp16) ;
} /* end of [ATS_2d0_2e2_2e10_2src_2ats_staexp1_2esats__e1xp_string] */

/*
// /home/hwxi/research/Anairiats/src/ats_staexp1.dats: 2928(line=111, offs=12) -- 2981(line=113, offs=2)
*/
ATSglobaldec()
ats_ptr_type
ATS_2d0_2e2_2e10_2src_2ats_staexp1_2esats__e1xp_undef (ats_ptr_type arg0) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp18) ;
ATSlocal (ats_ptr_type, tmp19) ;

__ats_lab_ATS_2d0_2e2_2e10_2src_2ats_staexp1_2esats__e1xp_undef:
tmp19 = (ats_sum_ptr_type)(&ATS_2d0_2e2_2e10_2src_2ats_staexp1_2esats__E1XPundef) ;
tmp18 = ATS_MALLOC(sizeof(anairiats_rec_1)) ;
ats_selptrset_mac(anairiats_rec_1, tmp18, atslab_e1xp_loc, arg0) ;
ats_selptrset_mac(anairiats_rec_1, tmp18, atslab_e1xp_node, tmp19) ;

return (tmp18) ;
} /* end of [ATS_2d0_2e2_2e10_2src_2ats_staexp1_2esats__e1xp_undef] */

/*
// /home/hwxi/research/Anairiats/src/ats_staexp1.dats: 3027(line=116, offs=12) -- 3088(line=118, offs=2)
*/
ATSglobaldec()
ats_ptr_type
ATS_2d0_2e2_2e10_2src_2ats_staexp1_2esats__e1xp_cstsp (ats_ptr_type arg0, ats_ptr_type arg1) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp20) ;
ATSlocal (ats_ptr_type, tmp21) ;

__ats_lab_ATS_2d0_2e2_2e10_2src_2ats_staexp1_2esats__e1xp_cstsp:
tmp21 = ATS_MALLOC(sizeof(anairiats_sum_4)) ;
((ats_sum_ptr_type)tmp21)->tag = 8 ;
ats_selptrset_mac(anairiats_sum_4, tmp21, atslab_0, arg1) ;
tmp20 = ATS_MALLOC(sizeof(anairiats_rec_1)) ;
ats_selptrset_mac(anairiats_rec_1, tmp20, atslab_e1xp_loc, arg0) ;
ats_selptrset_mac(anairiats_rec_1, tmp20, atslab_e1xp_node, tmp21) ;

return (tmp20) ;
} /* end of [ATS_2d0_2e2_2e10_2src_2ats_staexp1_2esats__e1xp_cstsp] */

/*
// /home/hwxi/research/Anairiats/src/ats_staexp1.dats: 3133(line=121, offs=11) -- 3185(line=123, offs=2)
*/
ATSglobaldec()
ats_ptr_type
ATS_2d0_2e2_2e10_2src_2ats_staexp1_2esats__e1xp_none (ats_ptr_type arg0) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp22) ;
ATSlocal (ats_ptr_type, tmp23) ;

__ats_lab_ATS_2d0_2e2_2e10_2src_2ats_staexp1_2esats__e1xp_none:
tmp23 = (ats_sum_ptr_type)(&ATS_2d0_2e2_2e10_2src_2ats_staexp1_2esats__E1XPnone) ;
tmp22 = ATS_MALLOC(sizeof(anairiats_rec_1)) ;
ats_selptrset_mac(anairiats_rec_1, tmp22, atslab_e1xp_loc, arg0) ;
ats_selptrset_mac(anairiats_rec_1, tmp22, atslab_e1xp_node, tmp23) ;

return (tmp22) ;
} /* end of [ATS_2d0_2e2_2e10_2src_2ats_staexp1_2esats__e1xp_none] */

/*
// /home/hwxi/research/Anairiats/src/ats_staexp1.dats: 3252(line=128, offs=3) -- 3298(line=128, offs=49)
*/
ATSglobaldec()
ats_ptr_type
ATS_2d0_2e2_2e10_2src_2ats_staexp1_2esats__e1xp_true () {
/* local vardec */
ATSlocal (ats_ptr_type, tmp24) ;

__ats_lab_ATS_2d0_2e2_2e10_2src_2ats_staexp1_2esats__e1xp_true:
tmp24 = ATS_2d0_2e2_2e10_2src_2ats_staexp1_2esats__e1xp_int (ATS_2d0_2e2_2e10_2src_2ats_location_2esats__location_dummy, ATSstrcst("1")) ;
return (tmp24) ;
} /* end of [ATS_2d0_2e2_2e10_2src_2ats_staexp1_2esats__e1xp_true] */

/*
// /home/hwxi/research/Anairiats/src/ats_staexp1.dats: 3322(line=130, offs=3) -- 3368(line=130, offs=49)
*/
ATSglobaldec()
ats_ptr_type
ATS_2d0_2e2_2e10_2src_2ats_staexp1_2esats__e1xp_false () {
/* local vardec */
ATSlocal (ats_ptr_type, tmp25) ;

__ats_lab_ATS_2d0_2e2_2e10_2src_2ats_staexp1_2esats__e1xp_false:
tmp25 = ATS_2d0_2e2_2e10_2src_2ats_staexp1_2esats__e1xp_int (ATS_2d0_2e2_2e10_2src_2ats_location_2esats__location_dummy, ATSstrcst("0")) ;
return (tmp25) ;
} /* end of [ATS_2d0_2e2_2e10_2src_2ats_staexp1_2esats__e1xp_false] */

/*
// /home/hwxi/research/Anairiats/src/ats_staexp1.dats: 3539(line=141, offs=22) -- 3609(line=143, offs=2)
*/
ATSglobaldec()
ats_ptr_type
ATS_2d0_2e2_2e10_2src_2ats_staexp1_2esats__s1rt_arrow (ats_ptr_type arg0) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp28) ;
ATSlocal (ats_ptr_type, tmp29) ;

__ats_lab_ATS_2d0_2e2_2e10_2src_2ats_staexp1_2esats__s1rt_arrow:
tmp29 = ATS_MALLOC(sizeof(anairiats_sum_8)) ;
((ats_sum_ptr_type)tmp29)->tag = 2 ;
ats_selptrset_mac(anairiats_sum_8, tmp29, atslab_0, statmp0) ;
ats_selptrset_mac(anairiats_sum_8, tmp29, atslab_1, ATS_2d0_2e2_2e10_2src_2ats_symbol_2esats__symbol_MINUSGT) ;
tmp28 = ATS_MALLOC(sizeof(anairiats_rec_7)) ;
ats_selptrset_mac(anairiats_rec_7, tmp28, atslab_s1rt_loc, arg0) ;
ats_selptrset_mac(anairiats_rec_7, tmp28, atslab_s1rt_node, tmp29) ;

return (tmp28) ;
} /* end of [ATS_2d0_2e2_2e10_2src_2ats_staexp1_2esats__s1rt_arrow] */

/*
// /home/hwxi/research/Anairiats/src/ats_staexp1.dats: 3676(line=147, offs=15) -- 3820(line=152, offs=15)
*/
ATSglobaldec()
ats_bool_type
ATS_2d0_2e2_2e10_2src_2ats_staexp1_2esats__s1rt_is_arrow (ats_ptr_type arg0) {
/* local vardec */
ATSlocal (ats_bool_type, tmp30) ;
ATSlocal (ats_ptr_type, tmp31) ;
ATSlocal (ats_ptr_type, tmp32) ;
ATSlocal (ats_ptr_type, tmp33) ;
ATSlocal (ats_bool_type, tmp34) ;

__ats_lab_ATS_2d0_2e2_2e10_2src_2ats_staexp1_2esats__s1rt_is_arrow:
tmp31 = ats_selbox_mac(ats_castptr_mac(anairiats_rec_7, arg0), atslab_s1rt_node) ;
do {
/* branch: __ats_lab_2 */
__ats_lab_2_0:
if (((ats_sum_ptr_type)tmp31)->tag != 2) { goto __ats_lab_3_0 ; }
__ats_lab_2_1:
tmp32 = ats_caselptrlab_mac(anairiats_sum_8, tmp31, atslab_0) ;
tmp33 = ats_caselptrlab_mac(anairiats_sum_8, tmp31, atslab_1) ;
tmp34 = s0rtq_is_none_0 (tmp32) ;
if (tmp34) {
tmp30 = ATS_2d0_2e2_2e10_2src_2ats_symbol_2esats__eq_symbol_symbol (tmp33, ATS_2d0_2e2_2e10_2src_2ats_symbol_2esats__symbol_MINUSGT) ;
} else {
tmp30 = ats_false_bool ;
} /* end of [if] */
break ;

/* branch: __ats_lab_3 */
__ats_lab_3_0:
__ats_lab_3_1:
tmp30 = ats_false_bool ;
break ;
} while (0) ;
return (tmp30) ;
} /* end of [ATS_2d0_2e2_2e10_2src_2ats_staexp1_2esats__s1rt_is_arrow] */

/*
// /home/hwxi/research/Anairiats/src/ats_staexp1.dats: 3867(line=155, offs=20) -- 3954(line=156, offs=61)
*/
ATSglobaldec()
ats_ptr_type
ATS_2d0_2e2_2e10_2src_2ats_staexp1_2esats__s1rt_app (ats_ptr_type arg0, ats_ptr_type arg1, ats_ptr_type arg2) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp35) ;
ATSlocal (ats_ptr_type, tmp36) ;

__ats_lab_ATS_2d0_2e2_2e10_2src_2ats_staexp1_2esats__s1rt_app:
tmp36 = ATS_MALLOC(sizeof(anairiats_sum_8)) ;
((ats_sum_ptr_type)tmp36)->tag = 0 ;
ats_selptrset_mac(anairiats_sum_8, tmp36, atslab_0, arg1) ;
ats_selptrset_mac(anairiats_sum_8, tmp36, atslab_1, arg2) ;
tmp35 = ATS_MALLOC(sizeof(anairiats_rec_7)) ;
ats_selptrset_mac(anairiats_rec_7, tmp35, atslab_s1rt_loc, arg0) ;
ats_selptrset_mac(anairiats_rec_7, tmp35, atslab_s1rt_node, tmp36) ;

return (tmp35) ;
} /* end of [ATS_2d0_2e2_2e10_2src_2ats_staexp1_2esats__s1rt_app] */

/*
// /home/hwxi/research/Anairiats/src/ats_staexp1.dats: 3975(line=158, offs=20) -- 4122(line=161, offs=6)
*/
ATSglobaldec()
ats_ptr_type
ATS_2d0_2e2_2e10_2src_2ats_staexp1_2esats__s1rt_fun (ats_ptr_type arg0, ats_ptr_type arg1, ats_ptr_type arg2) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp37) ;
ATSlocal (ats_ptr_type, tmp38) ;
ATSlocal (ats_ptr_type, tmp39) ;
ATSlocal (ats_ptr_type, tmp40) ;
ATSlocal (ats_ptr_type, tmp41) ;
ATSlocal (ats_ptr_type, tmp42) ;

__ats_lab_ATS_2d0_2e2_2e10_2src_2ats_staexp1_2esats__s1rt_fun:
tmp40 = (ats_sum_ptr_type)0 ;
tmp39 = ATS_MALLOC(sizeof(anairiats_sum_9)) ;
ats_selptrset_mac(anairiats_sum_9, tmp39, atslab_0, arg2) ;
ats_selptrset_mac(anairiats_sum_9, tmp39, atslab_1, tmp40) ;
tmp38 = ATS_MALLOC(sizeof(anairiats_sum_9)) ;
ats_selptrset_mac(anairiats_sum_9, tmp38, atslab_0, arg1) ;
ats_selptrset_mac(anairiats_sum_9, tmp38, atslab_1, tmp39) ;
tmp42 = ATS_2d0_2e2_2e10_2src_2ats_staexp1_2esats__s1rt_arrow (arg0) ;
tmp41 = ATS_MALLOC(sizeof(anairiats_sum_8)) ;
((ats_sum_ptr_type)tmp41)->tag = 0 ;
ats_selptrset_mac(anairiats_sum_8, tmp41, atslab_0, tmp42) ;
ats_selptrset_mac(anairiats_sum_8, tmp41, atslab_1, tmp38) ;
tmp37 = ATS_MALLOC(sizeof(anairiats_rec_7)) ;
ats_selptrset_mac(anairiats_rec_7, tmp37, atslab_s1rt_loc, arg0) ;
ats_selptrset_mac(anairiats_rec_7, tmp37, atslab_s1rt_node, tmp41) ;

return (tmp37) ;
} /* end of [ATS_2d0_2e2_2e10_2src_2ats_staexp1_2esats__s1rt_fun] */

/*
// /home/hwxi/research/Anairiats/src/ats_staexp1.dats: 4143(line=163, offs=20) -- 4212(line=165, offs=2)
*/
ATSglobaldec()
ats_ptr_type
ATS_2d0_2e2_2e10_2src_2ats_staexp1_2esats__s1rt_ide (ats_ptr_type arg0, ats_ptr_type arg1) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp43) ;
ATSlocal (ats_ptr_type, tmp44) ;

__ats_lab_ATS_2d0_2e2_2e10_2src_2ats_staexp1_2esats__s1rt_ide:
tmp44 = ATS_MALLOC(sizeof(anairiats_sum_8)) ;
((ats_sum_ptr_type)tmp44)->tag = 2 ;
ats_selptrset_mac(anairiats_sum_8, tmp44, atslab_0, statmp0) ;
ats_selptrset_mac(anairiats_sum_8, tmp44, atslab_1, arg1) ;
tmp43 = ATS_MALLOC(sizeof(anairiats_rec_7)) ;
ats_selptrset_mac(anairiats_rec_7, tmp43, atslab_s1rt_loc, arg0) ;
ats_selptrset_mac(anairiats_rec_7, tmp43, atslab_s1rt_node, tmp44) ;

return (tmp43) ;
} /* end of [ATS_2d0_2e2_2e10_2src_2ats_staexp1_2esats__s1rt_ide] */

/*
// /home/hwxi/research/Anairiats/src/ats_staexp1.dats: 4234(line=167, offs=21) -- 4373(line=169, offs=54)
*/
ATSglobaldec()
ats_ptr_type
ATS_2d0_2e2_2e10_2src_2ats_staexp1_2esats__s1rt_list (ats_ptr_type arg0, ats_ptr_type arg1) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp45) ;
ATSlocal (ats_ptr_type, tmp46) ;
ATSlocal (ats_ptr_type, tmp47) ;
ATSlocal (ats_ptr_type, tmp48) ;

__ats_lab_ATS_2d0_2e2_2e10_2src_2ats_staexp1_2esats__s1rt_list:
do {
/* branch: __ats_lab_4 */
__ats_lab_4_0:
if (arg1 == (ats_sum_ptr_type)0) { goto __ats_lab_5_0 ; }
tmp46 = ats_caselptrlab_mac(anairiats_sum_9, arg1, atslab_1) ;
if (tmp46 != (ats_sum_ptr_type)0) { goto __ats_lab_5_0 ; }
__ats_lab_4_1:
tmp47 = ats_caselptrlab_mac(anairiats_sum_9, arg1, atslab_0) ;
tmp45 = tmp47 ;
break ;

/* branch: __ats_lab_5 */
__ats_lab_5_0:
__ats_lab_5_1:
tmp48 = ATS_MALLOC(sizeof(anairiats_sum_4)) ;
((ats_sum_ptr_type)tmp48)->tag = 1 ;
ats_selptrset_mac(anairiats_sum_4, tmp48, atslab_0, arg1) ;
tmp45 = ATS_MALLOC(sizeof(anairiats_rec_7)) ;
ats_selptrset_mac(anairiats_rec_7, tmp45, atslab_s1rt_loc, arg0) ;
ats_selptrset_mac(anairiats_rec_7, tmp45, atslab_s1rt_node, tmp48) ;

break ;
} while (0) ;
return (tmp45) ;
} /* end of [ATS_2d0_2e2_2e10_2src_2ats_staexp1_2esats__s1rt_list] */

/*
// /home/hwxi/research/Anairiats/src/ats_staexp1.dats: 4394(line=171, offs=20) -- 4459(line=172, offs=51)
*/
ATSglobaldec()
ats_ptr_type
ATS_2d0_2e2_2e10_2src_2ats_staexp1_2esats__s1rt_qid (ats_ptr_type arg0, ats_ptr_type arg1, ats_ptr_type arg2) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp49) ;
ATSlocal (ats_ptr_type, tmp50) ;

__ats_lab_ATS_2d0_2e2_2e10_2src_2ats_staexp1_2esats__s1rt_qid:
tmp50 = ATS_MALLOC(sizeof(anairiats_sum_8)) ;
((ats_sum_ptr_type)tmp50)->tag = 2 ;
ats_selptrset_mac(anairiats_sum_8, tmp50, atslab_0, arg1) ;
ats_selptrset_mac(anairiats_sum_8, tmp50, atslab_1, arg2) ;
tmp49 = ATS_MALLOC(sizeof(anairiats_rec_7)) ;
ats_selptrset_mac(anairiats_rec_7, tmp49, atslab_s1rt_loc, arg0) ;
ats_selptrset_mac(anairiats_rec_7, tmp49, atslab_s1rt_node, tmp50) ;

return (tmp49) ;
} /* end of [ATS_2d0_2e2_2e10_2src_2ats_staexp1_2esats__s1rt_qid] */

/*
// /home/hwxi/research/Anairiats/src/ats_staexp1.dats: 4480(line=174, offs=20) -- 4540(line=175, offs=47)
*/
ATSglobaldec()
ats_ptr_type
ATS_2d0_2e2_2e10_2src_2ats_staexp1_2esats__s1rt_tup (ats_ptr_type arg0, ats_ptr_type arg1) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp51) ;
ATSlocal (ats_ptr_type, tmp52) ;

__ats_lab_ATS_2d0_2e2_2e10_2src_2ats_staexp1_2esats__s1rt_tup:
tmp52 = ATS_MALLOC(sizeof(anairiats_sum_4)) ;
((ats_sum_ptr_type)tmp52)->tag = 3 ;
ats_selptrset_mac(anairiats_sum_4, tmp52, atslab_0, arg1) ;
tmp51 = ATS_MALLOC(sizeof(anairiats_rec_7)) ;
ats_selptrset_mac(anairiats_rec_7, tmp51, atslab_s1rt_loc, arg0) ;
ats_selptrset_mac(anairiats_rec_7, tmp51, atslab_s1rt_node, tmp52) ;

return (tmp51) ;
} /* end of [ATS_2d0_2e2_2e10_2src_2ats_staexp1_2esats__s1rt_tup] */

/*
// /home/hwxi/research/Anairiats/src/ats_staexp1.dats: 4586(line=179, offs=24) -- 4663(line=181, offs=2)
*/
ATSglobaldec()
ats_ptr_type
ATS_2d0_2e2_2e10_2src_2ats_staexp1_2esats__s1rtpol_make (ats_ptr_type arg0, ats_ptr_type arg1, ats_int_type arg2) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp53) ;

__ats_lab_ATS_2d0_2e2_2e10_2src_2ats_staexp1_2esats__s1rtpol_make:
tmp53 = ATS_MALLOC(sizeof(anairiats_rec_10)) ;
ats_selptrset_mac(anairiats_rec_10, tmp53, atslab_s1rtpol_loc, arg0) ;
ats_selptrset_mac(anairiats_rec_10, tmp53, atslab_s1rtpol_srt, arg1) ;
ats_selptrset_mac(anairiats_rec_10, tmp53, atslab_s1rtpol_pol, arg2) ;

return (tmp53) ;
} /* end of [ATS_2d0_2e2_2e10_2src_2ats_staexp1_2esats__s1rtpol_make] */

/*
// /home/hwxi/research/Anairiats/src/ats_staexp1.dats: 4708(line=185, offs=23) -- 4776(line=187, offs=2)
*/
ATSglobaldec()
ats_ptr_type
ATS_2d0_2e2_2e10_2src_2ats_staexp1_2esats__d1atarg_srt (ats_ptr_type arg0, ats_ptr_type arg1) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp54) ;
ATSlocal (ats_ptr_type, tmp55) ;

__ats_lab_ATS_2d0_2e2_2e10_2src_2ats_staexp1_2esats__d1atarg_srt:
tmp55 = ATS_MALLOC(sizeof(anairiats_sum_4)) ;
((ats_sum_ptr_type)tmp55)->tag = 0 ;
ats_selptrset_mac(anairiats_sum_4, tmp55, atslab_0, arg1) ;
tmp54 = ATS_MALLOC(sizeof(anairiats_rec_11)) ;
ats_selptrset_mac(anairiats_rec_11, tmp54, atslab_d1atarg_loc, arg0) ;
ats_selptrset_mac(anairiats_rec_11, tmp54, atslab_d1atarg_node, tmp55) ;

return (tmp54) ;
} /* end of [ATS_2d0_2e2_2e10_2src_2ats_staexp1_2esats__d1atarg_srt] */

/*
// /home/hwxi/research/Anairiats/src/ats_staexp1.dats: 4802(line=189, offs=25) -- 4882(line=191, offs=2)
*/
ATSglobaldec()
ats_ptr_type
ATS_2d0_2e2_2e10_2src_2ats_staexp1_2esats__d1atarg_idsrt (ats_ptr_type arg0, ats_ptr_type arg1, ats_ptr_type arg2) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp56) ;
ATSlocal (ats_ptr_type, tmp57) ;

__ats_lab_ATS_2d0_2e2_2e10_2src_2ats_staexp1_2esats__d1atarg_idsrt:
tmp57 = ATS_MALLOC(sizeof(anairiats_sum_8)) ;
((ats_sum_ptr_type)tmp57)->tag = 1 ;
ats_selptrset_mac(anairiats_sum_8, tmp57, atslab_0, arg1) ;
ats_selptrset_mac(anairiats_sum_8, tmp57, atslab_1, arg2) ;
tmp56 = ATS_MALLOC(sizeof(anairiats_rec_11)) ;
ats_selptrset_mac(anairiats_rec_11, tmp56, atslab_d1atarg_loc, arg0) ;
ats_selptrset_mac(anairiats_rec_11, tmp56, atslab_d1atarg_node, tmp57) ;

return (tmp56) ;
} /* end of [ATS_2d0_2e2_2e10_2src_2ats_staexp1_2esats__d1atarg_idsrt] */

/*
// /home/hwxi/research/Anairiats/src/ats_staexp1.dats: 4926(line=195, offs=22) -- 4996(line=197, offs=2)
*/
ATSglobaldec()
ats_ptr_type
ATS_2d0_2e2_2e10_2src_2ats_staexp1_2esats__s1arg_make (ats_ptr_type arg0, ats_ptr_type arg1, ats_ptr_type arg2) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp58) ;

__ats_lab_ATS_2d0_2e2_2e10_2src_2ats_staexp1_2esats__s1arg_make:
tmp58 = ATS_MALLOC(sizeof(anairiats_rec_12)) ;
ats_selptrset_mac(anairiats_rec_12, tmp58, atslab_s1arg_loc, arg0) ;
ats_selptrset_mac(anairiats_rec_12, tmp58, atslab_s1arg_sym, arg1) ;
ats_selptrset_mac(anairiats_rec_12, tmp58, atslab_s1arg_srt, arg2) ;

return (tmp58) ;
} /* end of [ATS_2d0_2e2_2e10_2src_2ats_staexp1_2esats__s1arg_make] */

/*
// /home/hwxi/research/Anairiats/src/ats_staexp1.dats: 5018(line=199, offs=21) -- 5095(line=201, offs=2)
*/
ATSglobaldec()
ats_ptr_type
ATS_2d0_2e2_2e10_2src_2ats_staexp1_2esats__sp1at_con (ats_ptr_type arg0, ats_ptr_type arg1, ats_ptr_type arg2, ats_ptr_type arg3) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp59) ;
ATSlocal (ats_ptr_type, tmp60) ;

__ats_lab_ATS_2d0_2e2_2e10_2src_2ats_staexp1_2esats__sp1at_con:
tmp60 = ATS_MALLOC(sizeof(anairiats_sum_14)) ;
ats_selptrset_mac(anairiats_sum_14, tmp60, atslab_0, arg1) ;
ats_selptrset_mac(anairiats_sum_14, tmp60, atslab_1, arg2) ;
ats_selptrset_mac(anairiats_sum_14, tmp60, atslab_2, arg3) ;
tmp59 = ATS_MALLOC(sizeof(anairiats_rec_13)) ;
ats_selptrset_mac(anairiats_rec_13, tmp59, atslab_sp1at_loc, arg0) ;
ats_selptrset_mac(anairiats_rec_13, tmp59, atslab_sp1at_node, tmp60) ;

return (tmp59) ;
} /* end of [ATS_2d0_2e2_2e10_2src_2ats_staexp1_2esats__sp1at_con] */

/*
// /home/hwxi/research/Anairiats/src/ats_staexp1.dats: 5139(line=205, offs=21) -- 5209(line=207, offs=2)
*/
ATSglobaldec()
ats_ptr_type
ATS_2d0_2e2_2e10_2src_2ats_staexp1_2esats__s1exp_ann (ats_ptr_type arg0, ats_ptr_type arg1, ats_ptr_type arg2) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp61) ;
ATSlocal (ats_ptr_type, tmp62) ;

__ats_lab_ATS_2d0_2e2_2e10_2src_2ats_staexp1_2esats__s1exp_ann:
tmp62 = ATS_MALLOC(sizeof(anairiats_sum_8)) ;
((ats_sum_ptr_type)tmp62)->tag = 0 ;
ats_selptrset_mac(anairiats_sum_8, tmp62, atslab_0, arg1) ;
ats_selptrset_mac(anairiats_sum_8, tmp62, atslab_1, arg2) ;
tmp61 = ATS_MALLOC(sizeof(anairiats_rec_15)) ;
ats_selptrset_mac(anairiats_rec_15, tmp61, atslab_s1exp_loc, arg0) ;
ats_selptrset_mac(anairiats_rec_15, tmp61, atslab_s1exp_node, tmp62) ;

return (tmp61) ;
} /* end of [ATS_2d0_2e2_2e10_2src_2ats_staexp1_2esats__s1exp_ann] */

/*
// /home/hwxi/research/Anairiats/src/ats_staexp1.dats: 5232(line=209, offs=21) -- 5284(line=210, offs=45)
*/
ATSglobaldec()
ats_ptr_type
ATS_2d0_2e2_2e10_2src_2ats_staexp1_2esats__s1exp_any (ats_ptr_type arg0) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp63) ;
ATSlocal (ats_ptr_type, tmp64) ;

__ats_lab_ATS_2d0_2e2_2e10_2src_2ats_staexp1_2esats__s1exp_any:
tmp64 = (ats_sum_ptr_type)(&ATS_2d0_2e2_2e10_2src_2ats_staexp1_2esats__S1Eany) ;
tmp63 = ATS_MALLOC(sizeof(anairiats_rec_15)) ;
ats_selptrset_mac(anairiats_rec_15, tmp63, atslab_s1exp_loc, arg0) ;
ats_selptrset_mac(anairiats_rec_15, tmp63, atslab_s1exp_node, tmp64) ;

return (tmp63) ;
} /* end of [ATS_2d0_2e2_2e10_2src_2ats_staexp1_2esats__s1exp_any] */

/*
// /home/hwxi/research/Anairiats/src/ats_staexp1.dats: 5307(line=212, offs=21) -- 5397(line=214, offs=2)
*/
ATSglobaldec()
ats_ptr_type
ATS_2d0_2e2_2e10_2src_2ats_staexp1_2esats__s1exp_app (ats_ptr_type arg0, ats_ptr_type arg1, ats_ptr_type arg2, ats_ptr_type arg3) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp65) ;
ATSlocal (ats_ptr_type, tmp66) ;

__ats_lab_ATS_2d0_2e2_2e10_2src_2ats_staexp1_2esats__s1exp_app:
tmp66 = ATS_MALLOC(sizeof(anairiats_sum_2)) ;
((ats_sum_ptr_type)tmp66)->tag = 2 ;
ats_selptrset_mac(anairiats_sum_2, tmp66, atslab_0, arg1) ;
ats_selptrset_mac(anairiats_sum_2, tmp66, atslab_1, arg2) ;
ats_selptrset_mac(anairiats_sum_2, tmp66, atslab_2, arg3) ;
tmp65 = ATS_MALLOC(sizeof(anairiats_rec_15)) ;
ats_selptrset_mac(anairiats_rec_15, tmp65, atslab_s1exp_loc, arg0) ;
ats_selptrset_mac(anairiats_rec_15, tmp65, atslab_s1exp_node, tmp66) ;

return (tmp65) ;
} /* end of [ATS_2d0_2e2_2e10_2src_2ats_staexp1_2esats__s1exp_app] */

/*
// /home/hwxi/research/Anairiats/src/ats_staexp1.dats: 5420(line=216, offs=22) -- 5475(line=217, offs=45)
*/
ATSglobaldec()
ats_ptr_type
ATS_2d0_2e2_2e10_2src_2ats_staexp1_2esats__s1exp_char (ats_ptr_type arg0, ats_char_type arg1) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp67) ;
ATSlocal (ats_ptr_type, tmp68) ;

__ats_lab_ATS_2d0_2e2_2e10_2src_2ats_staexp1_2esats__s1exp_char:
tmp68 = ATS_MALLOC(sizeof(anairiats_sum_3)) ;
((ats_sum_ptr_type)tmp68)->tag = 3 ;
ats_selptrset_mac(anairiats_sum_3, tmp68, atslab_0, arg1) ;
tmp67 = ATS_MALLOC(sizeof(anairiats_rec_15)) ;
ats_selptrset_mac(anairiats_rec_15, tmp67, atslab_s1exp_loc, arg0) ;
ats_selptrset_mac(anairiats_rec_15, tmp67, atslab_s1exp_node, tmp68) ;

return (tmp67) ;
} /* end of [ATS_2d0_2e2_2e10_2src_2ats_staexp1_2esats__s1exp_char] */

/*
// /home/hwxi/research/Anairiats/src/ats_staexp1.dats: 5497(line=219, offs=21) -- 5589(line=221, offs=2)
*/
ATSglobaldec()
ats_ptr_type
ATS_2d0_2e2_2e10_2src_2ats_staexp1_2esats__s1exp_exi (ats_ptr_type arg0, ats_int_type arg1, ats_ptr_type arg2, ats_ptr_type arg3) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp69) ;
ATSlocal (ats_ptr_type, tmp70) ;

__ats_lab_ATS_2d0_2e2_2e10_2src_2ats_staexp1_2esats__s1exp_exi:
tmp70 = ATS_MALLOC(sizeof(anairiats_sum_16)) ;
((ats_sum_ptr_type)tmp70)->tag = 4 ;
ats_selptrset_mac(anairiats_sum_16, tmp70, atslab_0, arg1) ;
ats_selptrset_mac(anairiats_sum_16, tmp70, atslab_1, arg2) ;
ats_selptrset_mac(anairiats_sum_16, tmp70, atslab_2, arg3) ;
tmp69 = ATS_MALLOC(sizeof(anairiats_rec_15)) ;
ats_selptrset_mac(anairiats_rec_15, tmp69, atslab_s1exp_loc, arg0) ;
ats_selptrset_mac(anairiats_rec_15, tmp69, atslab_s1exp_node, tmp70) ;

return (tmp69) ;
} /* end of [ATS_2d0_2e2_2e10_2src_2ats_staexp1_2esats__s1exp_exi] */

/*
// /home/hwxi/research/Anairiats/src/ats_staexp1.dats: 5614(line=224, offs=14) -- 5695(line=226, offs=2)
*/
ATSglobaldec()
ats_ptr_type
ATS_2d0_2e2_2e10_2src_2ats_staexp1_2esats__s1exp_extype (ats_ptr_type arg0, ats_ptr_type arg1, ats_ptr_type arg2) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp71) ;
ATSlocal (ats_ptr_type, tmp72) ;

__ats_lab_ATS_2d0_2e2_2e10_2src_2ats_staexp1_2esats__s1exp_extype:
tmp72 = ATS_MALLOC(sizeof(anairiats_sum_8)) ;
((ats_sum_ptr_type)tmp72)->tag = 5 ;
ats_selptrset_mac(anairiats_sum_8, tmp72, atslab_0, arg1) ;
ats_selptrset_mac(anairiats_sum_8, tmp72, atslab_1, arg2) ;
tmp71 = ATS_MALLOC(sizeof(anairiats_rec_15)) ;
ats_selptrset_mac(anairiats_rec_15, tmp71, atslab_s1exp_loc, arg0) ;
ats_selptrset_mac(anairiats_rec_15, tmp71, atslab_s1exp_node, tmp72) ;

return (tmp71) ;
} /* end of [ATS_2d0_2e2_2e10_2src_2ats_staexp1_2esats__s1exp_extype] */

/*
// /home/hwxi/research/Anairiats/src/ats_staexp1.dats: 5742(line=228, offs=21) -- 5819(line=230, offs=2)
*/
ATSglobaldec()
ats_ptr_type
ATS_2d0_2e2_2e10_2src_2ats_staexp1_2esats__s1exp_ide (ats_ptr_type arg0, ats_ptr_type arg1) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp73) ;
ATSlocal (ats_ptr_type, tmp74) ;

__ats_lab_ATS_2d0_2e2_2e10_2src_2ats_staexp1_2esats__s1exp_ide:
tmp74 = ATS_MALLOC(sizeof(anairiats_sum_8)) ;
((ats_sum_ptr_type)tmp74)->tag = 11 ;
ats_selptrset_mac(anairiats_sum_8, tmp74, atslab_0, statmp1) ;
ats_selptrset_mac(anairiats_sum_8, tmp74, atslab_1, arg1) ;
tmp73 = ATS_MALLOC(sizeof(anairiats_rec_15)) ;
ats_selptrset_mac(anairiats_rec_15, tmp73, atslab_s1exp_loc, arg0) ;
ats_selptrset_mac(anairiats_rec_15, tmp73, atslab_s1exp_node, tmp74) ;

return (tmp73) ;
} /* end of [ATS_2d0_2e2_2e10_2src_2ats_staexp1_2esats__s1exp_ide] */

/*
// /home/hwxi/research/Anairiats/src/ats_staexp1.dats: 5841(line=232, offs=21) -- 5943(line=234, offs=2)
*/
ATSglobaldec()
ats_ptr_type
ATS_2d0_2e2_2e10_2src_2ats_staexp1_2esats__s1exp_imp (ats_ptr_type arg0, ats_ptr_type arg1, ats_int_type arg2, ats_int_type arg3, ats_ptr_type arg4) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp75) ;
ATSlocal (ats_ptr_type, tmp76) ;

__ats_lab_ATS_2d0_2e2_2e10_2src_2ats_staexp1_2esats__s1exp_imp:
tmp76 = ATS_MALLOC(sizeof(anairiats_sum_17)) ;
((ats_sum_ptr_type)tmp76)->tag = 6 ;
ats_selptrset_mac(anairiats_sum_17, tmp76, atslab_0, arg1) ;
ats_selptrset_mac(anairiats_sum_17, tmp76, atslab_1, arg2) ;
ats_selptrset_mac(anairiats_sum_17, tmp76, atslab_2, arg3) ;
ats_selptrset_mac(anairiats_sum_17, tmp76, atslab_3, arg4) ;
tmp75 = ATS_MALLOC(sizeof(anairiats_rec_15)) ;
ats_selptrset_mac(anairiats_rec_15, tmp75, atslab_s1exp_loc, arg0) ;
ats_selptrset_mac(anairiats_rec_15, tmp75, atslab_s1exp_node, tmp76) ;

return (tmp75) ;
} /* end of [ATS_2d0_2e2_2e10_2src_2ats_staexp1_2esats__s1exp_imp] */

/*
// /home/hwxi/research/Anairiats/src/ats_staexp1.dats: 5965(line=236, offs=21) -- 6031(line=237, offs=46)
*/
ATSglobaldec()
ats_ptr_type
ATS_2d0_2e2_2e10_2src_2ats_staexp1_2esats__s1exp_int (ats_ptr_type arg0, ats_ptr_type arg1) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp77) ;
ATSlocal (ats_ptr_type, tmp78) ;

__ats_lab_ATS_2d0_2e2_2e10_2src_2ats_staexp1_2esats__s1exp_int:
tmp78 = ATS_MALLOC(sizeof(anairiats_sum_4)) ;
((ats_sum_ptr_type)tmp78)->tag = 7 ;
ats_selptrset_mac(anairiats_sum_4, tmp78, atslab_0, arg1) ;
tmp77 = ATS_MALLOC(sizeof(anairiats_rec_15)) ;
ats_selptrset_mac(anairiats_rec_15, tmp77, atslab_s1exp_loc, arg0) ;
ats_selptrset_mac(anairiats_rec_15, tmp77, atslab_s1exp_node, tmp78) ;

return (tmp77) ;
} /* end of [ATS_2d0_2e2_2e10_2src_2ats_staexp1_2esats__s1exp_int] */

/*
// /home/hwxi/research/Anairiats/src/ats_staexp1.dats: 6055(line=239, offs=23) -- 6133(line=241, offs=2)
*/
ATSglobaldec()
ats_ptr_type
ATS_2d0_2e2_2e10_2src_2ats_staexp1_2esats__s1exp_invar (ats_ptr_type arg0, ats_int_type arg1, ats_ptr_type arg2) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp79) ;
ATSlocal (ats_ptr_type, tmp80) ;

__ats_lab_ATS_2d0_2e2_2e10_2src_2ats_staexp1_2esats__s1exp_invar:
tmp80 = ATS_MALLOC(sizeof(anairiats_sum_18)) ;
((ats_sum_ptr_type)tmp80)->tag = 8 ;
ats_selptrset_mac(anairiats_sum_18, tmp80, atslab_0, arg1) ;
ats_selptrset_mac(anairiats_sum_18, tmp80, atslab_1, arg2) ;
tmp79 = ATS_MALLOC(sizeof(anairiats_rec_15)) ;
ats_selptrset_mac(anairiats_rec_15, tmp79, atslab_s1exp_loc, arg0) ;
ats_selptrset_mac(anairiats_rec_15, tmp79, atslab_s1exp_node, tmp80) ;

return (tmp79) ;
} /* end of [ATS_2d0_2e2_2e10_2src_2ats_staexp1_2esats__s1exp_invar] */

/*
// /home/hwxi/research/Anairiats/src/ats_staexp1.dats: 6155(line=243, offs=21) -- 6237(line=245, offs=2)
*/
ATSglobaldec()
ats_ptr_type
ATS_2d0_2e2_2e10_2src_2ats_staexp1_2esats__s1exp_lam (ats_ptr_type arg0, ats_ptr_type arg1, ats_ptr_type arg2, ats_ptr_type arg3) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp81) ;
ATSlocal (ats_ptr_type, tmp82) ;

__ats_lab_ATS_2d0_2e2_2e10_2src_2ats_staexp1_2esats__s1exp_lam:
tmp82 = ATS_MALLOC(sizeof(anairiats_sum_2)) ;
((ats_sum_ptr_type)tmp82)->tag = 9 ;
ats_selptrset_mac(anairiats_sum_2, tmp82, atslab_0, arg1) ;
ats_selptrset_mac(anairiats_sum_2, tmp82, atslab_1, arg2) ;
ats_selptrset_mac(anairiats_sum_2, tmp82, atslab_2, arg3) ;
tmp81 = ATS_MALLOC(sizeof(anairiats_rec_15)) ;
ats_selptrset_mac(anairiats_rec_15, tmp81, atslab_s1exp_loc, arg0) ;
ats_selptrset_mac(anairiats_rec_15, tmp81, atslab_s1exp_node, tmp82) ;

return (tmp81) ;
} /* end of [ATS_2d0_2e2_2e10_2src_2ats_staexp1_2esats__s1exp_lam] */

/*
// /home/hwxi/research/Anairiats/src/ats_staexp1.dats: 6260(line=247, offs=22) -- 6569(line=257, offs=6)
*/
ATSglobaldec()
ats_ptr_type
ATS_2d0_2e2_2e10_2src_2ats_staexp1_2esats__s1exp_list (ats_ptr_type arg0, ats_ptr_type arg1) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp83) ;
ATSlocal (ats_ptr_type, tmp84) ;
ATSlocal (ats_ptr_type, tmp85) ;
ATSlocal (ats_ptr_type, tmp86) ;

__ats_lab_ATS_2d0_2e2_2e10_2src_2ats_staexp1_2esats__s1exp_list:
do {
/* branch: __ats_lab_6 */
__ats_lab_6_0:
if (arg1 == (ats_sum_ptr_type)0) { goto __ats_lab_7_0 ; }
tmp84 = ats_caselptrlab_mac(anairiats_sum_9, arg1, atslab_1) ;
if (tmp84 != (ats_sum_ptr_type)0) { goto __ats_lab_7_0 ; }
__ats_lab_6_1:
tmp85 = ats_caselptrlab_mac(anairiats_sum_9, arg1, atslab_0) ;
tmp83 = tmp85 ;
break ;

/* branch: __ats_lab_7 */
__ats_lab_7_0:
__ats_lab_7_1:
tmp86 = ATS_MALLOC(sizeof(anairiats_sum_18)) ;
((ats_sum_ptr_type)tmp86)->tag = 10 ;
ats_selptrset_mac(anairiats_sum_18, tmp86, atslab_0, 0) ;
ats_selptrset_mac(anairiats_sum_18, tmp86, atslab_1, arg1) ;
tmp83 = ATS_MALLOC(sizeof(anairiats_rec_15)) ;
ats_selptrset_mac(anairiats_rec_15, tmp83, atslab_s1exp_loc, arg0) ;
ats_selptrset_mac(anairiats_rec_15, tmp83, atslab_s1exp_node, tmp86) ;

break ;
} while (0) ;
return (tmp83) ;
} /* end of [ATS_2d0_2e2_2e10_2src_2ats_staexp1_2esats__s1exp_list] */

/*
// /home/hwxi/research/Anairiats/src/ats_staexp1.dats: 6632(line=261, offs=3) -- 6799(line=266, offs=6)
*/
ATSglobaldec()
ats_ptr_type
ATS_2d0_2e2_2e10_2src_2ats_staexp1_2esats__s1exp_list2 (ats_ptr_type arg0, ats_ptr_type arg1, ats_ptr_type arg2) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp87) ;
ATSlocal (ats_int_type, tmp88) ;
ATSlocal (ats_ptr_type, tmp89) ;
ATSlocal (ats_ptr_type, tmp90) ;

__ats_lab_ATS_2d0_2e2_2e10_2src_2ats_staexp1_2esats__s1exp_list2:
tmp88 = ATS_2d0_2e2_2e10_2src_2ats_list_2esats__list_length (arg1) ;
tmp89 = ATS_2d0_2e2_2e10_2src_2ats_list_2esats__list_append (arg1, arg2) ;
tmp90 = ATS_MALLOC(sizeof(anairiats_sum_18)) ;
((ats_sum_ptr_type)tmp90)->tag = 10 ;
ats_selptrset_mac(anairiats_sum_18, tmp90, atslab_0, tmp88) ;
ats_selptrset_mac(anairiats_sum_18, tmp90, atslab_1, tmp89) ;
tmp87 = ATS_MALLOC(sizeof(anairiats_rec_15)) ;
ats_selptrset_mac(anairiats_rec_15, tmp87, atslab_s1exp_loc, arg0) ;
ats_selptrset_mac(anairiats_rec_15, tmp87, atslab_s1exp_node, tmp90) ;

return (tmp87) ;
} /* end of [ATS_2d0_2e2_2e10_2src_2ats_staexp1_2esats__s1exp_list2] */

/*
// /home/hwxi/research/Anairiats/src/ats_staexp1.dats: 7124(line=282, offs=21) -- 7195(line=283, offs=50)
*/
ATSglobaldec()
ats_ptr_type
ATS_2d0_2e2_2e10_2src_2ats_staexp1_2esats__s1exp_qid (ats_ptr_type arg0, ats_ptr_type arg1, ats_ptr_type arg2) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp91) ;
ATSlocal (ats_ptr_type, tmp92) ;

__ats_lab_ATS_2d0_2e2_2e10_2src_2ats_staexp1_2esats__s1exp_qid:
tmp92 = ATS_MALLOC(sizeof(anairiats_sum_8)) ;
((ats_sum_ptr_type)tmp92)->tag = 11 ;
ats_selptrset_mac(anairiats_sum_8, tmp92, atslab_0, arg1) ;
ats_selptrset_mac(anairiats_sum_8, tmp92, atslab_1, arg2) ;
tmp91 = ATS_MALLOC(sizeof(anairiats_rec_15)) ;
ats_selptrset_mac(anairiats_rec_15, tmp91, atslab_s1exp_loc, arg0) ;
ats_selptrset_mac(anairiats_rec_15, tmp91, atslab_s1exp_node, tmp92) ;

return (tmp91) ;
} /* end of [ATS_2d0_2e2_2e10_2src_2ats_staexp1_2esats__s1exp_qid] */

/*
// /home/hwxi/research/Anairiats/src/ats_staexp1.dats: 7241(line=286, offs=6) -- 7428(line=290, offs=6)
*/
ATSstaticdec()
ats_ptr_type
err_41 (ats_ptr_type arg0) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp94) ;
// ATSlocal_void (tmp95) ;
// ATSlocal_void (tmp96) ;
// ATSlocal_void (tmp97) ;
// ATSlocal_void (tmp98) ;

__ats_lab_err_41:
/* tmp95 = */ ATS_2d0_2e2_2e10_2src_2ats_location_2esats__prerr_location (arg0) ;
/* tmp96 = */ atspre_prerr_string (ATSstrcst(": error(1)")) ;
/* tmp97 = */ atspre_prerr_string (ATSstrcst(": [read@] requires exactly two arguments.")) ;
/* tmp98 = */ atspre_prerr_newline () ;
/* tmp94 = */ ATS_2d0_2e2_2e10_2src_2ats_error_2esats__abort () ;
return (tmp94) ;
} /* end of [err_41] */

/*
// /home/hwxi/research/Anairiats/src/ats_staexp1.dats: 7219(line=285, offs=22) -- 7724(line=300, offs=4)
*/
ATSglobaldec()
ats_ptr_type
ATS_2d0_2e2_2e10_2src_2ats_staexp1_2esats__s1exp_read (ats_ptr_type arg0, ats_ptr_type arg1) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp93) ;
ATSlocal (ats_ptr_type, tmp99) ;
ATSlocal (ats_ptr_type, tmp100) ;
ATSlocal (ats_ptr_type, tmp101) ;
ATSlocal (ats_ptr_type, tmp102) ;
ATSlocal (ats_ptr_type, tmp103) ;
ATSlocal (ats_ptr_type, tmp104) ;
ATSlocal (ats_ptr_type, tmp105) ;

__ats_lab_ATS_2d0_2e2_2e10_2src_2ats_staexp1_2esats__s1exp_read:
tmp99 = ats_selbox_mac(ats_castptr_mac(anairiats_rec_15, arg1), atslab_s1exp_node) ;
do {
/* branch: __ats_lab_8 */
__ats_lab_8_0:
if (((ats_sum_ptr_type)tmp99)->tag != 10) { goto __ats_lab_11_0 ; }
__ats_lab_8_1:
tmp100 = ats_caselptrlab_mac(anairiats_sum_18, tmp99, atslab_1) ;
do {
/* branch: __ats_lab_9 */
__ats_lab_9_0:
if (tmp100 == (ats_sum_ptr_type)0) { goto __ats_lab_10_0 ; }
tmp101 = ats_caselptrlab_mac(anairiats_sum_9, tmp100, atslab_1) ;
if (tmp101 == (ats_sum_ptr_type)0) { goto __ats_lab_10_0 ; }
tmp102 = ats_caselptrlab_mac(anairiats_sum_9, tmp101, atslab_1) ;
if (tmp102 != (ats_sum_ptr_type)0) { goto __ats_lab_10_0 ; }
__ats_lab_9_1:
tmp103 = ats_caselptrlab_mac(anairiats_sum_9, tmp100, atslab_0) ;
tmp104 = ats_caselptrlab_mac(anairiats_sum_9, tmp101, atslab_0) ;
tmp105 = ATS_MALLOC(sizeof(anairiats_sum_8)) ;
((ats_sum_ptr_type)tmp105)->tag = 12 ;
ats_selptrset_mac(anairiats_sum_8, tmp105, atslab_0, tmp103) ;
ats_selptrset_mac(anairiats_sum_8, tmp105, atslab_1, tmp104) ;
tmp93 = ATS_MALLOC(sizeof(anairiats_rec_15)) ;
ats_selptrset_mac(anairiats_rec_15, tmp93, atslab_s1exp_loc, arg0) ;
ats_selptrset_mac(anairiats_rec_15, tmp93, atslab_s1exp_node, tmp105) ;

break ;

/* branch: __ats_lab_10 */
__ats_lab_10_0:
__ats_lab_10_1:
tmp93 = err_41 (arg0) ;
break ;
} while (0) ;
break ;

/* branch: __ats_lab_11 */
__ats_lab_11_0:
__ats_lab_11_1:
tmp93 = err_41 (arg0) ;
break ;
} while (0) ;
return (tmp93) ;
} /* end of [ATS_2d0_2e2_2e10_2src_2ats_staexp1_2esats__s1exp_read] */

/*
// /home/hwxi/research/Anairiats/src/ats_staexp1.dats: 7925(line=310, offs=21) -- 7995(line=312, offs=2)
*/
ATSglobaldec()
ats_ptr_type
ATS_2d0_2e2_2e10_2src_2ats_staexp1_2esats__s1exp_top (ats_ptr_type arg0, ats_int_type arg1, ats_ptr_type arg2) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp106) ;
ATSlocal (ats_ptr_type, tmp107) ;

__ats_lab_ATS_2d0_2e2_2e10_2src_2ats_staexp1_2esats__s1exp_top:
tmp107 = ATS_MALLOC(sizeof(anairiats_sum_18)) ;
((ats_sum_ptr_type)tmp107)->tag = 13 ;
ats_selptrset_mac(anairiats_sum_18, tmp107, atslab_0, arg1) ;
ats_selptrset_mac(anairiats_sum_18, tmp107, atslab_1, arg2) ;
tmp106 = ATS_MALLOC(sizeof(anairiats_rec_15)) ;
ats_selptrset_mac(anairiats_rec_15, tmp106, atslab_s1exp_loc, arg0) ;
ats_selptrset_mac(anairiats_rec_15, tmp106, atslab_s1exp_node, tmp107) ;

return (tmp106) ;
} /* end of [ATS_2d0_2e2_2e10_2src_2ats_staexp1_2esats__s1exp_top] */

/*
// /home/hwxi/research/Anairiats/src/ats_staexp1.dats: 8019(line=314, offs=23) -- 8095(line=316, offs=2)
*/
ATSglobaldec()
ats_ptr_type
ATS_2d0_2e2_2e10_2src_2ats_staexp1_2esats__s1exp_trans (ats_ptr_type arg0, ats_ptr_type arg1, ats_ptr_type arg2) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp108) ;
ATSlocal (ats_ptr_type, tmp109) ;

__ats_lab_ATS_2d0_2e2_2e10_2src_2ats_staexp1_2esats__s1exp_trans:
tmp109 = ATS_MALLOC(sizeof(anairiats_sum_8)) ;
((ats_sum_ptr_type)tmp109)->tag = 14 ;
ats_selptrset_mac(anairiats_sum_8, tmp109, atslab_0, arg1) ;
ats_selptrset_mac(anairiats_sum_8, tmp109, atslab_1, arg2) ;
tmp108 = ATS_MALLOC(sizeof(anairiats_rec_15)) ;
ats_selptrset_mac(anairiats_rec_15, tmp108, atslab_s1exp_loc, arg0) ;
ats_selptrset_mac(anairiats_rec_15, tmp108, atslab_s1exp_node, tmp109) ;

return (tmp108) ;
} /* end of [ATS_2d0_2e2_2e10_2src_2ats_staexp1_2esats__s1exp_trans] */

/*
// /home/hwxi/research/Anairiats/src/ats_staexp1.dats: 8119(line=318, offs=23) -- 8211(line=320, offs=2)
*/
ATSglobaldec()
ats_ptr_type
ATS_2d0_2e2_2e10_2src_2ats_staexp1_2esats__s1exp_tyarr (ats_ptr_type arg0, ats_ptr_type arg1, ats_ptr_type arg2) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp110) ;
ATSlocal (ats_ptr_type, tmp111) ;

__ats_lab_ATS_2d0_2e2_2e10_2src_2ats_staexp1_2esats__s1exp_tyarr:
tmp111 = ATS_MALLOC(sizeof(anairiats_sum_8)) ;
((ats_sum_ptr_type)tmp111)->tag = 15 ;
ats_selptrset_mac(anairiats_sum_8, tmp111, atslab_0, arg1) ;
ats_selptrset_mac(anairiats_sum_8, tmp111, atslab_1, arg2) ;
tmp110 = ATS_MALLOC(sizeof(anairiats_rec_15)) ;
ats_selptrset_mac(anairiats_rec_15, tmp110, atslab_s1exp_loc, arg0) ;
ats_selptrset_mac(anairiats_rec_15, tmp110, atslab_s1exp_node, tmp111) ;

return (tmp110) ;
} /* end of [ATS_2d0_2e2_2e10_2src_2ats_staexp1_2esats__s1exp_tyarr] */

/*
// /home/hwxi/research/Anairiats/src/ats_staexp1.dats: 8235(line=322, offs=23) -- 8313(line=324, offs=2)
*/
ATSglobaldec()
ats_ptr_type
ATS_2d0_2e2_2e10_2src_2ats_staexp1_2esats__s1exp_tyrec (ats_ptr_type arg0, ats_int_type arg1, ats_ptr_type arg2) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp112) ;
ATSlocal (ats_ptr_type, tmp113) ;

__ats_lab_ATS_2d0_2e2_2e10_2src_2ats_staexp1_2esats__s1exp_tyrec:
tmp113 = ATS_MALLOC(sizeof(anairiats_sum_18)) ;
((ats_sum_ptr_type)tmp113)->tag = 16 ;
ats_selptrset_mac(anairiats_sum_18, tmp113, atslab_0, arg1) ;
ats_selptrset_mac(anairiats_sum_18, tmp113, atslab_1, arg2) ;
tmp112 = ATS_MALLOC(sizeof(anairiats_rec_15)) ;
ats_selptrset_mac(anairiats_rec_15, tmp112, atslab_s1exp_loc, arg0) ;
ats_selptrset_mac(anairiats_rec_15, tmp112, atslab_s1exp_node, tmp113) ;

return (tmp112) ;
} /* end of [ATS_2d0_2e2_2e10_2src_2ats_staexp1_2esats__s1exp_tyrec] */

/*
// /home/hwxi/research/Anairiats/src/ats_staexp1.dats: 8341(line=326, offs=27) -- 8423(line=328, offs=2)
*/
ATSglobaldec()
ats_ptr_type
ATS_2d0_2e2_2e10_2src_2ats_staexp1_2esats__s1exp_tyrec_ext (ats_ptr_type arg0, ats_ptr_type arg1, ats_ptr_type arg2) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp114) ;
ATSlocal (ats_ptr_type, tmp115) ;

__ats_lab_ATS_2d0_2e2_2e10_2src_2ats_staexp1_2esats__s1exp_tyrec_ext:
tmp115 = ATS_MALLOC(sizeof(anairiats_sum_8)) ;
((ats_sum_ptr_type)tmp115)->tag = 17 ;
ats_selptrset_mac(anairiats_sum_8, tmp115, atslab_0, arg1) ;
ats_selptrset_mac(anairiats_sum_8, tmp115, atslab_1, arg2) ;
tmp114 = ATS_MALLOC(sizeof(anairiats_rec_15)) ;
ats_selptrset_mac(anairiats_rec_15, tmp114, atslab_s1exp_loc, arg0) ;
ats_selptrset_mac(anairiats_rec_15, tmp114, atslab_s1exp_node, tmp115) ;

return (tmp114) ;
} /* end of [ATS_2d0_2e2_2e10_2src_2ats_staexp1_2esats__s1exp_tyrec_ext] */

/*
// /home/hwxi/research/Anairiats/src/ats_staexp1.dats: 8447(line=330, offs=23) -- 8523(line=332, offs=2)
*/
ATSglobaldec()
ats_ptr_type
ATS_2d0_2e2_2e10_2src_2ats_staexp1_2esats__s1exp_tytup (ats_ptr_type arg0, ats_int_type arg1, ats_ptr_type arg2) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp116) ;
ATSlocal (ats_ptr_type, tmp117) ;

__ats_lab_ATS_2d0_2e2_2e10_2src_2ats_staexp1_2esats__s1exp_tytup:
tmp117 = ATS_MALLOC(sizeof(anairiats_sum_18)) ;
((ats_sum_ptr_type)tmp117)->tag = 18 ;
ats_selptrset_mac(anairiats_sum_18, tmp117, atslab_0, arg1) ;
ats_selptrset_mac(anairiats_sum_18, tmp117, atslab_1, arg2) ;
tmp116 = ATS_MALLOC(sizeof(anairiats_rec_15)) ;
ats_selptrset_mac(anairiats_rec_15, tmp116, atslab_s1exp_loc, arg0) ;
ats_selptrset_mac(anairiats_rec_15, tmp116, atslab_s1exp_node, tmp117) ;

return (tmp116) ;
} /* end of [ATS_2d0_2e2_2e10_2src_2ats_staexp1_2esats__s1exp_tytup] */

/*
// /home/hwxi/research/Anairiats/src/ats_staexp1.dats: 8548(line=334, offs=24) -- 8641(line=336, offs=2)
*/
ATSglobaldec()
ats_ptr_type
ATS_2d0_2e2_2e10_2src_2ats_staexp1_2esats__s1exp_tytup2 (ats_ptr_type arg0, ats_int_type arg1, ats_ptr_type arg2, ats_ptr_type arg3) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp118) ;
ATSlocal (ats_ptr_type, tmp119) ;

__ats_lab_ATS_2d0_2e2_2e10_2src_2ats_staexp1_2esats__s1exp_tytup2:
tmp119 = ATS_MALLOC(sizeof(anairiats_sum_16)) ;
((ats_sum_ptr_type)tmp119)->tag = 19 ;
ats_selptrset_mac(anairiats_sum_16, tmp119, atslab_0, arg1) ;
ats_selptrset_mac(anairiats_sum_16, tmp119, atslab_1, arg2) ;
ats_selptrset_mac(anairiats_sum_16, tmp119, atslab_2, arg3) ;
tmp118 = ATS_MALLOC(sizeof(anairiats_rec_15)) ;
ats_selptrset_mac(anairiats_rec_15, tmp118, atslab_s1exp_loc, arg0) ;
ats_selptrset_mac(anairiats_rec_15, tmp118, atslab_s1exp_node, tmp119) ;

return (tmp118) ;
} /* end of [ATS_2d0_2e2_2e10_2src_2ats_staexp1_2esats__s1exp_tytup2] */

/*
// /home/hwxi/research/Anairiats/src/ats_staexp1.dats: 8663(line=338, offs=21) -- 8735(line=340, offs=2)
*/
ATSglobaldec()
ats_ptr_type
ATS_2d0_2e2_2e10_2src_2ats_staexp1_2esats__s1exp_uni (ats_ptr_type arg0, ats_ptr_type arg1, ats_ptr_type arg2) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp120) ;
ATSlocal (ats_ptr_type, tmp121) ;

__ats_lab_ATS_2d0_2e2_2e10_2src_2ats_staexp1_2esats__s1exp_uni:
tmp121 = ATS_MALLOC(sizeof(anairiats_sum_8)) ;
((ats_sum_ptr_type)tmp121)->tag = 20 ;
ats_selptrset_mac(anairiats_sum_8, tmp121, atslab_0, arg1) ;
ats_selptrset_mac(anairiats_sum_8, tmp121, atslab_1, arg2) ;
tmp120 = ATS_MALLOC(sizeof(anairiats_rec_15)) ;
ats_selptrset_mac(anairiats_rec_15, tmp120, atslab_s1exp_loc, arg0) ;
ats_selptrset_mac(anairiats_rec_15, tmp120, atslab_s1exp_node, tmp121) ;

return (tmp120) ;
} /* end of [ATS_2d0_2e2_2e10_2src_2ats_staexp1_2esats__s1exp_uni] */

/*
// /home/hwxi/research/Anairiats/src/ats_staexp1.dats: 8759(line=342, offs=23) -- 8835(line=344, offs=2)
*/
ATSglobaldec()
ats_ptr_type
ATS_2d0_2e2_2e10_2src_2ats_staexp1_2esats__s1exp_union (ats_ptr_type arg0, ats_ptr_type arg1, ats_ptr_type arg2) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp122) ;
ATSlocal (ats_ptr_type, tmp123) ;

__ats_lab_ATS_2d0_2e2_2e10_2src_2ats_staexp1_2esats__s1exp_union:
tmp123 = ATS_MALLOC(sizeof(anairiats_sum_8)) ;
((ats_sum_ptr_type)tmp123)->tag = 21 ;
ats_selptrset_mac(anairiats_sum_8, tmp123, atslab_0, arg1) ;
ats_selptrset_mac(anairiats_sum_8, tmp123, atslab_1, arg2) ;
tmp122 = ATS_MALLOC(sizeof(anairiats_rec_15)) ;
ats_selptrset_mac(anairiats_rec_15, tmp122, atslab_s1exp_loc, arg0) ;
ats_selptrset_mac(anairiats_rec_15, tmp122, atslab_s1exp_node, tmp123) ;

return (tmp122) ;
} /* end of [ATS_2d0_2e2_2e10_2src_2ats_staexp1_2esats__s1exp_union] */

/*
// /home/hwxi/research/Anairiats/src/ats_staexp1.dats: 8881(line=348, offs=24) -- 8944(line=350, offs=2)
*/
ATSglobaldec()
ats_ptr_type
ATS_2d0_2e2_2e10_2src_2ats_staexp1_2esats__s1exparg_one (ats_ptr_type arg0) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp124) ;
ATSlocal (ats_ptr_type, tmp125) ;

__ats_lab_ATS_2d0_2e2_2e10_2src_2ats_staexp1_2esats__s1exparg_one:
tmp125 = (ats_sum_ptr_type)(&ATS_2d0_2e2_2e10_2src_2ats_staexp1_2esats__S1EXPARGone) ;
tmp124 = ATS_MALLOC(sizeof(anairiats_rec_19)) ;
ats_selptrset_mac(anairiats_rec_19, tmp124, atslab_s1exparg_loc, arg0) ;
ats_selptrset_mac(anairiats_rec_19, tmp124, atslab_s1exparg_node, tmp125) ;

return (tmp124) ;
} /* end of [ATS_2d0_2e2_2e10_2src_2ats_staexp1_2esats__s1exparg_one] */

/*
// /home/hwxi/research/Anairiats/src/ats_staexp1.dats: 8969(line=352, offs=24) -- 9032(line=354, offs=2)
*/
ATSglobaldec()
ats_ptr_type
ATS_2d0_2e2_2e10_2src_2ats_staexp1_2esats__s1exparg_all (ats_ptr_type arg0) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp126) ;
ATSlocal (ats_ptr_type, tmp127) ;

__ats_lab_ATS_2d0_2e2_2e10_2src_2ats_staexp1_2esats__s1exparg_all:
tmp127 = (ats_sum_ptr_type)(&ATS_2d0_2e2_2e10_2src_2ats_staexp1_2esats__S1EXPARGall) ;
tmp126 = ATS_MALLOC(sizeof(anairiats_rec_19)) ;
ats_selptrset_mac(anairiats_rec_19, tmp126, atslab_s1exparg_loc, arg0) ;
ats_selptrset_mac(anairiats_rec_19, tmp126, atslab_s1exparg_node, tmp127) ;

return (tmp126) ;
} /* end of [ATS_2d0_2e2_2e10_2src_2ats_staexp1_2esats__s1exparg_all] */

/*
// /home/hwxi/research/Anairiats/src/ats_staexp1.dats: 9057(line=356, offs=24) -- 9128(line=358, offs=2)
*/
ATSglobaldec()
ats_ptr_type
ATS_2d0_2e2_2e10_2src_2ats_staexp1_2esats__s1exparg_seq (ats_ptr_type arg0, ats_ptr_type arg1) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp128) ;
ATSlocal (ats_ptr_type, tmp129) ;

__ats_lab_ATS_2d0_2e2_2e10_2src_2ats_staexp1_2esats__s1exparg_seq:
tmp129 = ATS_MALLOC(sizeof(anairiats_sum_4)) ;
((ats_sum_ptr_type)tmp129)->tag = 2 ;
ats_selptrset_mac(anairiats_sum_4, tmp129, atslab_0, arg1) ;
tmp128 = ATS_MALLOC(sizeof(anairiats_rec_19)) ;
ats_selptrset_mac(anairiats_rec_19, tmp128, atslab_s1exparg_loc, arg0) ;
ats_selptrset_mac(anairiats_rec_19, tmp128, atslab_s1exparg_node, tmp129) ;

return (tmp128) ;
} /* end of [ATS_2d0_2e2_2e10_2src_2ats_staexp1_2esats__s1exparg_seq] */

/*
// /home/hwxi/research/Anairiats/src/ats_staexp1.dats: 9173(line=362, offs=23) -- 9236(line=364, offs=2)
*/
ATSglobaldec()
ats_ptr_type
ATS_2d0_2e2_2e10_2src_2ats_staexp1_2esats__s1rtext_srt (ats_ptr_type arg0, ats_ptr_type arg1) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp130) ;
ATSlocal (ats_ptr_type, tmp131) ;

__ats_lab_ATS_2d0_2e2_2e10_2src_2ats_staexp1_2esats__s1rtext_srt:
tmp131 = ATS_MALLOC(sizeof(anairiats_sum_4)) ;
((ats_sum_ptr_type)tmp131)->tag = 0 ;
ats_selptrset_mac(anairiats_sum_4, tmp131, atslab_0, arg1) ;
tmp130 = ATS_MALLOC(sizeof(anairiats_rec_20)) ;
ats_selptrset_mac(anairiats_rec_20, tmp130, atslab_s1rtext_loc, arg0) ;
ats_selptrset_mac(anairiats_rec_20, tmp130, atslab_s1rtext_node, tmp131) ;

return (tmp130) ;
} /* end of [ATS_2d0_2e2_2e10_2src_2ats_staexp1_2esats__s1rtext_srt] */

/*
// /home/hwxi/research/Anairiats/src/ats_staexp1.dats: 9260(line=366, offs=23) -- 9347(line=368, offs=2)
*/
ATSglobaldec()
ats_ptr_type
ATS_2d0_2e2_2e10_2src_2ats_staexp1_2esats__s1rtext_sub (ats_ptr_type arg0, ats_ptr_type arg1, ats_ptr_type arg2, ats_ptr_type arg3) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp132) ;
ATSlocal (ats_ptr_type, tmp133) ;

__ats_lab_ATS_2d0_2e2_2e10_2src_2ats_staexp1_2esats__s1rtext_sub:
tmp133 = ATS_MALLOC(sizeof(anairiats_sum_2)) ;
((ats_sum_ptr_type)tmp133)->tag = 1 ;
ats_selptrset_mac(anairiats_sum_2, tmp133, atslab_0, arg1) ;
ats_selptrset_mac(anairiats_sum_2, tmp133, atslab_1, arg2) ;
ats_selptrset_mac(anairiats_sum_2, tmp133, atslab_2, arg3) ;
tmp132 = ATS_MALLOC(sizeof(anairiats_rec_20)) ;
ats_selptrset_mac(anairiats_rec_20, tmp132, atslab_s1rtext_loc, arg0) ;
ats_selptrset_mac(anairiats_rec_20, tmp132, atslab_s1rtext_node, tmp133) ;

return (tmp132) ;
} /* end of [ATS_2d0_2e2_2e10_2src_2ats_staexp1_2esats__s1rtext_sub] */

/*
// /home/hwxi/research/Anairiats/src/ats_staexp1.dats: 9633(line=386, offs=22) -- 9692(line=387, offs=47)
*/
ATSglobaldec()
ats_ptr_type
ATS_2d0_2e2_2e10_2src_2ats_staexp1_2esats__s1qua_prop (ats_ptr_type arg0, ats_ptr_type arg1) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp134) ;
ATSlocal (ats_ptr_type, tmp135) ;

__ats_lab_ATS_2d0_2e2_2e10_2src_2ats_staexp1_2esats__s1qua_prop:
tmp135 = ATS_MALLOC(sizeof(anairiats_sum_4)) ;
((ats_sum_ptr_type)tmp135)->tag = 0 ;
ats_selptrset_mac(anairiats_sum_4, tmp135, atslab_0, arg1) ;
tmp134 = ATS_MALLOC(sizeof(anairiats_rec_21)) ;
ats_selptrset_mac(anairiats_rec_21, tmp134, atslab_s1qua_loc, arg0) ;
ats_selptrset_mac(anairiats_rec_21, tmp134, atslab_s1qua_node, tmp135) ;

return (tmp134) ;
} /* end of [ATS_2d0_2e2_2e10_2src_2ats_staexp1_2esats__s1qua_prop] */

/*
// /home/hwxi/research/Anairiats/src/ats_staexp1.dats: 9715(line=389, offs=22) -- 9788(line=390, offs=55)
*/
ATSglobaldec()
ats_ptr_type
ATS_2d0_2e2_2e10_2src_2ats_staexp1_2esats__s1qua_vars (ats_ptr_type arg0, ats_ptr_type arg1, ats_ptr_type arg2) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp136) ;
ATSlocal (ats_ptr_type, tmp137) ;

__ats_lab_ATS_2d0_2e2_2e10_2src_2ats_staexp1_2esats__s1qua_vars:
tmp137 = ATS_MALLOC(sizeof(anairiats_sum_8)) ;
((ats_sum_ptr_type)tmp137)->tag = 1 ;
ats_selptrset_mac(anairiats_sum_8, tmp137, atslab_0, arg1) ;
ats_selptrset_mac(anairiats_sum_8, tmp137, atslab_1, arg2) ;
tmp136 = ATS_MALLOC(sizeof(anairiats_rec_21)) ;
ats_selptrset_mac(anairiats_rec_21, tmp136, atslab_s1qua_loc, arg0) ;
ats_selptrset_mac(anairiats_rec_21, tmp136, atslab_s1qua_node, tmp137) ;

return (tmp136) ;
} /* end of [ATS_2d0_2e2_2e10_2src_2ats_staexp1_2esats__s1qua_vars] */

/*
// /home/hwxi/research/Anairiats/src/ats_staexp1.dats: 9859(line=396, offs=5) -- 10357(line=409, offs=8)
*/
ATSstaticdec()
ats_ptr_type
aux_59 (ats_ptr_type env0, ats_ptr_type arg0) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp139) ;
ATSlocal (ats_ptr_type, tmp140) ;
ATSlocal (ats_ptr_type, tmp141) ;
ATSlocal (ats_ptr_type, tmp142) ;
ATSlocal (ats_ptr_type, tmp143) ;
ATSlocal (ats_ptr_type, tmp144) ;
ATSlocal (ats_ptr_type, tmp145) ;
ATSlocal (ats_ptr_type, tmp146) ;
ATSlocal (ats_char_type, tmp147) ;
ATSlocal (ats_ptr_type, tmp148) ;
ATSlocal (ats_ptr_type, tmp149) ;
ATSlocal (ats_ptr_type, tmp150) ;
// ATSlocal_void (tmp151) ;
// ATSlocal_void (tmp152) ;
// ATSlocal_void (tmp153) ;
// ATSlocal_void (tmp154) ;

__ats_lab_aux_59:
tmp140 = ats_selbox_mac(ats_castptr_mac(anairiats_rec_1, arg0), atslab_e1xp_node) ;
do {
/* branch: __ats_lab_12 */
__ats_lab_12_0:
if (((ats_sum_ptr_type)tmp140)->tag != 0) { goto __ats_lab_13_0 ; }
__ats_lab_12_1:
tmp141 = ats_caselptrlab_mac(anairiats_sum_2, tmp140, atslab_0) ;
tmp142 = ats_caselptrlab_mac(anairiats_sum_2, tmp140, atslab_1) ;
tmp143 = ats_caselptrlab_mac(anairiats_sum_2, tmp140, atslab_2) ;
tmp144 = aux_59 (env0, tmp141) ;
tmp145 = aux_list_60 (env0, tmp143) ;
tmp139 = ATS_2d0_2e2_2e10_2src_2ats_staexp1_2esats__s1exp_app (env0, tmp144, tmp142, tmp145) ;
break ;

/* branch: __ats_lab_13 */
__ats_lab_13_0:
if (((ats_sum_ptr_type)tmp140)->tag != 3) { goto __ats_lab_14_0 ; }
__ats_lab_13_1:
tmp146 = ats_caselptrlab_mac(anairiats_sum_4, tmp140, atslab_0) ;
tmp139 = ATS_2d0_2e2_2e10_2src_2ats_staexp1_2esats__s1exp_ide (env0, tmp146) ;
break ;

/* branch: __ats_lab_14 */
__ats_lab_14_0:
if (((ats_sum_ptr_type)tmp140)->tag != 1) { goto __ats_lab_15_0 ; }
__ats_lab_14_1:
tmp147 = ats_caselptrlab_mac(anairiats_sum_3, tmp140, atslab_0) ;
tmp139 = ATS_2d0_2e2_2e10_2src_2ats_staexp1_2esats__s1exp_char (env0, tmp147) ;
break ;

/* branch: __ats_lab_15 */
__ats_lab_15_0:
if (((ats_sum_ptr_type)tmp140)->tag != 4) { goto __ats_lab_16_0 ; }
__ats_lab_15_1:
tmp148 = ats_caselptrlab_mac(anairiats_sum_4, tmp140, atslab_0) ;
tmp139 = ATS_2d0_2e2_2e10_2src_2ats_staexp1_2esats__s1exp_int (env0, tmp148) ;
break ;

/* branch: __ats_lab_16 */
__ats_lab_16_0:
if (((ats_sum_ptr_type)tmp140)->tag != 5) { goto __ats_lab_17_0 ; }
__ats_lab_16_1:
tmp149 = ats_caselptrlab_mac(anairiats_sum_4, tmp140, atslab_0) ;
tmp150 = aux_list_60 (env0, tmp149) ;
tmp139 = ATS_2d0_2e2_2e10_2src_2ats_staexp1_2esats__s1exp_list (env0, tmp150) ;
break ;

/* branch: __ats_lab_17 */
__ats_lab_17_0:
__ats_lab_17_1:
/* tmp151 = */ ATS_2d0_2e2_2e10_2src_2ats_location_2esats__prerr_location (env0) ;
/* tmp152 = */ atspre_prerr_string (ATSstrcst("INTERNAL ERROR (ats_staexp1)")) ;
/* tmp153 = */ atspre_prerr_string (ATSstrcst(": illegal static expression.")) ;
/* tmp154 = */ atspre_prerr_newline () ;
/* tmp139 = */ ATS_2d0_2e2_2e10_2src_2ats_error_2esats__abort () ;
break ;
} while (0) ;
return (tmp139) ;
} /* end of [aux_59] */

typedef struct {
ats_fun_ptr_type closure_fun ;
ats_ptr_type closure_env_0 ;
} aux_59_closure_type ;

ats_ptr_type
aux_59_clofun (ats_clo_ptr_type cloptr, ats_ptr_type arg0) {
return aux_59 (((aux_59_closure_type*)cloptr)->closure_env_0, arg0) ;
} /* end of function */

ATSinline()
ats_void_type
aux_59_closure_init (aux_59_closure_type *p_clo, ats_ptr_type env0) {
p_clo->closure_fun = (ats_fun_ptr_type)&aux_59_clofun ;
p_clo->closure_env_0 = env0 ;
return ;
} /* end of function */

ats_clo_ptr_type
aux_59_closure_make (ats_ptr_type env0) {
aux_59_closure_type *p_clo = ATS_MALLOC(sizeof(aux_59_closure_type)) ;
aux_59_closure_init (p_clo, env0) ;
return (ats_clo_ptr_type)p_clo ;
} /* end of function */

/*
// /home/hwxi/research/Anairiats/src/ats_staexp1.dats: 10393(line=412, offs=5) -- 10515(line=413, offs=65)
*/
ATSstaticdec()
ats_ptr_type
aux_list_60 (ats_ptr_type env0, ats_ptr_type arg0) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp155) ;
ATSlocal (ats_ptr_type, tmp156) ;
ATSlocal (ats_ptr_type, tmp157) ;
ATSlocal (ats_ptr_type, tmp158) ;
ATSlocal (ats_ptr_type, tmp159) ;

__ats_lab_aux_list_60:
do {
/* branch: __ats_lab_18 */
__ats_lab_18_0:
if (arg0 == (ats_sum_ptr_type)0) { goto __ats_lab_19_0 ; }
__ats_lab_18_1:
tmp156 = ats_caselptrlab_mac(anairiats_sum_9, arg0, atslab_0) ;
tmp157 = ats_caselptrlab_mac(anairiats_sum_9, arg0, atslab_1) ;
tmp158 = aux_59 (env0, tmp156) ;
tmp159 = aux_list_60 (env0, tmp157) ;
tmp155 = ATS_MALLOC(sizeof(anairiats_sum_9)) ;
ats_selptrset_mac(anairiats_sum_9, tmp155, atslab_0, tmp158) ;
ats_selptrset_mac(anairiats_sum_9, tmp155, atslab_1, tmp159) ;
break ;

/* branch: __ats_lab_19 */
__ats_lab_19_0:
// if (arg0 != (ats_sum_ptr_type)0) { ats_deadcode_failure_handle () ; }
__ats_lab_19_1:
tmp155 = (ats_sum_ptr_type)0 ;
break ;
} while (0) ;
return (tmp155) ;
} /* end of [aux_list_60] */

typedef struct {
ats_fun_ptr_type closure_fun ;
ats_ptr_type closure_env_0 ;
} aux_list_60_closure_type ;

ats_ptr_type
aux_list_60_clofun (ats_clo_ptr_type cloptr, ats_ptr_type arg0) {
return aux_list_60 (((aux_list_60_closure_type*)cloptr)->closure_env_0, arg0) ;
} /* end of function */

ATSinline()
ats_void_type
aux_list_60_closure_init (aux_list_60_closure_type *p_clo, ats_ptr_type env0) {
p_clo->closure_fun = (ats_fun_ptr_type)&aux_list_60_clofun ;
p_clo->closure_env_0 = env0 ;
return ;
} /* end of function */

ats_clo_ptr_type
aux_list_60_closure_make (ats_ptr_type env0) {
aux_list_60_closure_type *p_clo = ATS_MALLOC(sizeof(aux_list_60_closure_type)) ;
aux_list_60_closure_init (p_clo, env0) ;
return (ats_clo_ptr_type)p_clo ;
} /* end of function */

/*
// /home/hwxi/research/Anairiats/src/ats_staexp1.dats: 9837(line=394, offs=27) -- 10553(line=418, offs=4)
*/
ATSglobaldec()
ats_ptr_type
ATS_2d0_2e2_2e10_2src_2ats_staexp1_2esats__s1exp_make_e1xp (ats_ptr_type arg0, ats_ptr_type arg1) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp138) ;

__ats_lab_ATS_2d0_2e2_2e10_2src_2ats_staexp1_2esats__s1exp_make_e1xp:
tmp138 = aux_59 (arg0, arg1) ;
return (tmp138) ;
} /* end of [ATS_2d0_2e2_2e10_2src_2ats_staexp1_2esats__s1exp_make_e1xp] */

/*
// /home/hwxi/research/Anairiats/src/ats_staexp1.dats: 10634(line=422, offs=31) -- 10806(line=426, offs=4)
*/
ATSglobaldec()
ats_bool_type
ATS_2d0_2e2_2e10_2src_2ats_staexp1_2esats__wths1explst_is_none (ats_ptr_type arg0) {
/* local vardec */
ATSlocal (ats_bool_type, tmp160) ;
ATSlocal (ats_ptr_type, tmp161) ;

__ats_lab_ATS_2d0_2e2_2e10_2src_2ats_staexp1_2esats__wths1explst_is_none:
do {
/* branch: __ats_lab_20 */
__ats_lab_20_0:
if (((ats_sum_ptr_type)arg0)->tag != 1) { goto __ats_lab_21_0 ; }
__ats_lab_20_1:
tmp160 = ats_false_bool ;
break ;

/* branch: __ats_lab_21 */
__ats_lab_21_0:
if (((ats_sum_ptr_type)arg0)->tag != 2) { goto __ats_lab_22_0 ; }
__ats_lab_21_1:
tmp161 = ats_caselptrlab_mac(anairiats_sum_4, arg0, atslab_0) ;
arg0 = tmp161 ;
goto __ats_lab_ATS_2d0_2e2_2e10_2src_2ats_staexp1_2esats__wths1explst_is_none ; // tail call
break ;

/* branch: __ats_lab_22 */
__ats_lab_22_0:
// if (((ats_sum_ptr_type)arg0)->tag != 0) { ats_deadcode_failure_handle () ; }
__ats_lab_22_1:
tmp160 = ats_true_bool ;
break ;
} while (0) ;
return (tmp160) ;
} /* end of [ATS_2d0_2e2_2e10_2src_2ats_staexp1_2esats__wths1explst_is_none] */

/*
// /home/hwxi/research/Anairiats/src/ats_staexp1.dats: 10892(line=429, offs=7) -- 11253(line=439, offs=31)
*/
ATSstaticdec()
ats_ptr_type
aux_63 (ats_ptr_type arg0, ats_ptr_type arg1) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp163) ;
ATSlocal (ats_int_type, tmp164) ;
ATSlocal (ats_ptr_type, tmp165) ;
ATSlocal (ats_ptr_type, tmp166) ;
ATSlocal (ats_ptr_type, tmp167) ;
ATSlocal (ats_ptr_type, tmp168) ;
ATSlocal (ats_ptr_type, tmp169) ;

__ats_lab_aux_63:
do {
/* branch: __ats_lab_23 */
__ats_lab_23_0:
if (((ats_sum_ptr_type)arg0)->tag != 1) { goto __ats_lab_24_0 ; }
__ats_lab_23_1:
tmp164 = ats_caselptrlab_mac(anairiats_sum_16, arg0, atslab_0) ;
tmp165 = ats_caselptrlab_mac(anairiats_sum_16, arg0, atslab_1) ;
tmp166 = ats_caselptrlab_mac(anairiats_sum_16, arg0, atslab_2) ;
tmp167 = ATS_MALLOC(sizeof(anairiats_sum_16)) ;
((ats_sum_ptr_type)tmp167)->tag = 1 ;
ats_selptrset_mac(anairiats_sum_16, tmp167, atslab_0, tmp164) ;
ats_selptrset_mac(anairiats_sum_16, tmp167, atslab_1, tmp165) ;
ats_selptrset_mac(anairiats_sum_16, tmp167, atslab_2, arg1) ;
arg0 = tmp166 ;
arg1 = tmp167 ;
goto __ats_lab_aux_63 ; // tail call
break ;

/* branch: __ats_lab_24 */
__ats_lab_24_0:
if (((ats_sum_ptr_type)arg0)->tag != 2) { goto __ats_lab_25_0 ; }
__ats_lab_24_1:
tmp168 = ats_caselptrlab_mac(anairiats_sum_4, arg0, atslab_0) ;
tmp169 = ATS_MALLOC(sizeof(anairiats_sum_4)) ;
((ats_sum_ptr_type)tmp169)->tag = 2 ;
ats_selptrset_mac(anairiats_sum_4, tmp169, atslab_0, arg1) ;
arg0 = tmp168 ;
arg1 = tmp169 ;
goto __ats_lab_aux_63 ; // tail call
break ;

/* branch: __ats_lab_25 */
__ats_lab_25_0:
// if (((ats_sum_ptr_type)arg0)->tag != 0) { ats_deadcode_failure_handle () ; }
__ats_lab_25_1:
tmp163 = arg1 ;
break ;
} while (0) ;
return (tmp163) ;
} /* end of [aux_63] */

/*
// /home/hwxi/research/Anairiats/src/ats_staexp1.dats: 10870(line=428, offs=31) -- 11340(line=443, offs=4)
*/
ATSglobaldec()
ats_ptr_type
ATS_2d0_2e2_2e10_2src_2ats_staexp1_2esats__wths1explst_reverse (ats_ptr_type arg0) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp162) ;
ATSlocal (ats_ptr_type, tmp170) ;

__ats_lab_ATS_2d0_2e2_2e10_2src_2ats_staexp1_2esats__wths1explst_reverse:
tmp170 = (ats_sum_ptr_type)(&ATS_2d0_2e2_2e10_2src_2ats_staexp1_2esats__WTHS1EXPLSTnil) ;
tmp162 = aux_63 (arg0, tmp170) ;
return (tmp162) ;
} /* end of [ATS_2d0_2e2_2e10_2src_2ats_staexp1_2esats__wths1explst_reverse] */

/* static load function */

extern ats_void_type ATS_2d0_2e2_2e10_2src_2ats_error_2esats__staload (void) ;
extern ats_void_type ATS_2d0_2e2_2e10_2src_2ats_location_2esats__staload (void) ;
extern ats_void_type ATS_2d0_2e2_2e10_2src_2ats_list_2esats__staload (void) ;
extern ats_void_type ATS_2d0_2e2_2e10_2src_2ats_symbol_2esats__staload (void) ;
extern ats_void_type ATS_2d0_2e2_2e10_2src_2ats_syntax_2esats__staload (void) ;
extern ats_void_type ATS_2d0_2e2_2e10_2src_2ats_staexp1_2esats__staload (void) ;

ats_void_type
ATS_2d0_2e2_2e10_2src_2ats_staexp1_2edats__staload () {
static int ATS_2d0_2e2_2e10_2src_2ats_staexp1_2edats__staload_flag = 0 ;
if (ATS_2d0_2e2_2e10_2src_2ats_staexp1_2edats__staload_flag) return ;
ATS_2d0_2e2_2e10_2src_2ats_staexp1_2edats__staload_flag = 1 ;

ATS_2d0_2e2_2e10_2src_2ats_error_2esats__staload () ;
ATS_2d0_2e2_2e10_2src_2ats_location_2esats__staload () ;
ATS_2d0_2e2_2e10_2src_2ats_list_2esats__staload () ;
ATS_2d0_2e2_2e10_2src_2ats_symbol_2esats__staload () ;
ATS_2d0_2e2_2e10_2src_2ats_syntax_2esats__staload () ;
ATS_2d0_2e2_2e10_2src_2ats_staexp1_2esats__staload () ;

return ;
} /* staload function */

/* dynamic load function */

// dynload flag declaration
extern ats_int_type ATS_2d0_2e2_2e10_2src_2ats_staexp1_2edats__dynload_flag ;

ats_void_type
ATS_2d0_2e2_2e10_2src_2ats_staexp1_2edats__dynload () {
ATS_2d0_2e2_2e10_2src_2ats_staexp1_2edats__dynload_flag = 1 ;
ATS_2d0_2e2_2e10_2src_2ats_staexp1_2edats__staload () ;

#ifdef _ATS_PROOFCHECK
#endif /* _ATS_PROOFCHECK */

/* marking static variables for GC */
ATS_GC_MARKROOT(&statmp0, sizeof(ats_ptr_type)) ;
ATS_GC_MARKROOT(&statmp1, sizeof(ats_ptr_type)) ;
ATS_GC_MARKROOT(&statmp26, sizeof(ats_ptr_type)) ;
ATS_GC_MARKROOT(&statmp27, sizeof(ats_ptr_type)) ;

/* marking external values for GC */

/* code for dynamic loading */
statmp0 = s0rtq_none () ;
statmp1 = s0taq_none () ;
statmp26 = ATS_MALLOC(sizeof(anairiats_sum_6)) ;
((ats_sum_ptr_type)statmp26)->tag = 2 ;
ats_selptrset_mac(anairiats_sum_6, statmp26, atslab_0, 1) ;
ATS_GC_MARKROOT(&ATS_2d0_2e2_2e10_2src_2ats_staexp1_2esats__v1al_true, sizeof(ats_ptr_type)) ;
ATS_2d0_2e2_2e10_2src_2ats_staexp1_2esats__v1al_true = statmp26 ;
statmp27 = ATS_MALLOC(sizeof(anairiats_sum_6)) ;
((ats_sum_ptr_type)statmp27)->tag = 2 ;
ats_selptrset_mac(anairiats_sum_6, statmp27, atslab_0, 0) ;
ATS_GC_MARKROOT(&ATS_2d0_2e2_2e10_2src_2ats_staexp1_2esats__v1al_false, sizeof(ats_ptr_type)) ;
ATS_2d0_2e2_2e10_2src_2ats_staexp1_2esats__v1al_false = statmp27 ;
return ;
} /* end of [dynload function] */

/* external codes at mid */
/* external codes at bot */

/* ****** ****** */

/* end of [/home/hwxi/research/Anairiats/bootstrap1/ats_staexp1_dats.c] */
