/*
**
** The C code is generated by ATS/Anairiats
** The compilation time is: 2016-8-25: 20h:18m
**
*/

/* include some .h files */
#ifndef _ATS_HEADER_NONE
#include "ats_config.h"
#include "ats_basics.h"
#include "ats_types.h"
#include "ats_exception.h"
#include "ats_memory.h"
#endif /* _ATS_HEADER_NONE */

/* include some .cats files */
#ifndef _ATS_PRELUDE_NONE
#include "prelude/CATS/basics.cats"
#include "prelude/CATS/bool.cats"
#include "prelude/CATS/char.cats"
#include "prelude/CATS/byte.cats"
#include "prelude/CATS/float.cats"
#include "prelude/CATS/integer.cats"
#include "prelude/CATS/integer_ptr.cats"
#include "prelude/CATS/integer_fixed.cats"
#include "prelude/CATS/sizetype.cats"
#include "prelude/CATS/pointer.cats"
#include "prelude/CATS/reference.cats"
#include "prelude/CATS/string.cats"
#include "prelude/CATS/lazy.cats"
#include "prelude/CATS/lazy_vt.cats"
#include "prelude/CATS/printf.cats"
#include "prelude/CATS/list.cats"
#include "prelude/CATS/option.cats"
#include "prelude/CATS/array.cats"
#include "prelude/CATS/matrix.cats"
#endif /* _ATS_PRELUDE_NONE */
/* prologues from statically loaded files */

#include "ats_counter.cats"

#include "ats_intinf.cats"

#include "ats_counter.cats"

#include "ats_intinf.cats"

#include "ats_counter.cats"

#include "ats_counter.cats"

#include "ats_intinf.cats"

#include "ats_counter.cats"

#include "ats_counter.cats"

#include "ats_intinf.cats"

#include "ats_counter.cats"

#include "ats_intinf.cats"

#include "ats_counter.cats"

#include "ats_counter.cats"

#include "ats_intinf.cats"

#include "ats_counter.cats"

#include "ats_counter.cats"

#include "ats_intinf.cats"

#include "ats_counter.cats"

#include "ats_intinf.cats"

#include "ats_counter.cats"

#include "ats_counter.cats"

#include "ats_intinf.cats"

#include "ats_counter.cats"

#include "ats_counter.cats"

#include "ats_intinf.cats"

#include "ats_counter.cats"

#include "ats_intinf.cats"

#include "ats_counter.cats"

#include "ats_counter.cats"

#include "ats_intinf.cats"

#include "ats_counter.cats"

#include "ats_counter.cats"

#include "ats_intinf.cats"

#include "ats_counter.cats"

#include "ats_intinf.cats"

#include "ats_counter.cats"

#include "ats_counter.cats"

#include "ats_intinf.cats"

#include "ats_counter.cats"

#include "ats_counter.cats"

#include "ats_intinf.cats"

#include "ats_counter.cats"

#include "ats_intinf.cats"

#include "ats_counter.cats"

#include "ats_counter.cats"

#include "ats_intinf.cats"

#include "ats_counter.cats"
/* external codes at top */
/* type definitions */
typedef struct {
ats_ptr_type atslab_0 ;
ats_ptr_type atslab_1 ;
} anairiats_sum_0 ;

typedef struct {
int tag ;
ats_ptr_type atslab_0 ;
} anairiats_sum_1 ;

typedef struct {
int tag ;
ats_ptr_type atslab_0 ;
ats_ptr_type atslab_1 ;
ats_ptr_type atslab_2 ;
ats_ptr_type atslab_3 ;
} anairiats_sum_2 ;

typedef struct {
ats_ptr_type atslab_0 ;
} anairiats_sum_3 ;

/* external typedefs */
/* external dynamic constructor declarations */
ATSextern_val(ats_sum_type, ATS_2d0_2e2_2e12_2prelude_2basics_sta_2esats__list_cons_0) ;
ATSextern_val(ats_sum_type, ATS_2d0_2e2_2e12_2prelude_2basics_sta_2esats__list_nil_1) ;
ATSextern_val(ats_sum_type, ATS_2d0_2e2_2e12_2prelude_2basics_sta_2esats__None_vt_0) ;
ATSextern_val(ats_sum_type, ATS_2d0_2e2_2e12_2prelude_2basics_sta_2esats__Some_vt_1) ;
ATSextern_val(ats_sum_type, ATS_2d0_2e2_2e12_2src_2ats_trans3_env_2esats__LMLPlam_0) ;
ATSextern_val(ats_sum_type, ATS_2d0_2e2_2e12_2src_2ats_trans3_env_2esats__LMLPloop0_1) ;
ATSextern_val(ats_sum_type, ATS_2d0_2e2_2e12_2src_2ats_trans3_env_2esats__LMLPloop1_2) ;
ATSextern_val(ats_sum_type, ATS_2d0_2e2_2e12_2src_2ats_trans3_env_2esats__LMLPnone_3) ;

/* external dynamic constant declarations */
ATSextern_fun(ats_void_type, atspre_prerr_newline) () ;
ATSextern_fun(ats_void_type, atspre_prerr_string) (ats_ptr_type) ;
ATSextern_fun(ats_varet_type, ATS_2d0_2e2_2e12_2src_2ats_error_2esats__abort) () ;
ATSextern_fun(ats_ptr_type, atspre_ref_make_elt_tsz) (ats_ref_type, ats_size_type) ;
ATSextern_fun(ats_ptr_type, atspre_ref_get_view_ptr) (ats_ptr_type) ;

/* external dynamic terminating constant declarations */
#ifdef _ATS_PROOFCHECK
#endif /* _ATS_PROOFCHECK */

/* assuming abstract types */
int ATS_2d0_2e2_2e12_2src_2ats_trans3_env_2esats__sasp__lamloop_env_token = 0 ;

/* sum constructor declarations */
/* exn constructor declarations */
/* global dynamic (non-functional) constant declarations */
/* internal function declarations */
static
ats_ptr_type ref_make_elt_03658_ats_ptr_type (ats_ptr_type arg0) ;
static
ats_void_type the_lamloop_env_push_3 (ats_ptr_type arg0) ;
static
ats_ptr_type aux_8 (ats_ptr_type arg0) ;

/* partial value template declarations */
/* static temporary variable declarations */
ATSstatic (ats_ptr_type, statmp0) ;
ATSstatic (ats_ptr_type, statmp3) ;
ATSstatic (ats_ptr_type, statmp4) ;
ATSstatic (ats_ptr_type, statmp5) ;

/* external value variable declarations */

/* function implementations */

/*
// /home/hwxi/Research/ATS-Anairiats/src/ats_reference.dats: 1888(line=57, offs=27) -- 1962(line=59, offs=4)
*/
ATSstaticdec()
ats_ptr_type
ref_make_elt_03658_ats_ptr_type (ats_ptr_type arg0) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp1) ;
ATSlocal (ats_ptr_type, tmp2) ;

__ats_lab_ref_make_elt_03658_ats_ptr_type:
/* ats_ptr_type tmp2 ; */
tmp2 = arg0 ;
tmp1 = atspre_ref_make_elt_tsz ((&tmp2), sizeof(ats_ptr_type)) ;
return (tmp1) ;
} /* end of [ref_make_elt_03658_ats_ptr_type] */

/*
// /home/hwxi/Research/ATS-Anairiats/src/ats_trans3_env_loop.dats: 1973(line=60, offs=31) -- 1990(line=60, offs=48)
*/
ATSglobaldec()
ats_ptr_type
ATS_2d0_2e2_2e12_2src_2ats_trans3_env_2esats__the_lamloop_env_top () {
/* local vardec */
ATSlocal (ats_ptr_type, tmp6) ;

__ats_lab_ATS_2d0_2e2_2e12_2src_2ats_trans3_env_2esats__the_lamloop_env_top:
tmp6 = ats_ptrget_mac(ats_ptr_type, statmp0) ;
return (tmp6) ;
} /* end of [ATS_2d0_2e2_2e12_2src_2ats_trans3_env_2esats__the_lamloop_env_top] */

/*
// /home/hwxi/Research/ATS-Anairiats/src/ats_trans3_env_loop.dats: 2043(line=64, offs=31) -- 2423(line=74, offs=4)
*/
ATSglobaldec()
ats_void_type
ATS_2d0_2e2_2e12_2src_2ats_trans3_env_2esats__the_lamloop_env_pop () {
/* local vardec */
// ATSlocal_void (tmp7) ;
ATSlocal (ats_ptr_type, tmp8) ;
ATSlocal (ats_ptr_type, tmp9) ;
ATSlocal (ats_ptr_type, tmp10) ;
// ATSlocal_void (tmp11) ;
// ATSlocal_void (tmp12) ;
// ATSlocal_void (tmp13) ;

__ats_lab_ATS_2d0_2e2_2e12_2src_2ats_trans3_env_2esats__the_lamloop_env_pop:
tmp8 = ats_ptrget_mac(ats_ptr_type, statmp4) ;
do {
/* branch: __ats_lab_0 */
__ats_lab_0_0:
if (tmp8 == (ats_sum_ptr_type)0) { goto __ats_lab_1_0 ; }
__ats_lab_0_1:
tmp9 = ats_caselptrlab_mac(anairiats_sum_0, tmp8, atslab_0) ;
tmp10 = ats_caselptrlab_mac(anairiats_sum_0, tmp8, atslab_1) ;
ats_ptrget_mac(ats_ptr_type, statmp0) = tmp9 ;
ats_ptrget_mac(ats_ptr_type, statmp4) = tmp10 ;
break ;

/* branch: __ats_lab_1 */
__ats_lab_1_0:
// if (tmp8 != (ats_sum_ptr_type)0) { ats_deadcode_failure_handle () ; }
__ats_lab_1_1:
/* tmp11 = */ atspre_prerr_string (ATSstrcst("INTERNAL ERROR (ats_trans3_env_loop)")) ;
/* tmp12 = */ atspre_prerr_string (ATSstrcst(": the_lamloop_env_pop")) ;
/* tmp13 = */ atspre_prerr_newline () ;
/* tmp7 = */ ATS_2d0_2e2_2e12_2src_2ats_error_2esats__abort () ;
break ;
} while (0) ;
return /* (tmp7) */ ;
} /* end of [ATS_2d0_2e2_2e12_2src_2ats_trans3_env_2esats__the_lamloop_env_pop] */

/*
// /home/hwxi/Research/ATS-Anairiats/src/ats_trans3_env_loop.dats: 2481(line=78, offs=4) -- 2663(line=83, offs=4)
*/
ATSstaticdec()
ats_void_type
the_lamloop_env_push_3 (ats_ptr_type arg0) {
/* local vardec */
// ATSlocal_void (tmp14) ;
ATSlocal (ats_ptr_type, tmp15) ;
ATSlocal (ats_ptr_type, tmp16) ;
ATSlocal (ats_ptr_type, tmp17) ;

__ats_lab_the_lamloop_env_push_3:
tmp16 = ats_ptrget_mac(ats_ptr_type, statmp0) ;
tmp17 = ats_ptrget_mac(ats_ptr_type, statmp4) ;
tmp15 = ATS_MALLOC(sizeof(anairiats_sum_0)) ;
ats_selptrset_mac(anairiats_sum_0, tmp15, atslab_0, tmp16) ;
ats_selptrset_mac(anairiats_sum_0, tmp15, atslab_1, tmp17) ;
ats_ptrget_mac(ats_ptr_type, statmp4) = tmp15 ;
ats_ptrget_mac(ats_ptr_type, statmp0) = arg0 ;
return /* (tmp14) */ ;
} /* end of [the_lamloop_env_push_3] */

/*
// /home/hwxi/Research/ATS-Anairiats/src/ats_trans3_env_loop.dats: 2733(line=85, offs=36) -- 2789(line=87, offs=4)
*/
ATSglobaldec()
ats_void_type
ATS_2d0_2e2_2e12_2src_2ats_trans3_env_2esats__the_lamloop_env_push_lam (ats_ptr_type arg0) {
/* local vardec */
// ATSlocal_void (tmp18) ;
ATSlocal (ats_ptr_type, tmp19) ;

__ats_lab_ATS_2d0_2e2_2e12_2src_2ats_trans3_env_2esats__the_lamloop_env_push_lam:
tmp19 = ATS_MALLOC(sizeof(anairiats_sum_1)) ;
((ats_sum_ptr_type)tmp19)->tag = 0 ;
ats_selptrset_mac(anairiats_sum_1, tmp19, atslab_0, arg0) ;
/* tmp18 = */ the_lamloop_env_push_3 (tmp19) ;
return /* (tmp18) */ ;
} /* end of [ATS_2d0_2e2_2e12_2src_2ats_trans3_env_2esats__the_lamloop_env_push_lam] */

/*
// /home/hwxi/Research/ATS-Anairiats/src/ats_trans3_env_loop.dats: 2865(line=89, offs=38) -- 2917(line=91, offs=4)
*/
ATSglobaldec()
ats_void_type
ATS_2d0_2e2_2e12_2src_2ats_trans3_env_2esats__the_lamloop_env_push_loop0 () {
/* local vardec */
// ATSlocal_void (tmp20) ;
ATSlocal (ats_ptr_type, tmp21) ;

__ats_lab_ATS_2d0_2e2_2e12_2src_2ats_trans3_env_2esats__the_lamloop_env_push_loop0:
tmp21 = (ats_sum_ptr_type)(&ATS_2d0_2e2_2e12_2src_2ats_trans3_env_2esats__LMLPloop0_1) ;
/* tmp20 = */ the_lamloop_env_push_3 (tmp21) ;
return /* (tmp20) */ ;
} /* end of [ATS_2d0_2e2_2e12_2src_2ats_trans3_env_2esats__the_lamloop_env_push_loop0] */

/*
// /home/hwxi/Research/ATS-Anairiats/src/ats_trans3_env_loop.dats: 2997(line=94, offs=3) -- 3109(line=96, offs=4)
*/
ATSglobaldec()
ats_void_type
ATS_2d0_2e2_2e12_2src_2ats_trans3_env_2esats__the_lamloop_env_push_loop1 (ats_ptr_type arg0, ats_ptr_type arg1, ats_ptr_type arg2, ats_ptr_type arg3) {
/* local vardec */
// ATSlocal_void (tmp22) ;
ATSlocal (ats_ptr_type, tmp23) ;

__ats_lab_ATS_2d0_2e2_2e12_2src_2ats_trans3_env_2esats__the_lamloop_env_push_loop1:
tmp23 = ATS_MALLOC(sizeof(anairiats_sum_2)) ;
((ats_sum_ptr_type)tmp23)->tag = 2 ;
ats_selptrset_mac(anairiats_sum_2, tmp23, atslab_0, arg0) ;
ats_selptrset_mac(anairiats_sum_2, tmp23, atslab_1, arg1) ;
ats_selptrset_mac(anairiats_sum_2, tmp23, atslab_2, arg2) ;
ats_selptrset_mac(anairiats_sum_2, tmp23, atslab_3, arg3) ;
/* tmp22 = */ the_lamloop_env_push_3 (tmp23) ;
return /* (tmp22) */ ;
} /* end of [ATS_2d0_2e2_2e12_2src_2ats_trans3_env_2esats__the_lamloop_env_push_loop1] */

/*
// /home/hwxi/Research/ATS-Anairiats/src/ats_trans3_env_loop.dats: 3221(line=103, offs=5) -- 3432(line=112, offs=2)
*/
ATSstaticdec()
ats_ptr_type
aux_8 (ats_ptr_type arg0) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp25) ;
ATSlocal (ats_ptr_type, tmp26) ;
ATSlocal (ats_ptr_type, tmp27) ;
ATSlocal (ats_ptr_type, tmp28) ;

__ats_lab_aux_8:
do {
/* branch: __ats_lab_2 */
__ats_lab_2_0:
if (arg0 == (ats_sum_ptr_type)0) { goto __ats_lab_5_0 ; }
__ats_lab_2_1:
tmp26 = ats_caselptrlab_mac(anairiats_sum_0, arg0, atslab_0) ;
tmp27 = ats_caselptrlab_mac(anairiats_sum_0, arg0, atslab_1) ;
do {
/* branch: __ats_lab_3 */
__ats_lab_3_0:
if (((ats_sum_ptr_type)tmp26)->tag != 0) { goto __ats_lab_4_0 ; }
__ats_lab_3_1:
tmp28 = ats_caselptrlab_mac(anairiats_sum_1, tmp26, atslab_0) ;
tmp25 = ATS_MALLOC(sizeof(anairiats_sum_3)) ;
ats_selptrset_mac(anairiats_sum_3, tmp25, atslab_0, tmp28) ;
break ;

/* branch: __ats_lab_4 */
__ats_lab_4_0:
__ats_lab_4_1:
arg0 = tmp27 ;
goto __ats_lab_aux_8 ; // tail call
break ;
} while (0) ;
break ;

/* branch: __ats_lab_5 */
__ats_lab_5_0:
// if (arg0 != (ats_sum_ptr_type)0) { ats_deadcode_failure_handle () ; }
__ats_lab_5_1:
tmp25 = (ats_sum_ptr_type)0 ;
break ;
} while (0) ;
return (tmp25) ;
} /* end of [aux_8] */

/*
// /home/hwxi/Research/ATS-Anairiats/src/ats_trans3_env_loop.dats: 3205(line=101, offs=25) -- 3542(line=117, offs=4)
*/
ATSglobaldec()
ats_ptr_type
ATS_2d0_2e2_2e12_2src_2ats_trans3_env_2esats__the_lamloop_env_arg_get () {
/* local vardec */
ATSlocal (ats_ptr_type, tmp24) ;
ATSlocal (ats_ptr_type, tmp29) ;
ATSlocal (ats_ptr_type, tmp30) ;
ATSlocal (ats_ptr_type, tmp31) ;

__ats_lab_ATS_2d0_2e2_2e12_2src_2ats_trans3_env_2esats__the_lamloop_env_arg_get:
tmp29 = ats_ptrget_mac(ats_ptr_type, statmp0) ;
do {
/* branch: __ats_lab_6 */
__ats_lab_6_0:
if (((ats_sum_ptr_type)tmp29)->tag != 0) { goto __ats_lab_7_0 ; }
__ats_lab_6_1:
tmp30 = ats_caselptrlab_mac(anairiats_sum_1, tmp29, atslab_0) ;
tmp24 = ATS_MALLOC(sizeof(anairiats_sum_3)) ;
ats_selptrset_mac(anairiats_sum_3, tmp24, atslab_0, tmp30) ;
break ;

/* branch: __ats_lab_7 */
__ats_lab_7_0:
__ats_lab_7_1:
tmp31 = ats_ptrget_mac(ats_ptr_type, statmp4) ;
tmp24 = aux_8 (tmp31) ;
break ;
} while (0) ;
return (tmp24) ;
} /* end of [ATS_2d0_2e2_2e12_2src_2ats_trans3_env_2esats__the_lamloop_env_arg_get] */

/* static load function */

extern ats_void_type ATS_2d0_2e2_2e12_2src_2ats_error_2esats__staload (void) ;
extern ats_void_type ATS_2d0_2e2_2e12_2src_2ats_dynexp3_2esats__staload (void) ;
extern ats_void_type ATS_2d0_2e2_2e12_2src_2ats_trans3_env_2esats__staload (void) ;
extern ats_void_type ATS_2d0_2e2_2e12_2src_2ats_reference_2esats__staload (void) ;
extern ats_void_type ATS_2d0_2e2_2e12_2src_2ats_reference_2edats__staload (void) ;

ats_void_type
ATS_2d0_2e2_2e12_2src_2ats_trans3_env_loop_2edats__staload () {
static int ATS_2d0_2e2_2e12_2src_2ats_trans3_env_loop_2edats__staload_flag = 0 ;
if (ATS_2d0_2e2_2e12_2src_2ats_trans3_env_loop_2edats__staload_flag) return ;
ATS_2d0_2e2_2e12_2src_2ats_trans3_env_loop_2edats__staload_flag = 1 ;

ATS_2d0_2e2_2e12_2src_2ats_error_2esats__staload () ;
ATS_2d0_2e2_2e12_2src_2ats_dynexp3_2esats__staload () ;
ATS_2d0_2e2_2e12_2src_2ats_trans3_env_2esats__staload () ;
ATS_2d0_2e2_2e12_2src_2ats_reference_2esats__staload () ;
ATS_2d0_2e2_2e12_2src_2ats_reference_2edats__staload () ;

return ;
} /* staload function */

/* dynamic load function */

// dynload flag declaration
extern ats_int_type ATS_2d0_2e2_2e12_2src_2ats_trans3_env_loop_2edats__dynload_flag ;

ats_void_type
ATS_2d0_2e2_2e12_2src_2ats_trans3_env_loop_2edats__dynload () {
ATS_2d0_2e2_2e12_2src_2ats_trans3_env_loop_2edats__dynload_flag = 1 ;
ATS_2d0_2e2_2e12_2src_2ats_trans3_env_loop_2edats__staload () ;

#ifdef _ATS_PROOFCHECK
#endif /* _ATS_PROOFCHECK */

/* marking static variables for GC */
ATS_GC_MARKROOT(&statmp0, sizeof(ats_ptr_type)) ;
ATS_GC_MARKROOT(&statmp3, sizeof(ats_ptr_type)) ;
ATS_GC_MARKROOT(&statmp4, sizeof(ats_ptr_type)) ;
ATS_GC_MARKROOT(&statmp5, sizeof(ats_ptr_type)) ;

/* marking external values for GC */

/* code for dynamic loading */
statmp3 = (ats_sum_ptr_type)(&ATS_2d0_2e2_2e12_2src_2ats_trans3_env_2esats__LMLPnone_3) ;
statmp0 = ref_make_elt_03658_ats_ptr_type (statmp3) ;
statmp5 = (ats_sum_ptr_type)0 ;
statmp4 = ref_make_elt_03658_ats_ptr_type (statmp5) ;
return ;
} /* end of [dynload function] */

/* external codes at mid */
/* external codes at bot */

/* ****** ****** */

/* end of [/home/hwxi/Research/ATS-Anairiats/bootstrap1/ats_trans3_env_loop_dats.c] */
