/*
**
** The C code is generated by ATS/Anairiats
** The compilation time is: 2016-8-25: 20h:18m
**
*/

/* include some .h files */
#ifndef _ATS_HEADER_NONE
#include "ats_config.h"
#include "ats_basics.h"
#include "ats_types.h"
#include "ats_exception.h"
#include "ats_memory.h"
#endif /* _ATS_HEADER_NONE */

/* prologues from statically loaded files */

#include "ats_counter.cats"

#include "ats_intinf.cats"

#include "ats_counter.cats"

#include "ats_intinf.cats"

#include "ats_counter.cats"

#include "ats_counter.cats"

#include "ats_intinf.cats"

#include "ats_counter.cats"
/* external codes at top */
/* type definitions */
typedef
struct {
ats_ptr_type atslab_hityp_name ;
ats_ptr_type atslab_hityp_node ;
} anairiats_rec_0 ;

/* external typedefs */
/* assuming abstract types */
/* sum constructor declarations */
ATSglobal(ats_sum_type, ATS_2d0_2e2_2e12_2src_2ats_hiexp_2esats__HITNAM_0) ;
ATSglobal(ats_sum_type, ATS_2d0_2e2_2e12_2src_2ats_hiexp_2esats__LABHITYPLSTcons_0) ;
ATSglobal(ats_sum_type, ATS_2d0_2e2_2e12_2src_2ats_hiexp_2esats__LABHITYPLSTnil_1) ;
ATSglobal(ats_sum_type, ATS_2d0_2e2_2e12_2src_2ats_hiexp_2esats__HITcltype_0) ;
ATSglobal(ats_sum_type, ATS_2d0_2e2_2e12_2src_2ats_hiexp_2esats__HITextype_1) ;
ATSglobal(ats_sum_type, ATS_2d0_2e2_2e12_2src_2ats_hiexp_2esats__HITfun_2) ;
ATSglobal(ats_sum_type, ATS_2d0_2e2_2e12_2src_2ats_hiexp_2esats__HITrefarg_3) ;
ATSglobal(ats_sum_type, ATS_2d0_2e2_2e12_2src_2ats_hiexp_2esats__HITs2var_4) ;
ATSglobal(ats_sum_type, ATS_2d0_2e2_2e12_2src_2ats_hiexp_2esats__HITtyarr_5) ;
ATSglobal(ats_sum_type, ATS_2d0_2e2_2e12_2src_2ats_hiexp_2esats__HITtyrec_6) ;
ATSglobal(ats_sum_type, ATS_2d0_2e2_2e12_2src_2ats_hiexp_2esats__HITtyrectemp_7) ;
ATSglobal(ats_sum_type, ATS_2d0_2e2_2e12_2src_2ats_hiexp_2esats__HITtyrecsin_8) ;
ATSglobal(ats_sum_type, ATS_2d0_2e2_2e12_2src_2ats_hiexp_2esats__HITtysum_9) ;
ATSglobal(ats_sum_type, ATS_2d0_2e2_2e12_2src_2ats_hiexp_2esats__HITtysumtemp_10) ;
ATSglobal(ats_sum_type, ATS_2d0_2e2_2e12_2src_2ats_hiexp_2esats__HITunion_11) ;
ATSglobal(ats_sum_type, ATS_2d0_2e2_2e12_2src_2ats_hiexp_2esats__HITvararg_12) ;
ATSglobal(ats_sum_type, ATS_2d0_2e2_2e12_2src_2ats_hiexp_2esats__TMPVAROPTsome_0) ;
ATSglobal(ats_sum_type, ATS_2d0_2e2_2e12_2src_2ats_hiexp_2esats__TMPVAROPTnone_1) ;
ATSglobal(ats_sum_type, ATS_2d0_2e2_2e12_2src_2ats_hiexp_2esats__LABHIPATLSTcons_0) ;
ATSglobal(ats_sum_type, ATS_2d0_2e2_2e12_2src_2ats_hiexp_2esats__LABHIPATLSTdot_1) ;
ATSglobal(ats_sum_type, ATS_2d0_2e2_2e12_2src_2ats_hiexp_2esats__LABHIPATLSTnil_2) ;
ATSglobal(ats_sum_type, ATS_2d0_2e2_2e12_2src_2ats_hiexp_2esats__HIPann_0) ;
ATSglobal(ats_sum_type, ATS_2d0_2e2_2e12_2src_2ats_hiexp_2esats__HIPany_1) ;
ATSglobal(ats_sum_type, ATS_2d0_2e2_2e12_2src_2ats_hiexp_2esats__HIPas_2) ;
ATSglobal(ats_sum_type, ATS_2d0_2e2_2e12_2src_2ats_hiexp_2esats__HIPbool_3) ;
ATSglobal(ats_sum_type, ATS_2d0_2e2_2e12_2src_2ats_hiexp_2esats__HIPchar_4) ;
ATSglobal(ats_sum_type, ATS_2d0_2e2_2e12_2src_2ats_hiexp_2esats__HIPcon_5) ;
ATSglobal(ats_sum_type, ATS_2d0_2e2_2e12_2src_2ats_hiexp_2esats__HIPcon_any_6) ;
ATSglobal(ats_sum_type, ATS_2d0_2e2_2e12_2src_2ats_hiexp_2esats__HIPempty_7) ;
ATSglobal(ats_sum_type, ATS_2d0_2e2_2e12_2src_2ats_hiexp_2esats__HIPfloat_8) ;
ATSglobal(ats_sum_type, ATS_2d0_2e2_2e12_2src_2ats_hiexp_2esats__HIPint_9) ;
ATSglobal(ats_sum_type, ATS_2d0_2e2_2e12_2src_2ats_hiexp_2esats__HIPlst_10) ;
ATSglobal(ats_sum_type, ATS_2d0_2e2_2e12_2src_2ats_hiexp_2esats__HIPrec_11) ;
ATSglobal(ats_sum_type, ATS_2d0_2e2_2e12_2src_2ats_hiexp_2esats__HIPstring_12) ;
ATSglobal(ats_sum_type, ATS_2d0_2e2_2e12_2src_2ats_hiexp_2esats__HIPvar_13) ;
ATSglobal(ats_sum_type, ATS_2d0_2e2_2e12_2src_2ats_hiexp_2esats__HILlab_0) ;
ATSglobal(ats_sum_type, ATS_2d0_2e2_2e12_2src_2ats_hiexp_2esats__HILind_1) ;
ATSglobal(ats_sum_type, ATS_2d0_2e2_2e12_2src_2ats_hiexp_2esats__LABHIEXPLSTcons_0) ;
ATSglobal(ats_sum_type, ATS_2d0_2e2_2e12_2src_2ats_hiexp_2esats__LABHIEXPLSTnil_1) ;
ATSglobal(ats_sum_type, ATS_2d0_2e2_2e12_2src_2ats_hiexp_2esats__HIEapp_0) ;
ATSglobal(ats_sum_type, ATS_2d0_2e2_2e12_2src_2ats_hiexp_2esats__HIEarrinit_1) ;
ATSglobal(ats_sum_type, ATS_2d0_2e2_2e12_2src_2ats_hiexp_2esats__HIEarrpsz_2) ;
ATSglobal(ats_sum_type, ATS_2d0_2e2_2e12_2src_2ats_hiexp_2esats__HIEassgn_ptr_3) ;
ATSglobal(ats_sum_type, ATS_2d0_2e2_2e12_2src_2ats_hiexp_2esats__HIEassgn_var_4) ;
ATSglobal(ats_sum_type, ATS_2d0_2e2_2e12_2src_2ats_hiexp_2esats__HIEbool_5) ;
ATSglobal(ats_sum_type, ATS_2d0_2e2_2e12_2src_2ats_hiexp_2esats__HIEcaseof_6) ;
ATSglobal(ats_sum_type, ATS_2d0_2e2_2e12_2src_2ats_hiexp_2esats__HIEcastfn_7) ;
ATSglobal(ats_sum_type, ATS_2d0_2e2_2e12_2src_2ats_hiexp_2esats__HIEchar_8) ;
ATSglobal(ats_sum_type, ATS_2d0_2e2_2e12_2src_2ats_hiexp_2esats__HIEcon_9) ;
ATSglobal(ats_sum_type, ATS_2d0_2e2_2e12_2src_2ats_hiexp_2esats__HIEcst_10) ;
ATSglobal(ats_sum_type, ATS_2d0_2e2_2e12_2src_2ats_hiexp_2esats__HIEcstsp_11) ;
ATSglobal(ats_sum_type, ATS_2d0_2e2_2e12_2src_2ats_hiexp_2esats__HIEdynload_12) ;
ATSglobal(ats_sum_type, ATS_2d0_2e2_2e12_2src_2ats_hiexp_2esats__HIEempty_13) ;
ATSglobal(ats_sum_type, ATS_2d0_2e2_2e12_2src_2ats_hiexp_2esats__HIEextval_14) ;
ATSglobal(ats_sum_type, ATS_2d0_2e2_2e12_2src_2ats_hiexp_2esats__HIEfix_15) ;
ATSglobal(ats_sum_type, ATS_2d0_2e2_2e12_2src_2ats_hiexp_2esats__HIEfloat_16) ;
ATSglobal(ats_sum_type, ATS_2d0_2e2_2e12_2src_2ats_hiexp_2esats__HIEfloatsp_17) ;
ATSglobal(ats_sum_type, ATS_2d0_2e2_2e12_2src_2ats_hiexp_2esats__HIEfreeat_18) ;
ATSglobal(ats_sum_type, ATS_2d0_2e2_2e12_2src_2ats_hiexp_2esats__HIEif_19) ;
ATSglobal(ats_sum_type, ATS_2d0_2e2_2e12_2src_2ats_hiexp_2esats__HIEint_20) ;
ATSglobal(ats_sum_type, ATS_2d0_2e2_2e12_2src_2ats_hiexp_2esats__HIEintsp_21) ;
ATSglobal(ats_sum_type, ATS_2d0_2e2_2e12_2src_2ats_hiexp_2esats__HIElam_22) ;
ATSglobal(ats_sum_type, ATS_2d0_2e2_2e12_2src_2ats_hiexp_2esats__HIElaminit_23) ;
ATSglobal(ats_sum_type, ATS_2d0_2e2_2e12_2src_2ats_hiexp_2esats__HIElazy_delay_24) ;
ATSglobal(ats_sum_type, ATS_2d0_2e2_2e12_2src_2ats_hiexp_2esats__HIElazy_ldelay_25) ;
ATSglobal(ats_sum_type, ATS_2d0_2e2_2e12_2src_2ats_hiexp_2esats__HIElazy_force_26) ;
ATSglobal(ats_sum_type, ATS_2d0_2e2_2e12_2src_2ats_hiexp_2esats__HIElet_27) ;
ATSglobal(ats_sum_type, ATS_2d0_2e2_2e12_2src_2ats_hiexp_2esats__HIEloop_28) ;
ATSglobal(ats_sum_type, ATS_2d0_2e2_2e12_2src_2ats_hiexp_2esats__HIEloopexn_29) ;
ATSglobal(ats_sum_type, ATS_2d0_2e2_2e12_2src_2ats_hiexp_2esats__HIElst_30) ;
ATSglobal(ats_sum_type, ATS_2d0_2e2_2e12_2src_2ats_hiexp_2esats__HIEptrof_ptr_31) ;
ATSglobal(ats_sum_type, ATS_2d0_2e2_2e12_2src_2ats_hiexp_2esats__HIEptrof_var_32) ;
ATSglobal(ats_sum_type, ATS_2d0_2e2_2e12_2src_2ats_hiexp_2esats__HIEraise_33) ;
ATSglobal(ats_sum_type, ATS_2d0_2e2_2e12_2src_2ats_hiexp_2esats__HIErec_34) ;
ATSglobal(ats_sum_type, ATS_2d0_2e2_2e12_2src_2ats_hiexp_2esats__HIErefarg_35) ;
ATSglobal(ats_sum_type, ATS_2d0_2e2_2e12_2src_2ats_hiexp_2esats__HIEsel_36) ;
ATSglobal(ats_sum_type, ATS_2d0_2e2_2e12_2src_2ats_hiexp_2esats__HIEsel_ptr_37) ;
ATSglobal(ats_sum_type, ATS_2d0_2e2_2e12_2src_2ats_hiexp_2esats__HIEsel_var_38) ;
ATSglobal(ats_sum_type, ATS_2d0_2e2_2e12_2src_2ats_hiexp_2esats__HIEseq_39) ;
ATSglobal(ats_sum_type, ATS_2d0_2e2_2e12_2src_2ats_hiexp_2esats__HIEsif_40) ;
ATSglobal(ats_sum_type, ATS_2d0_2e2_2e12_2src_2ats_hiexp_2esats__HIEsizeof_41) ;
ATSglobal(ats_sum_type, ATS_2d0_2e2_2e12_2src_2ats_hiexp_2esats__HIEstring_42) ;
ATSglobal(ats_sum_type, ATS_2d0_2e2_2e12_2src_2ats_hiexp_2esats__HIEtmpcst_43) ;
ATSglobal(ats_sum_type, ATS_2d0_2e2_2e12_2src_2ats_hiexp_2esats__HIEtmpvar_44) ;
ATSglobal(ats_sum_type, ATS_2d0_2e2_2e12_2src_2ats_hiexp_2esats__HIEtop_45) ;
ATSglobal(ats_sum_type, ATS_2d0_2e2_2e12_2src_2ats_hiexp_2esats__HIEtrywith_46) ;
ATSglobal(ats_sum_type, ATS_2d0_2e2_2e12_2src_2ats_hiexp_2esats__HIEvar_47) ;
ATSglobal(ats_sum_type, ATS_2d0_2e2_2e12_2src_2ats_hiexp_2esats__HIDlist_0) ;
ATSglobal(ats_sum_type, ATS_2d0_2e2_2e12_2src_2ats_hiexp_2esats__HIDsaspdec_1) ;
ATSglobal(ats_sum_type, ATS_2d0_2e2_2e12_2src_2ats_hiexp_2esats__HIDdcstdec_2) ;
ATSglobal(ats_sum_type, ATS_2d0_2e2_2e12_2src_2ats_hiexp_2esats__HIDdatdec_3) ;
ATSglobal(ats_sum_type, ATS_2d0_2e2_2e12_2src_2ats_hiexp_2esats__HIDexndec_4) ;
ATSglobal(ats_sum_type, ATS_2d0_2e2_2e12_2src_2ats_hiexp_2esats__HIDextype_5) ;
ATSglobal(ats_sum_type, ATS_2d0_2e2_2e12_2src_2ats_hiexp_2esats__HIDextval_6) ;
ATSglobal(ats_sum_type, ATS_2d0_2e2_2e12_2src_2ats_hiexp_2esats__HIDextern_7) ;
ATSglobal(ats_sum_type, ATS_2d0_2e2_2e12_2src_2ats_hiexp_2esats__HIDfundecs_8) ;
ATSglobal(ats_sum_type, ATS_2d0_2e2_2e12_2src_2ats_hiexp_2esats__HIDvaldecs_9) ;
ATSglobal(ats_sum_type, ATS_2d0_2e2_2e12_2src_2ats_hiexp_2esats__HIDvaldecs_par_10) ;
ATSglobal(ats_sum_type, ATS_2d0_2e2_2e12_2src_2ats_hiexp_2esats__HIDvaldecs_rec_11) ;
ATSglobal(ats_sum_type, ATS_2d0_2e2_2e12_2src_2ats_hiexp_2esats__HIDvardecs_12) ;
ATSglobal(ats_sum_type, ATS_2d0_2e2_2e12_2src_2ats_hiexp_2esats__HIDimpdec_13) ;
ATSglobal(ats_sum_type, ATS_2d0_2e2_2e12_2src_2ats_hiexp_2esats__HIDimpdec_prf_14) ;
ATSglobal(ats_sum_type, ATS_2d0_2e2_2e12_2src_2ats_hiexp_2esats__HIDlocal_15) ;
ATSglobal(ats_sum_type, ATS_2d0_2e2_2e12_2src_2ats_hiexp_2esats__HIDstaload_16) ;
ATSglobal(ats_sum_type, ATS_2d0_2e2_2e12_2src_2ats_hiexp_2esats__HIDdynload_17) ;
ATSglobal(ats_sum_type, ATS_2d0_2e2_2e12_2src_2ats_hiexp_2esats__LABSTRLSTcons_0) ;
ATSglobal(ats_sum_type, ATS_2d0_2e2_2e12_2src_2ats_hiexp_2esats__LABSTRLSTnil_1) ;
ATSglobal(ats_sum_type, ATS_2d0_2e2_2e12_2src_2ats_hiexp_2esats__TYPKEYrec_0) ;
ATSglobal(ats_sum_type, ATS_2d0_2e2_2e12_2src_2ats_hiexp_2esats__TYPKEYsum_1) ;
ATSglobal(ats_sum_type, ATS_2d0_2e2_2e12_2src_2ats_hiexp_2esats__TYPKEYuni_2) ;

/* exn constructor declarations */
/* static load function */

extern ats_void_type ATS_2d0_2e2_2e12_2src_2ats_syntax_2esats__staload (void) ;
extern ats_void_type ATS_2d0_2e2_2e12_2src_2ats_staexp2_2esats__staload (void) ;
extern ats_void_type ATS_2d0_2e2_2e12_2src_2ats_dynexp2_2esats__staload (void) ;

ats_void_type
ATS_2d0_2e2_2e12_2src_2ats_hiexp_2esats__staload () {
static int ATS_2d0_2e2_2e12_2src_2ats_hiexp_2esats__staload_flag = 0 ;
if (ATS_2d0_2e2_2e12_2src_2ats_hiexp_2esats__staload_flag) return ;
ATS_2d0_2e2_2e12_2src_2ats_hiexp_2esats__staload_flag = 1 ;

ATS_2d0_2e2_2e12_2src_2ats_syntax_2esats__staload () ;
ATS_2d0_2e2_2e12_2src_2ats_staexp2_2esats__staload () ;
ATS_2d0_2e2_2e12_2src_2ats_dynexp2_2esats__staload () ;

// ATS_2d0_2e2_2e12_2src_2ats_hiexp_2esats__HITNAM_0.tag = 0 ;
// ATS_2d0_2e2_2e12_2src_2ats_hiexp_2esats__LABHITYPLSTcons_0.tag = 0 ;
ATS_2d0_2e2_2e12_2src_2ats_hiexp_2esats__LABHITYPLSTnil_1.tag = 1 ;
// ATS_2d0_2e2_2e12_2src_2ats_hiexp_2esats__HITcltype_0.tag = 0 ;
// ATS_2d0_2e2_2e12_2src_2ats_hiexp_2esats__HITextype_1.tag = 1 ;
// ATS_2d0_2e2_2e12_2src_2ats_hiexp_2esats__HITfun_2.tag = 2 ;
// ATS_2d0_2e2_2e12_2src_2ats_hiexp_2esats__HITrefarg_3.tag = 3 ;
// ATS_2d0_2e2_2e12_2src_2ats_hiexp_2esats__HITs2var_4.tag = 4 ;
// ATS_2d0_2e2_2e12_2src_2ats_hiexp_2esats__HITtyarr_5.tag = 5 ;
// ATS_2d0_2e2_2e12_2src_2ats_hiexp_2esats__HITtyrec_6.tag = 6 ;
// ATS_2d0_2e2_2e12_2src_2ats_hiexp_2esats__HITtyrectemp_7.tag = 7 ;
// ATS_2d0_2e2_2e12_2src_2ats_hiexp_2esats__HITtyrecsin_8.tag = 8 ;
// ATS_2d0_2e2_2e12_2src_2ats_hiexp_2esats__HITtysum_9.tag = 9 ;
// ATS_2d0_2e2_2e12_2src_2ats_hiexp_2esats__HITtysumtemp_10.tag = 10 ;
// ATS_2d0_2e2_2e12_2src_2ats_hiexp_2esats__HITunion_11.tag = 11 ;
ATS_2d0_2e2_2e12_2src_2ats_hiexp_2esats__HITvararg_12.tag = 12 ;
// ATS_2d0_2e2_2e12_2src_2ats_hiexp_2esats__TMPVAROPTsome_0.tag = 0 ;
ATS_2d0_2e2_2e12_2src_2ats_hiexp_2esats__TMPVAROPTnone_1.tag = 1 ;
// ATS_2d0_2e2_2e12_2src_2ats_hiexp_2esats__LABHIPATLSTcons_0.tag = 0 ;
ATS_2d0_2e2_2e12_2src_2ats_hiexp_2esats__LABHIPATLSTdot_1.tag = 1 ;
ATS_2d0_2e2_2e12_2src_2ats_hiexp_2esats__LABHIPATLSTnil_2.tag = 2 ;
// ATS_2d0_2e2_2e12_2src_2ats_hiexp_2esats__HIPann_0.tag = 0 ;
ATS_2d0_2e2_2e12_2src_2ats_hiexp_2esats__HIPany_1.tag = 1 ;
// ATS_2d0_2e2_2e12_2src_2ats_hiexp_2esats__HIPas_2.tag = 2 ;
// ATS_2d0_2e2_2e12_2src_2ats_hiexp_2esats__HIPbool_3.tag = 3 ;
// ATS_2d0_2e2_2e12_2src_2ats_hiexp_2esats__HIPchar_4.tag = 4 ;
// ATS_2d0_2e2_2e12_2src_2ats_hiexp_2esats__HIPcon_5.tag = 5 ;
// ATS_2d0_2e2_2e12_2src_2ats_hiexp_2esats__HIPcon_any_6.tag = 6 ;
ATS_2d0_2e2_2e12_2src_2ats_hiexp_2esats__HIPempty_7.tag = 7 ;
// ATS_2d0_2e2_2e12_2src_2ats_hiexp_2esats__HIPfloat_8.tag = 8 ;
// ATS_2d0_2e2_2e12_2src_2ats_hiexp_2esats__HIPint_9.tag = 9 ;
// ATS_2d0_2e2_2e12_2src_2ats_hiexp_2esats__HIPlst_10.tag = 10 ;
// ATS_2d0_2e2_2e12_2src_2ats_hiexp_2esats__HIPrec_11.tag = 11 ;
// ATS_2d0_2e2_2e12_2src_2ats_hiexp_2esats__HIPstring_12.tag = 12 ;
// ATS_2d0_2e2_2e12_2src_2ats_hiexp_2esats__HIPvar_13.tag = 13 ;
// ATS_2d0_2e2_2e12_2src_2ats_hiexp_2esats__HILlab_0.tag = 0 ;
// ATS_2d0_2e2_2e12_2src_2ats_hiexp_2esats__HILind_1.tag = 1 ;
// ATS_2d0_2e2_2e12_2src_2ats_hiexp_2esats__LABHIEXPLSTcons_0.tag = 0 ;
ATS_2d0_2e2_2e12_2src_2ats_hiexp_2esats__LABHIEXPLSTnil_1.tag = 1 ;
// ATS_2d0_2e2_2e12_2src_2ats_hiexp_2esats__HIEapp_0.tag = 0 ;
// ATS_2d0_2e2_2e12_2src_2ats_hiexp_2esats__HIEarrinit_1.tag = 1 ;
// ATS_2d0_2e2_2e12_2src_2ats_hiexp_2esats__HIEarrpsz_2.tag = 2 ;
// ATS_2d0_2e2_2e12_2src_2ats_hiexp_2esats__HIEassgn_ptr_3.tag = 3 ;
// ATS_2d0_2e2_2e12_2src_2ats_hiexp_2esats__HIEassgn_var_4.tag = 4 ;
// ATS_2d0_2e2_2e12_2src_2ats_hiexp_2esats__HIEbool_5.tag = 5 ;
// ATS_2d0_2e2_2e12_2src_2ats_hiexp_2esats__HIEcaseof_6.tag = 6 ;
// ATS_2d0_2e2_2e12_2src_2ats_hiexp_2esats__HIEcastfn_7.tag = 7 ;
// ATS_2d0_2e2_2e12_2src_2ats_hiexp_2esats__HIEchar_8.tag = 8 ;
// ATS_2d0_2e2_2e12_2src_2ats_hiexp_2esats__HIEcon_9.tag = 9 ;
// ATS_2d0_2e2_2e12_2src_2ats_hiexp_2esats__HIEcst_10.tag = 10 ;
// ATS_2d0_2e2_2e12_2src_2ats_hiexp_2esats__HIEcstsp_11.tag = 11 ;
// ATS_2d0_2e2_2e12_2src_2ats_hiexp_2esats__HIEdynload_12.tag = 12 ;
ATS_2d0_2e2_2e12_2src_2ats_hiexp_2esats__HIEempty_13.tag = 13 ;
// ATS_2d0_2e2_2e12_2src_2ats_hiexp_2esats__HIEextval_14.tag = 14 ;
// ATS_2d0_2e2_2e12_2src_2ats_hiexp_2esats__HIEfix_15.tag = 15 ;
// ATS_2d0_2e2_2e12_2src_2ats_hiexp_2esats__HIEfloat_16.tag = 16 ;
// ATS_2d0_2e2_2e12_2src_2ats_hiexp_2esats__HIEfloatsp_17.tag = 17 ;
// ATS_2d0_2e2_2e12_2src_2ats_hiexp_2esats__HIEfreeat_18.tag = 18 ;
// ATS_2d0_2e2_2e12_2src_2ats_hiexp_2esats__HIEif_19.tag = 19 ;
// ATS_2d0_2e2_2e12_2src_2ats_hiexp_2esats__HIEint_20.tag = 20 ;
// ATS_2d0_2e2_2e12_2src_2ats_hiexp_2esats__HIEintsp_21.tag = 21 ;
// ATS_2d0_2e2_2e12_2src_2ats_hiexp_2esats__HIElam_22.tag = 22 ;
// ATS_2d0_2e2_2e12_2src_2ats_hiexp_2esats__HIElaminit_23.tag = 23 ;
// ATS_2d0_2e2_2e12_2src_2ats_hiexp_2esats__HIElazy_delay_24.tag = 24 ;
// ATS_2d0_2e2_2e12_2src_2ats_hiexp_2esats__HIElazy_ldelay_25.tag = 25 ;
// ATS_2d0_2e2_2e12_2src_2ats_hiexp_2esats__HIElazy_force_26.tag = 26 ;
// ATS_2d0_2e2_2e12_2src_2ats_hiexp_2esats__HIElet_27.tag = 27 ;
// ATS_2d0_2e2_2e12_2src_2ats_hiexp_2esats__HIEloop_28.tag = 28 ;
// ATS_2d0_2e2_2e12_2src_2ats_hiexp_2esats__HIEloopexn_29.tag = 29 ;
// ATS_2d0_2e2_2e12_2src_2ats_hiexp_2esats__HIElst_30.tag = 30 ;
// ATS_2d0_2e2_2e12_2src_2ats_hiexp_2esats__HIEptrof_ptr_31.tag = 31 ;
// ATS_2d0_2e2_2e12_2src_2ats_hiexp_2esats__HIEptrof_var_32.tag = 32 ;
// ATS_2d0_2e2_2e12_2src_2ats_hiexp_2esats__HIEraise_33.tag = 33 ;
// ATS_2d0_2e2_2e12_2src_2ats_hiexp_2esats__HIErec_34.tag = 34 ;
// ATS_2d0_2e2_2e12_2src_2ats_hiexp_2esats__HIErefarg_35.tag = 35 ;
// ATS_2d0_2e2_2e12_2src_2ats_hiexp_2esats__HIEsel_36.tag = 36 ;
// ATS_2d0_2e2_2e12_2src_2ats_hiexp_2esats__HIEsel_ptr_37.tag = 37 ;
// ATS_2d0_2e2_2e12_2src_2ats_hiexp_2esats__HIEsel_var_38.tag = 38 ;
// ATS_2d0_2e2_2e12_2src_2ats_hiexp_2esats__HIEseq_39.tag = 39 ;
// ATS_2d0_2e2_2e12_2src_2ats_hiexp_2esats__HIEsif_40.tag = 40 ;
// ATS_2d0_2e2_2e12_2src_2ats_hiexp_2esats__HIEsizeof_41.tag = 41 ;
// ATS_2d0_2e2_2e12_2src_2ats_hiexp_2esats__HIEstring_42.tag = 42 ;
// ATS_2d0_2e2_2e12_2src_2ats_hiexp_2esats__HIEtmpcst_43.tag = 43 ;
// ATS_2d0_2e2_2e12_2src_2ats_hiexp_2esats__HIEtmpvar_44.tag = 44 ;
ATS_2d0_2e2_2e12_2src_2ats_hiexp_2esats__HIEtop_45.tag = 45 ;
// ATS_2d0_2e2_2e12_2src_2ats_hiexp_2esats__HIEtrywith_46.tag = 46 ;
// ATS_2d0_2e2_2e12_2src_2ats_hiexp_2esats__HIEvar_47.tag = 47 ;
// ATS_2d0_2e2_2e12_2src_2ats_hiexp_2esats__HIDlist_0.tag = 0 ;
// ATS_2d0_2e2_2e12_2src_2ats_hiexp_2esats__HIDsaspdec_1.tag = 1 ;
// ATS_2d0_2e2_2e12_2src_2ats_hiexp_2esats__HIDdcstdec_2.tag = 2 ;
// ATS_2d0_2e2_2e12_2src_2ats_hiexp_2esats__HIDdatdec_3.tag = 3 ;
// ATS_2d0_2e2_2e12_2src_2ats_hiexp_2esats__HIDexndec_4.tag = 4 ;
// ATS_2d0_2e2_2e12_2src_2ats_hiexp_2esats__HIDextype_5.tag = 5 ;
// ATS_2d0_2e2_2e12_2src_2ats_hiexp_2esats__HIDextval_6.tag = 6 ;
// ATS_2d0_2e2_2e12_2src_2ats_hiexp_2esats__HIDextern_7.tag = 7 ;
// ATS_2d0_2e2_2e12_2src_2ats_hiexp_2esats__HIDfundecs_8.tag = 8 ;
// ATS_2d0_2e2_2e12_2src_2ats_hiexp_2esats__HIDvaldecs_9.tag = 9 ;
// ATS_2d0_2e2_2e12_2src_2ats_hiexp_2esats__HIDvaldecs_par_10.tag = 10 ;
// ATS_2d0_2e2_2e12_2src_2ats_hiexp_2esats__HIDvaldecs_rec_11.tag = 11 ;
// ATS_2d0_2e2_2e12_2src_2ats_hiexp_2esats__HIDvardecs_12.tag = 12 ;
// ATS_2d0_2e2_2e12_2src_2ats_hiexp_2esats__HIDimpdec_13.tag = 13 ;
// ATS_2d0_2e2_2e12_2src_2ats_hiexp_2esats__HIDimpdec_prf_14.tag = 14 ;
// ATS_2d0_2e2_2e12_2src_2ats_hiexp_2esats__HIDlocal_15.tag = 15 ;
// ATS_2d0_2e2_2e12_2src_2ats_hiexp_2esats__HIDstaload_16.tag = 16 ;
// ATS_2d0_2e2_2e12_2src_2ats_hiexp_2esats__HIDdynload_17.tag = 17 ;
// ATS_2d0_2e2_2e12_2src_2ats_hiexp_2esats__LABSTRLSTcons_0.tag = 0 ;
ATS_2d0_2e2_2e12_2src_2ats_hiexp_2esats__LABSTRLSTnil_1.tag = 1 ;
// ATS_2d0_2e2_2e12_2src_2ats_hiexp_2esats__TYPKEYrec_0.tag = 0 ;
// ATS_2d0_2e2_2e12_2src_2ats_hiexp_2esats__TYPKEYsum_1.tag = 1 ;
// ATS_2d0_2e2_2e12_2src_2ats_hiexp_2esats__TYPKEYuni_2.tag = 2 ;
return ;
} /* staload function */

/* external codes at mid */
/* external codes at bot */

/* ****** ****** */

/* end of [/home/hwxi/Research/ATS-Anairiats/bootstrap1/ats_hiexp_sats.c] */
