#
# A simple Makefile
#

######

all:: p1
all:: p2
all:: p3
all:: p4

######

p1: ; make -C problem1
p2: ; make -C problem2
p3: ; make -C problem3
p4: ; make -C problem4

######

cleanall:: ; make -C problem1 cleanall
cleanall:: ; make -C problem2 cleanall
cleanall:: ; make -C problem3 cleanall
cleanall:: ; make -C problem4 cleanall

###### end of [Makefile] ######
